### ISSUE TITLE
Can't use proxy models with django-reversion

### ISSUE THREAD

**Issue by freevoid** [etianen/django-reversion#134]
Hello!

Currently exception is thrown when one tries to register a proxy model. Advice is to register a parent class.

But django emits `post_save` signal with a proxy model class as a sender (*not a parent class*) so `_post_save_receiver` is omitted and thus a version/revision is lost.

Why exactly we may want to restrict proxy-model registration?

It works for me if I register both parent and proxy-child (assuming that I've commented out `raise RegistrationError(..)`).

**Comment by electroniceagle** [comment]
@creimers did you try this with the master branch?  I don't think this fix is in the packaged release.

**Comment by gentleShark** [comment]
@electroniceagle I installed the master branch from source after coming across the same issue with djangocms-cascade 0.4.x but the problem remains.  
@creimers @jrief Any success getting djangocms-cascade 0.4.x and reversion to play nice?

**Comment by jrief** [comment]
@gentleShark No, not yet

**Comment by etianen** [comment]
I don’t have the time at the moment to investigate this directly, but will merge any likely-looking pull requests with tests. I was under the impression that the proxy model issue had been resolved...

**Comment by honi** [comment]
It appears to work with proxy models, the only bug I'm facing is that in the recover deleted items view all instances of the concrete model are listed, i.e. history is not filtered exclusively for the proxy model.

django@1.7.7 and django-reversion@1.8.5

**Comment by etianen** [comment]
Seems that the recover deleted items view really is listing versions for all instances of the concrete model. This has just been reported again in #500. Any ideas, @bourivouh ?

**Comment by bourivouh** [comment]
I don't use recover view, so I have no idea right now. I'll try to understand this, when I have time. Maybe on the next week.

**Comment by lpakula** [comment]
What i did to fix this:
```
# revisions.py
def get_deleted(self, model_class, db=None, model_db=None):
    """
    Returns all the deleted versions for the given model class.

    The results are returned with the most recent versions first.
    """
    model_db = model_db or db
    -- content_type = ContentType.objects.db_manager(db).get_for_model(model_class)
    ++ content_type = ContentType.objects.db_manager(db).get_for_model(model_class, for_concrete_model=False)
```

I have no time to create pull request at the moment. If that's right for you i can do it soon

**Comment by etianen** [comment]
That seems reasonable. I'm away at the moment, but can merge a pull request
from anyway with the motivation to create one! :)

**Comment by lpakula** [comment]
I looked into this problem in more details. And there are other bits need to be changed in order to get this sorted: 
- when we create initial revisions to set correct content_type
- on history view to get objects with correct content_type
- on deleted list to get objects with correct content_type

I see backward compatibility challenge here -  all current revisions with wrong(old) content_type will be missing. I think we need some mechanism to keep the history like datamigration for proxy models.

I'll create pull request to solve the problem first, and then we need to discuss what about backward compatibility

**Comment by etianen** [comment]
There was talk of adding a `for_concrete_model=True` flag to reversion.register(). This seems like the only way to preserve backwards compatibility and keep everyone happy.

See #465

**Comment by etianen** [comment]
The refactor branch includes better support for proxy models by adding the `for_concrete_model` kwarg to `reversion.register()`.

https://github.com/etianen/django-reversion/tree/refactor

**Comment by sobolevn** [comment]
@etianen What the current status for this feature?

I have tried to use with no luck. Using the latest `django-reversion` and `django`.

```python
@admin.register(InnerClient)
class ClientsAdmin(VersionAdmin):
    list_display = ('contract', 'email', 'name')
    search_fields = ('contract', 'email', 'name')
```

**Comment by etianen** [comment]
There appears to be a bug: #628 

I don't have time to fix it at the moment, but will happily review accept pull requests.

**Comment by etianen** [comment]
Oh, hang on, that's to do with inheritance, not proxy models.

What's not working with Proxy models?

**Comment by sobolevn** [comment]
I would say that was a documentation issue.

I had to add 

```python
def reversion_register(self, model, **kwargs):
        return super().reversion_register(
            model, for_concrete_model=False, **kwargs,
        )
```

to get it working.

**Comment by etianen** [comment]
I've just made the docs more explicit for this use case. Thanks for the suggestion!

**Comment by miguelfg** [comment]
> I would say that was a documentation issue.
> 
> I had to add
> 
> ```python
>     def reversion_register(self, model, **kwargs):
>         return super().reversion_register(
>             model, for_concrete_model=False, **kwargs,
>         )
> ```
> 
> to get it working.

Sorry, but where this is meant to be? in the admin.py at the base class that is extending 'VersionAdmin', so here?
```

@admin.register(MyModel)
class MyModelAdmin(VersionAdmin):
```

**Comment by etianen** [comment]
Yup! That's where.
