### ISSUE TITLE
When saving a revision, automatically create an initial revision if there's none. 

### ISSUE THREAD

**Issue by etienned** [etianen/django-reversion#152]
General motivation: don't save unnecessary revisions to save database space and time (CPU, DB access).

It can be a good match for data that is not edited really often but that can be edited manually.

Examples :

1. Blog entries, many entries are never edited after the creation.
2. Legacy data already in the database (before reversion was active).
3. Legacy data imported from elsewhere (old DB, CSV, etc.).
4. Data coming automatically from an external source (aggregator, parser, etc.), could be at high speed so less CPU and DB access is an advantage.

I implemented it here: https://github.com/etienned/django-reversion/commit/b0b4f4bf498f6438ab5e66f39c1f2b2dc60b0906

Commits after that are mostly optimisations. I'm really not sure that one of the last (lazily connecting auto_initial pre_save signals) is worth the trouble. But it prevent to connect the `pre_save` signal to model that don't use the auto_initial feature.

Someone interested in having this feature added to reversion?

**Comment by etianen** [comment]
reversion.revision._save_revision() function still exists. I can't remember
why it was removed from the public API.

I'm about to do a new django-reversion release. I'll put this function back
in the public API>

**Comment by etianen** [comment]
Oh, damn, it's actually really hard to add this functionality back in.
There's a lot of difficult logic in adding something to a revision that's
hard to untangle.

For simple cases, you could manually create a revision using the Version
and Revision models directly.

**Comment by dbischof** [comment]
Creating the Version and Revision models manually worked for my simple case. Thanks for the nudge.

**Comment by etianen** [comment]
Sorry it’s not easier!
