### ISSUE TITLE
VersionAdmin should be able to set "exclude" and other reversion options

### ISSUE THREAD

**Issue by erikcw** [etianen/django-reversion#180]
Being able to set the "exclude" parameter and other options when registering with VersionAdmin would be helpful.  

If one wants to use both VersionAdmin, and include some advanced settings, the model needs to be registered with VersionAdmin (to get access to the admin features), and then immediately unregister the model and re-register it with the other options.

This isn't very DRY.  You are forced to reregister all of the "follow" options that are implicitly setup by VersionAdmin.

Perhaps just being able to pass in an "extra_options" dict and VersionAdmin could **kwargs it into its internal call tl reversion.register.

Alternatively, a public API for adding options to registered models would work.

**Comment by etianen** [comment]
The admin class now includes:

``` py
def register_model_with_reversion(self, model, **kwargs):
        """
        Registers the given model with reversion, using the given kwargs.

        Override to provide additional arguments to the reversion.register() call.
        """
        self.revision_manager.register(model, **kwargs)
```

Override this method to perform custom per-model registration logic.

**Comment by arogachev** [comment]
It's now called `reversion_register`:

```python
def reversion_register(self, model, **kwargs):
    """Registers the model with reversion."""
    register(model, **kwargs)
```
