### ISSUE TITLE
Revisiting Optimizing Datamigration 0004

### ISSUE THREAD

**Issue by crccheck** [etianen/django-reversion#212]
So [migration 0004](https://github.com/etianen/django-reversion/blob/master/src/reversion/migrations/0004_populate_object_id_int.py) blows up (Python ran out of memory) on my machine. I've got a fair number of Versions...

```
>>> Version.objects.count()
421560
```

I came up with two alternatives:

1) The first one I tried was chunking the queryset using http://djangosnippets.org/snippets/1949/ It worked, albeit slow. I even left DEBUG=True and barely used any memory.

2) The second thing I tried was doing an update query using an F object and relying on my database (mysql) to coerce the type.

```
>>> from django.db.models import F
>>> Version.objects.all().update(object_id_int=F('object_id'))
```

My mysqlslow.log:

```
# Query_time: 32  Lock_time: 0  Rows_sent: 0  Rows_examined: 0
UPDATE `reversion_version` SET `object_id_int` = `reversion_version`.`object_id`;
```

Now I knew that all _my_ object_id's were ints, but migration 0004 could be rewritten to do a do a mass update for every `content_type`. Is this something worth writing? I'd be willing to give it a shot.

**Comment by fluther** [comment]
Just an update on this -- I ran into the same problem recently while upgrading an ancient project with 5.4MM versioned rows. I'd segfault or have the process killed because it would eat up all the RAM on the machine.

Chunking the queryset fixed the memory issue.

**Comment by etianen** [comment]
Just to confirm, you know that this issue applies to the old south migrations... not the new migrations introduced in v2.0.0?
