### ISSUE TITLE
'ascii' codec can't decode byte 0xc3 in position 4: ordinal not in range(128) [Ç]

### ISSUE THREAD

**Issue by pedrovgp** [etianen/django-reversion#245]
When trying to delete an object of a model tracked by reversion and which name attribute contains Ç (SUIÇA for example), I get this error message:

'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128).

The error seems to be in line 300 of reversion\revisions.py.

I only detected the problem with Ç, but not with ç.

**Comment by aaronmader** [comment]
This thread was helpful to me. I had written a `__unicode__` method which was returning a string. Leading to this error.

Bad:

    def __unicode__(self):
        return "%s is %s's %s" % (self.p2, self.p1, self.get_relation())

Good:

    def __unicode__(self):
        return u"%s is %s's %s" % (self.p2, self.p1, self.get_relation())

**Comment by pedrovgp** [comment]
I am glad to know it helped somebody else :)
