### ISSUE TITLE
revision_view and recover_view broken when ATOMIC_REQUESTS = True on Django 1.6

### ISSUE THREAD

**Issue by ghost** [etianen/django-reversion#268]
From https://docs.djangoproject.com/en/dev/topics/db/transactions/#transaction-middleware, TransactionMiddleware is deprecated in Django 1.6; after removing it from the MIDDLEWARE_CLASSES, and settings ATOMIC_REQUESTS to True in the database settings, displaying either the revision_view or recover_view will raise an TransactionManagementError exception: "This is forbidden when an 'atomic' block is active"

Replacing both instances of @transaction.commit_on_success in admin.py (in front of recover_view and revision_view) by @transaction.atomic, as advised in Django's doc (https://docs.djangoproject.com/en/dev/topics/db/transactions/#transaction-middleware) fixes the problem for me.

**Comment by guettli** [comment]
Just of the records, we try to solve this issue, and started a discussion on django-devel
https://groups.google.com/forum/#!topic/django-developers/uW5Ogio8QBc

**Comment by etianen** [comment]
Good luck! Django middleware needs an overhaul. Fight the good fight!

**Comment by guettli** [comment]
@etianen good news: the middleware rewrite was done in 1.10

See: https://docs.djangoproject.com/en/1.10/releases/1.10/#new-style-middleware

Do you plan, to integrate this?

**Comment by etianen** [comment]
Django reversion >= 2.0 uses new-style middleware and wraps every request in a transaction when using RevisionMiddleware.

So, it's already done!
