### ISSUE TITLE
int() argument must be a string or a number, not 'NoneType' error with django 1.6

### ISSUE THREAD

**Issue by shawnwall** [etianen/django-reversion#272]
After upgrading reversion to 1.8 (and running migration) to work with django 1.6.1 I get the following error when saving:

_int() argument must be a string or a number, not 'NoneType'_

revisions.py in get_version_data

`object_id_int = int(obj.pk)`

Any clues as to what could be going on here? The docs state reversion 1.8 works with django 1.6.

**Comment by mountainpaul** [comment]
I ran into this same error. When doing a delete of a form.instance of a model. Doing the delete resulted in the id of the instance being set to None (which makes some sense). Saving the id prior to delete and then reassigning it to the instance resolved the problem, but is probably not the ideal solution.

**Comment by lpakula** [comment]
I have the same issue when i override model ``delete()`` method and call ``save()`` method within this ``delete()`` to do some cleanup. Basically i change one flag of the model(and save) before delete. 

That eventually try to create revision of the model what is about to be deleted.
I just changed my ``delete()`` method. I hope this may help someone

**Comment by Woseseltops** [comment]
I managed to solve this using the comments above. The patch for me:

    +                pk = gloss.pk
                     gloss.delete()
    +                gloss.pk = pk
