### ISSUE TITLE
Ignore field in change detection

### ISSUE THREAD

**Issue by chrisspen** [etianen/django-reversion#273]
How would you instruct reversion to ignore a field when checking for a change?

I'm currently trying to prevent duplicate versions by using `ignore_duplicate_revisions = True` and setting `set_ignore_duplicates(True)` but they're not having any effect.

After inspecting the `reversion_version` table, this appears to be caused by my use of a DateTimeField() with `auto_now=True`. I want to track the change to all user-entered values, but reversion is detecting the change to this auto-updating value which changes every time a model's save() method is called, even if no other fields actually change.

e.g. I have a model like:

```
from django.db import models

from reversion import register, create_revision, set_ignore_duplicates, revision_context_manager, get_unique_for_object
from reversion.revisions import RegistrationError

class Data(models.Model):

    value = models.FloatField(
        blank=True,
        null=True)

    updated = models.DateTimeField(
        auto_now_add=True,
        auto_now=True)

    def save(self, *args, **kwargs):
        with create_revision():
            set_ignore_duplicates(True)
            super(Domain, self).save(*args, **kwargs)

try:
    register(Data)
except RegistrationError:
    pass
```

And in my admin.py:

```
from django.contrib import admin
from reversion.admin import VersionAdmin
import models

class DataAdmin(VersionAdmin):
    pass

admin.site.register(models.Data, DataAdmin)
```

If a user saves the model in admin, of the model gets saved elsewhere (such as by a management command) without any changes being made, no new version should be created, but yet a new version is created due to the change to `updated`.

Does this make sense? How would I instruct certain fields be ignored by change detection?

**Comment by rrauenza** [comment]
This is now documented at http://django-reversion.readthedocs.io/en/latest/api.html#registration-api -- see exclude()
