### ISSUE TITLE
Version.object_id lookups too slow

### ISSUE THREAD

**Issue by asfaltboy** [etianen/django-reversion#295]
In cases where the `pk` field of a given model is not an int, the `object_id_int` is not being used. If a lot of rows exists for this model, it makes the lookups very very slow.

These look ups can be made considerably faster by adding a `db_index=True` attribute to the text field.

It seems `South` does allow creating a schemamigration for this and it runs with sqlite and postgresql. Also, [Django adds a type specific index](https://docs.djangoproject.com/en/dev/ref/databases/#indexes-for-varchar-and-text-columns) (if db supports it).

Is there any reason why this can't be added?

**Comment by ajferrick** [comment]
Hey! I have been running into this issue as well. Saving versions take an inordinate amount of time because of a subquery using `object_id` instead of the indexed `object_id_int`.

Would you still be open to a PR that adds a migration in the style above?

**Comment by etianen** [comment]
How would you suggest doing this? There are a couple of possible approaches:

1. Change the TextField to a CharField(max_length=191, db_index=True)
    pro: relatively simple, and could also probably remove the IntegerField on Version and use the new CharField for models.
    con: Won't work for models with very long primary keys.

2. Add another CharField(max_length=191, db_index=True) to the model, and use this for models whose primary key is a CharField of compatible length.
    pro: Works everywhere
    con: Complicated, and still slow for models with a long string PK.

3. Add an index to the TextField if the database is not MySQL.
    pro: Speeds up everything but MySQL.
    con: Doesn't speed up MySQL.

I can't decide between 1 or 3.

**Comment by asfaltboy** [comment]
Personally, I like 1 just because it works everywhere, I honestly don't believe I've ever encountered a PK with over 64 characters and see little reason to use a TextField for it.

All we need to make this work is a `TextField` -> `CharField` migration, some clear documentation and a major version bump (potentially backward incompatible change).

**Comment by etianen** [comment]
I'm not so sure. 1 changes existing functionality, while 2 improves functionality for everyone but MySQL.

TBH, there's also a fourth option, which is to insist that models used with reversion have an integer primary key, and to drop the TextField entirely. I've never been sure what the reasons are for not having an integer primary key on a model...

**Comment by asfaltboy** [comment]
The reason (at least for projects I’ve worked on) is to use a type of UUID as primary key.

**Comment by etianen** [comment]
Oh, yeah, that's a pretty good reason.

Okay, how about this:

1. Change the object_id TextField to a CharField(max_length=191, db_index=True)
2. Remove the object_id_int field.
3. Remove all code that references the object_id_int field and primary-key detection.

The end result will work for 99% of existing users, and will be simpler to maintain in the long-run.

**Comment by ajferrick** [comment]
That sounds reasonable to me. I think removing the `object_id_int` field will clean up some of the existing code.

I think @asfaltboy is right that the patch should include clear documentation on the potentially breaking change, and probably be involved in a major version bump.

**Comment by etianen** [comment]
I think a major version bump would be OTT, given that the API remains the
same. I've been using a convention so far where patch versions are
backwards-compatible, and minor versions include slight
backwards-incompatibilities (similar to have Django seems to be doing
things). So that would make this change become django-reversion 1.11.0.

Happy to take a pull request for this feature. It sounds good.

**Comment by asfaltboy** [comment]
If no-one’s handled it by the weekend I’ll be happy to give it a shot.

**Comment by ajferrick** [comment]
I'm going to give it a shot as well, hopefully it shouldn't be too big of a change.

**Comment by etianen** [comment]
Closed by 54288b055ad8a8dca75e18482f9d90e88805281b

**Comment by asfaltboy** [comment]
Sorry for not coming through, we're all talk and no action, thanks for the fix  @etianen !
