### ISSUE TITLE
Inline model contents in Change History but lost on Save

### ISSUE THREAD

**Issue by ahernp** [etianen/django-reversion#33]
Inline model contents are lost when a parent model instance is recovered following a deletion.

Perhaps I have not set django-reversion up properly but the low-level API documentation seems to say that making the parent model a subclass of VersionAdmin should be sufficient.

Plus the inline content is appearing correctly in the version preview. It is just not being saved.

I've tried registering both models via VersionAdmin as well as the API but have been unable to get the inline data to be restored. Please advise.

Steps to recreate:
1. Vanilla install of Django (version 1.2.3) & Django-Reversion (version 1.3.2) - Python version 2.6.5.
2. Setup Django app with model and admin definitions below. Document model has DocumentPage inline.
3. Create a Document with a DocumentPage.
4. Delete the Document.
5. Choose "Recover deleted documents" option & select the version just deleted.
6. Note that the Recover preview shows the inline DocumentPage correctly.
7. Press Save.
8. The parent Document is saved but the inline DocumentPage is not.

models.py:

```
class Document(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()

class DocumentPage(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    document = models.ForeignKey(Document)
```

admin.py:

```
from django.contrib import admin
from reversion.admin import VersionAdmin
from demo.rev.models import Document, DocumentPage

class DocumentPageInline(admin.TabularInline):
    model = DocumentPage

class DocumentAdmin(VersionAdmin):
    inlines = [DocumentPageInline,]

class DocumentPageAdmin(VersionAdmin):
    pass

admin.site.register(Document, DocumentAdmin)
admin.site.register(DocumentPage, DocumentPageAdmin)
```

**Comment by corebyte** [comment]
Sorry for opening this ticket again but i have the same issue with reversion (latest) and inline model of invoice that are invoicerules. Working with django==1.8.

My admin.py

```python
from django.contrib import admin
from reversion.admin import VersionAdmin
import models


class InvoiceRuleInlineAdmin(admin.TabularInline):
    model = models.InvoiceRule
    extra = 1


class InvoiceAdmin(VersionAdmin):
    list_display = ('company', 'number')
    list_filter = ['company']
    search_fields = ['company']
    ordering = ('-company',)
    inlines = [InvoiceRuleInlineAdmin]


admin.site.register(models.Invoice, InvoiceAdmin)
```

**Comment by etianen** [comment]
Do you mean it's working with Django 1.8, or that you're using Django 1.8 and it's not working?
