### ISSUE TITLE
Readonly fields get displayed incorrectly in History view

### ISSUE THREAD

**Issue by dgaus** [etianen/django-reversion#339]
I am trying to show users a read-only version of objects' history. The problem is, if I set any fields as read-only, then those show the current version of the object instead of the Version's. 
This seems to be because the render_revision_form method is using the ModelForm 'initial' argument, and then the fieldset.html template does {{ field.contents }}, which points to the original object.

I was thinking we could replace the line
```python
form = ModelForm(instance=obj, initial=self.get_revision_form_data(request, obj, version))
```
with a forloop that modifies obj to with the version data. Do you think this would work, or would it break anything else? Thanks

**Comment by jmurty** [comment]
FWIW I have tackled a similar issue by:
* adding custom Javascript to the admin page to disable form fields on the client-side
* using the "strict" restore feature in PR #424 to enforce the read-only nature of history pages on the server-side, so user supplied form data is ignored altogether on revert

Not very elegant, but it does the job.

**Comment by etianen** [comment]
Should be fixed in aa858f8ff53b50ea10be8b2ccca96ca993b95545

Try the latest master.

**Comment by dgaus** [comment]
Large commit! looks nice. I wanted to test this, however after uninstalling and installing master (doing pip install https://github.com/etianen/django-reversion/archive/master.zip) I get 'ImportError: No module named reversion' when trying to run a django shell. Am I missing something obvious or is this a bug?

**Comment by etianen** [comment]
Try pip install git+https://github.com/etianen/django-reversion.git

**Comment by etianen** [comment]
And yes, it’s a fundamental change to how admin rollback is achieved. Before, it was a load of little hacks to smash the revision data into the admin form. Now, it uses a database savepoint to temporarily restore the DB to a point in time, render the page, then roll back the save point.

It’s a bit of an abuse of save points, but it seems to work in all DB engines. There are some caveats, such as it breaking MyISAM tables in MySQL (but that’s no longer the default table format in recent versions), and breaking for a transaction isolation of read uncommitted (which isn’t the default isolation level in any database anywhere). The benefit is that a huge number of fragile hacks are gone, and that a load of small things that didn’t work now work. :)

**Comment by dgaus** [comment]
I think given the hackyness of the previous implementation this is a really good change. Cannot test it unfortunately! 

```
$ pip uninstall django-reversion
Uninstalling django-reversion:
  /home/vagrant/venv/lib/python2.7/site-packages/django_reversion-1.8.7-py2.7.egg-info
Proceed (y/n)? y
  Successfully uninstalled django-reversion
$ pip install --upgrade git+https://github.com/etianen/django-reversion.git
Downloading/unpacking git+https://github.com/etianen/django-reversion.git
  Cloning https://github.com/etianen/django-reversion.git to /tmp/pip-Gb1_q_-build
  Running setup.py (path:/tmp/pip-Gb1_q_-build/setup.py) egg_info for package from git+https://github.com/etianen/django-reversion.git

    no previously-included directories found matching 'docs/_build'
Requirement already up-to-date: django>=1.7 in /home/vagrant/venv/lib/python2.7/site-packages (from django-reversion==1.8.7)
Installing collected packages: django-reversion
  Running setup.py install for django-reversion

    no previously-included directories found matching 'docs/_build'
Successfully installed django-reversion
Cleaning up...
$ python manage.py shell_plus
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named reversion
$ pip uninstall django-reversion
Uninstalling django-reversion:
  /home/vagrant/venv/lib/python2.7/site-packages/django_reversion-1.8.7-py2.7.egg-info
Proceed (y/n)? y
  Successfully uninstalled django-reversion
$ pip install django-reversion
Downloading/unpacking django-reversion
  Downloading django-reversion-1.8.7.tar.gz (58kB): 58kB downloaded
  Running setup.py (path:/home/vagrant/venv/build/django-reversion/setup.py) egg_info for package django-reversion

    no previously-included directories found matching 'docs/_build'
Installing collected packages: django-reversion
  Running setup.py install for django-reversion

    no previously-included directories found matching 'docs/_build'
Successfully installed django-reversion
Cleaning up...
$ python manage.py shell_plus
Python 2.7.3 (default, Feb 27 2014, 19:58:35)
Type "copyright", "credits" or "license" for more information.

IPython 2.3.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]:
```

**Comment by etianen** [comment]
Hmm, odd and annoying.

Try just cloning the git repo somewhere and symlinking the src/reversion directory into venv/lib/python2.7/site-packages

**Comment by bourivouh** [comment]
Hi! 
I just wonder why you decided to make hack with transaction and revert instead of simple returning object_version.object in get_object function? Is there any pitfalls which I don't realize yet?
I know that it was quite long time ago, but hope you have really good memory :)

**Comment by etianen** [comment]
object_version.object would return incorrect data for foreign keys, since the foreign keys would be loaded from the live db.

It was a choice of a million buggy hacks on the admin interface, or a single self-contained hack with database transactions. No brainer, really.

**Comment by bourivouh** [comment]
Thanks for clarification!
Admittedly, I didn't check fk fields before asking. I just saw one problem with auto_now=True field. It's update after any restore, so you can't see historical value. But this is the lesser of two evils, anyway.

**Comment by etianen** [comment]
auto_now and auto_now_add are pretty hard to control with their behaviour.
I like to use default=timezone.now and similar techniques to bring a bit
more control back to the application developer.
