### ISSUE TITLE
Some non-transactional changed tables couldn't be rolled back

### ISSUE THREAD

**Issue by joshkurz** [etianen/django-reversion#362]
I am getting an error when trying to save an object from the admin panel.

This is where the error is coming from. 

/usr/local/lib/python2.7/dist-packages/reversion/admin.py in log_change
            db = self.revision_context_manager.get_db(), ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/reversion/revisions.py in save_revision
                        cls._default_manager.db_manager(db).create(revision=revision, **kwargs) ...
▶ Local vars

any help would be appreciated. Thanks

**Comment by jpatel3** [comment]
I believe you using mysql and it happens when you have mix of MYISAM and innodb tables. and you have join between those tables which both are on different Engine. You will need to resolve that, it should work fine.
