### ISSUE TITLE
How to prevent history saving if nothing is changed?

### ISSUE THREAD

**Issue by yn-coder** [etianen/django-reversion#378]
How to prevent history saving if nothing is changed?

For example, user do Edit and Save in form, without changing anything. Can reversion skip this unusual save-signal?

**Comment by etianen** [comment]
To do that, it would need to compare to the last version of the object, which introduces a race condition.

That being said, this feature does exist. Call reversion.set_ignore_duplicates(True) at some point in your revision, and it’ll do just that.

TBH, I regret adding that feature, but it’s there if you want it!

**Comment by yn-coder** [comment]
Why you regret?

**Comment by etianen** [comment]
It’s a feature that has a race condition and adds overhead to the revision save process.

I’d much rather save revisions all the time, a de-duplicate on read.

**Comment by yn-coder** [comment]
But if you have an ignore_duplicates flag, you'll skip this check by defalut?

**Comment by etianen** [comment]
The default is ignore_duplicates=False, which skips the check. Setting the flag enables the check.

So the feature doesn’t do any harm if disabled, but I dislike having features that aren’t 100% safe and performant.

**Comment by thedrow** [comment]
It's possible to lock the row in the database if you want to avoid a race condition.
I don't expect django-reversion to do that any time soon since Django doesn't provide many locking constructs.
It is possible to use select_for_update to lock the row on newer versions of Django though. Could that be used instead?

**Comment by etianen** [comment]
I think the race condition could be avoided, true, but at the expense of making that portion of the code essentially single-threaded. Still not great.

I’m much more comfortable with fast version writes and background garbage collection. It’s how git works. It’s how couchdb works.

**Comment by lorinkoz** [comment]
Can we have at least an official management command to remove duplicates?

**Comment by halfnibble** [comment]
This race condition you speak of. In the case where the non-desired outcome wins, what is the worse possible scenario? Is it:
A) You get a duplicate after all, or 
B) You don't get a unique revision logged by mistake?
Thanks. (I think A is acceptable, whereas B would not be).

**Comment by etianen** [comment]
I believe that it results in a duplicate revision.

**Comment by tdruez** [comment]
See alos #442
