### ISSUE TITLE
Versions passed through by reversion.post_revision_commit have no primary key

### ISSUE THREAD

**Issue by joelarson** [etianen/django-reversion#380]
Odd behavior:

```py
# Setup this signal, try saving a tracked object, and check your test server output
@receiver(reversion.post_revision_commit)
def on_revision_commit(revision, versions, instances, **kwargs):
    print(versions[0].pk)
    # pk = None

    # then if I save the object to give it a pk, it saves a duplicate in the db
    versions[0].save()  # go check the db, you'll see the duplicate
    print(versions[0].pk)

```

**Comment by etianen** [comment]
The versions sent in that signal have yet to be saved to the database. They’re saved in bulk after the signal has been sent.

**Comment by joelarson** [comment]
Is this the desired behavior? [The documentation](https://django-reversion.readthedocs.org/en/latest/signals.html#reversion-post-revision-commit) suggests that the versions are already saved when they are handed to you in the signal, which makes sense to me:

> ### reversion.post_revision_commit
> This signal is triggered just after a revision is saved to the database. It receives the following keyword arguments:

> * **instances** - A list of the model instances in the revision.
> * **revision** - The saved Revision model.
> * **versions** - The **saved** Version models in the revision.

And if there is a good reason for it, could we consider adding another signal that fires after the revision and all its versions have been saved? I obviously have a use case for it?

**Comment by etianen** [comment]
Huh, that documentation is wrong. Damn.

At the moment, the revisions don’t have a pk because they’re being bulk-saved by Django. Even after the bulk-save, they don’t get assigned a PK, since that’s a downside of the bulk-save method.

Theoretically, the bulk save could be removed and multiple calls to save() used. This would have performance implications, particularly for bulk data loading during createinitialrevisions. I wonder how serious those implications would be?

**Comment by joelarson** [comment]
What do you think about the following approach? It should only take two queries if I understand things correctly:

```py
# reversion/revisions.py:490

...

# Save version models.
for version in new_versions:
    version.revision = revision
# query #1: Bulk save (does not return versions with primary keys)
Version.objects.using(db).bulk_create(new_versions)
# query #2: replace new_versions with filtered set from db
# which will include the primary keys
new_versions = Version.objects.filter(revision=revision)

...

# Send the post_revision_commit signal.
post_revision_commit.send(self,
    instances = ordered_objects,
    revision = revision,
    versions = new_versions,
)

...
```

Although I would assume that most of the time a revision will only have one version if people are just using it with the out of the box admin integration. So if you really wanted to optimize, you could check the length of the versions list and if it's less than a certain threshold, save them individually, otherwise bulk save them then retrieve them.

**Comment by etianen** [comment]
It’s an interesting approach, but TBH, I think saving the Version objects with normal ORM save() is fine here. The real place where performance is an issue is createinitialrevisions, which would only be creating one Version per Revision anyway, so the bulk_save optimisation wouldn’t help at all!

If you hit me with a pull request that replaces bulk_save with just saving the Version instances on the spot, I’ll happily pull.

**Comment by dehnert** [comment]
> At the moment, the revisions don’t have a pk because they’re being bulk-saved by Django. Even after the bulk-save, they don’t get assigned a PK, since that’s a downside of the bulk-save method.

FWIW, this is no longer always the case. [Django 1.10](https://docs.djangoproject.com/en/1.10/ref/models/querysets/#bulk-create) (release about a year and a half after this) added support on some databases (PostgreSQL at the time). SQLite was added in [Django 4.0](https://docs.djangoproject.com/en/4.1/ref/models/querysets/#bulk-create), and MariaDB was added sometime in the middle.

(I found this issue while trying to figure out why tons of queries were being used despite the [changelog](https://django-reversion.readthedocs.io/en/stable/changelog.html#id50) claiming reversion uses `bulk_create`.)
