### ISSUE TITLE
RemovedInDjango19Warning: django.contrib.admin.util

### ISSUE THREAD

**Issue by khakulov** [etianen/django-reversion#384]
I tried to run my project with Django 1.8. I got the following warning:

    RemovedInDjango19Warning: The django.contrib.admin.util module has been renamed.
    Use django.contrib.admin.utils instead.
    "Use django.contrib.admin.utils instead.", RemovedInDjango19Warning)

admin.py L:12
```python
from django.contrib.admin.util import unquote, quote
```

The other question for myself was, why the  ```admin.py ``` was imported in my project, where i never use django admin interface/modules. Why we need to import  ```VersionAdmin ``` class in ```__init__.py```???

**Comment by etianen** [comment]
It was imported in __init__.py as a convenience, really, but I see your point here, that it’s importing a whole load of code for no reason in some cases.

I’ll take a pull request that updates the docs and reversion code to remove the reversion.VersionAdmin link. I’m inclined to ignore the deprecation warning for now, however. The time to change the reference is when Django 1.9 hits alpha.

**Comment by pquentin** [comment]
The deprecation warning is definitely annoying. Even if it's one release away, I still try to fix the issue. With many Django apps, there is no easy way to know where the warning comes from (I had to modify Django and dev-install it to print the apps it was trying to import).

Is it possible to first fix the warning and refactor later? Thanks!

**Comment by pquentin** [comment]
Thank you etianen! Sorry if I was rude, that was not my intention.

**Comment by etianen** [comment]
Rude? Nope, not at all! Enjoy the release! :D
