### ISSUE TITLE
"Registering models with django-reversion" method doesn't create revisions

### ISSUE THREAD

**Issue by gdonald** [etianen/django-reversion#385]
Concerning https://github.com/etianen/django-reversion/issues/383

Why did you close the ticked and then proceed with asking me to test your fix?

I tried your recommendation to not use RevisionMiddleware.  I switched my app over to the "Registering models with django-reversion" method but now I do not get revisions any longer.  No error messages, just silently fails to do what it used to do.

**Comment by etianen** [comment]
Most people never get back to me about whether a fix actually works! In any case, the solution to this one seemed pretty obvious, and the unit tests aren't complaining.

In the absence of the RevisionMiddleware, you have to use the create_revision() decorator/contextmanager in your views.

http://django-reversion.readthedocs.org/en/latest/api.html#reversion-create-revision-decorator
