### ISSUE TITLE
problem with excluded auto field

### ISSUE THREAD

**Issue by szelga** [etianen/django-reversion#387]
here's my model:

```python
class WikiPage(models.Model):
    title = models.CharField(verbose_name='title', max_length=128,\
        unique=True, db_index=True)
    content = models.TextField(verbose_name='content')
    
    is_deleted = models.BooleanField(default=False, blank=True)
    
    time_created = models.DateTimeField(auto_now_add=True)
    time_modified = models.DateTimeField(auto_now=True)
    
    attachments = models.ManyToManyField(Attachment, related_name='wiki_pages', blank=True, null=True)

    def __unicode__(self):
        return u'{0}'.format(self.title)
        
    class Meta:
        permissions = (
            ('view_wikipage', 'Can view wiki pages'),
            ('revert_wikipage', 'Can revert wiki pages'),
        )
        ordering = ['-time_modified',]

reversion.register(WikiPage, exclude=['attachments', 'time_created', 'time_modified'])
```

when i perform `version.revert()` i get database error: `IntegrityError: NOT NULL constraint failed: wiki_wikipage.time_created`. how can i work around this?

**Comment by szelga** [comment]
OK, i understand that excluding stuff is a bad idea anyway, because those fields become null instead of getting untouched (as i thought it would be). i think it's worth mentioning in the docs (along with more detailed explanation of difference between `version.revert()` and `version.revision.revert()`).

**Comment by szelga** [comment]
Django==1.6.8, django-reversion==1.8.4, if it's important.

**Comment by etianen** [comment]
Sorry, I’m confused about what the bug is here.
