### ISSUE TITLE
Readonly revision_view for DeserializationError and IntegrityError

### ISSUE THREAD

**Issue by kevinmarsh** [etianen/django-reversion#389]
If I make a migration changing a field from a `CharField` to a `ForeignKey` and then go to look at a previous version where that field was saved as a character string, I get a `DeserializationError` error which means that I can't even see the representation of the object from that revision.

To overcome this I've created a kind of read only view that just displays the `serialized_data` in a simple JSON tree if a `DeserializationError` or `IntegrityError` is raised in the `revision_view`. A user can't revert to this revision but at least they can see what the data was at that revision.

I'm not sure if this something that would be useful to the project or if it's the right approach (or if there is something already built in that I'm missing). I'm using [this branch](https://github.com/etianen/django-reversion/compare/master...kevinmarsh:revision_readonly) for a project at work but it'd need more work/tests/thought before it got integrated into `master`.

For example before:
![deserializationerror_before](https://cloud.githubusercontent.com/assets/1423728/6893709/ef091e1a-d6c6-11e4-8a82-0e34d91f49fa.png)

and after:
![deserializationerror_after](https://cloud.githubusercontent.com/assets/1423728/6893712/f4f42af4-d6c6-11e4-9cdc-3bf10978e3e6.png)

**Comment by LegoStormtroopr** [comment]
This is a really interesting edge case. I'll fork from your repo and have a look.

**Comment by etianen** [comment]
Interesting idea!

I’d implement this as a standalone subclass of VersionAdmin. You can wrap render_revision_form with your fallback view, which would allow users to apply the fallback on a per-model basis rather than relying on a global setting.

I don’t think that this belongs in the django-reversion core, but it would make a great add-on app.

**Comment by kevinmarsh** [comment]
Ok thanks for a the feedback I'll just keep it as a seperate fork for now then. Thanks for your work on django-reversion by the way.
