### ISSUE TITLE
Not adding a custom revision at /admin

### ISSUE THREAD

**Issue by mauricioabreu** [etianen/django-reversion#390]
Well, my problem is that everytime I try to create a revision at /admin it does not get created.

Here is my custom revision model:

```python
class VersionAccount(models.Model):
    revision = models.OneToOneField(Revision)
    account_id = models.PositiveIntegerField()
    user_id = models.PositiveIntegerField(null=True, blank=True)
    user_email = models.CharField(max_length=100, null=True, blank=True)
    user_fullname = models.CharField(max_length=100, null=True, blank=True)
    type = models.CharField(max_length=5, choices=(
        ('+', _('created')),
        ('~', _('changed')),
        ('-', _('deleted')),))

    def save(self, *args, **kwargs):
        if self.user_id:
            user = get_user_model().objects.get(id=self.user_id)
            self.user_email = user.email
            self.user_fullname = user.get_full_name()
        super(VersionAccount, self).save(*args, **kwargs)
```

Here is my admin code:

```python
class ConfigurationAdmin(admin.ModelAdmin):
    readonly_fields = (some_fields_here)
    list_display = [some_fields_here]
    search_fields = [some_fields_here]
    ordering = [some_fields_here]
    actions = [save_multiple]
    form = ConfigurationAdminForm

    @reversion.create_revision()
    def change_view(self, request, object_id, form_url='', extra_context=None):
        configuration = Configuration.objects.get(id=object_id)
        reversion.set_user(request.user)
        reversion.add_meta(VersionAccount, account_id=configuration.account.id, type='~')
        return super(ConfigurationAdmin, self).change_view(request, object_id, form_url, extra_context)

    @reversion.create_revision()
    def delete_view(self, request, object_id, extra_context=None):
        configuration = Configuration.objects.get(id=object_id)
        reversion.set_user(request.user)
        reversion.add_meta(VersionAccount, account_id=configuration.account.id, type='-')
        return super(ConfigurationAdmin, self).delete_view(request, object_id, extra_context)

    def has_add_permission(self, request):
        """
        Remove add action from admin interface.
        """
        return False
```

Some things to note:

* change_view is saving the revision ok.
* delete_view is not saving the revision ok and it is being execute (I tested using pdb).

Versions:
Django 1.6.11
django-reversion 1.8.5
Python 2.6

What am I missing? Thanks for this app!

**Comment by etianen** [comment]
Model deletions are not captured in a revision. Only creations and updates. Reversion knows a model is deleted because it’s present in the revision database, but not in the live database.

When a model is deleted, it can be recovered from the “recover deleted objects” section of the admin.

**Comment by mauricioabreu** [comment]
So there is no way to catch up a delete using django reversion? Or it does not make any sense?

My application has some important objects saved into the database and I would like to keep track when  a specific object was deleted and who did it.

**Comment by etianen** [comment]
django-reversion is primarily a rollback and recovery, although it’s somewhat useful as an audit log. There was a brief period when it recorded deletes as new revisions, but the result was inconsistency and a dramatic increase in complexity, so the feature was removed.

More discussion around this issue:
- https://github.com/etianen/django-reversion/issues/364
- https://github.com/etianen/django-reversion/issues/164

**Comment by mauricioabreu** [comment]
Nice! Thanks for your answer.

**Comment by mauricioabreu** [comment]
I think I am going to use django-reversion for rollback update/insert and django-simple-history as an audit log tool.

**Comment by etianen** [comment]
The right tool for the right job. Smashing!

Myself, I'd be tempted to re-use the built-in django admin log model. That way it would integrate nicely with the existing admin tools.

**Comment by mauricioabreu** [comment]
Yeah, good answer! I am going to read Django admin code. 

Thanks for your support!
