### ISSUE TITLE
Running django-reversion in Django 1.8 gets me this warning

### ISSUE THREAD

**Issue by misingnoglic** [etianen/django-reversion#396]
Not sure if this is my fault but I figured I'd share this hear anyway, I get this error when I run runserver or shell or any other manage.py command

/usr/local/lib/python2.7/site-packages/reversion/admin.py:16: RemovedInDjango19Warning: django.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9. Its contents have been moved to the fields, forms, and admin submodules of django.contrib.contenttypes.
  from django.contrib.contenttypes.generic import GenericInlineModelAdmin, GenericRelation

**Comment by tlevine** [comment]
It happens that this has already been addressed in commit 33a14819df319cdd33a3982ca4b7adcfc958a737, but that won't make the warning go away until Django 1.9 arrives.

I haven't found an elegant way to turn off the RemovedInDjango19Warning warnings, but you could run your project like so to hide all warnings.

    python -W ignore ./manage.py

**Comment by etianen** [comment]
Try updating to the latest master version from GitHub. I think this is now solved, as of 8621bbb351adf633e3be856a41f7cd6f0e656428

**Comment by carltongibson** [comment]
@etianen I'm wondering if you'll put these changes on PyPI as is, or if a new release will wait a while? (Not really fussed but I'd like to avoid pulling in `master` if a new release is coming immediately) Thanks!

**Comment by etianen** [comment]
Would you mind trying the master branch to confirm that your issue is fixed? If it is, I can push out a release today.

**Comment by carltongibson** [comment]
No worries. I'll pull it in now. Will report back...

**Comment by carltongibson** [comment]
Looks good.

**Comment by etianen** [comment]
1.8.7 has landed!

**Comment by carltongibson** [comment]
👍
