### ISSUE TITLE
doc issue: installation requires adding to settings.py

### ISSUE THREAD

**Issue by adriannye** [etianen/django-reversion#399]
Installation instructions should mention that you need to add "reversion" to INSTALLED_APPS, otherwise the createinitialrevisions management command will not be found.

**Comment by adriannye** [comment]
Installation instructions also don't mention that it requires running a migration to create a table.
Ideally the instructions would include both South and django migration steps.

**Comment by etianen** [comment]
I think that they do include this step.

http://django-reversion.readthedocs.org/en/latest/index.html#getting-started-with-django-reversion

**Comment by adriannye** [comment]
OK, agreed but I would say Getting Started should be listed in the left
navigation.
I got to a different page of the doc from google, and in that case there is
no way to know the Getting Started page even exists: the only way to get to
it is to click Docs in the breadcrumbs.

**Comment by etianen** [comment]
Agreed, although I’m not sure how to make the index page also appear in the left hand nav. It already appears above the search box, by the home icon.

**Comment by etianen** [comment]
I've added a link from the installation methods page to the getting started guide.
