### ISSUE TITLE
ForeignKey follow does not work

### ISSUE THREAD

**Issue by thongly** [etianen/django-reversion#400]
As per the docs section, http://django-reversion.readthedocs.org/en/latest/api.html#following-foreign-key-relationships, I am trying to get a simple `ForeignKey` to be saved with revisions. However, after trying for hours, I'm unable to get this rather basic functionality to work.

-I am currently using **Django 1.6** and **django-reversion 1.8.5**.
-`reversion.middleware.RevisionMiddleware` is included in `MIDDLEWARE_CLASSSES`
-I am expecting that **articles** with a FK to a given **section** will also be included in the `serialized_data` of that section's version - is this the expected behavior?

**models.py**

```
rom django.db import models
import reversion


class Article(models.Model):
    name = models.CharField(max_length=50)
    content = models.TextField()
    section = models.ForeignKey('article.Section', blank=True, null=True)

    class Meta:
        verbose_name = "Article"
        verbose_name_plural = "Articles"

    def __str__(self):
        return '%s' % self.name

if not reversion.is_registered(Article):
    reversion.register(Article)


class Section(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        verbose_name = "Section"
        verbose_name_plural = "Sections"

    def __str__(self):
        return '%s' % self.name

    @reversion.create_revision()
    def save(self, *args, **kwargs):
        super(Section, self).save(*args, **kwargs)

if not reversion.is_registered(Section):
    reversion.register(Section, follow=["article_set"])
```

**Comment by etianen** [comment]
The serialiazed_data of a Version model contains only a single model. This is because otherwise circular references would lead to infinite JSON!

Instead, look for multiple Version models grouped under the same Revision model.

I’d also update your code to:

reversion.register(Article, follow=[“section”])

Also, if you’re having to use `if not reversion.is_registered`, then you’re running into double-import problems. Avoid using relative paths to import models. Always use absolute paths, everywhere.

**Comment by thongly** [comment]
Thanks!

Does `reversion` currently account for **GenericForeignKey** relationships
on reverts?

**Comment by etianen** [comment]
If the generic foreign key is followed, then a revert should include it.

**Comment by thongly** [comment]
Is it possible to follow it follow the reverse generic relation with reversion pre django 1.7 - https://docs.djangoproject.com/en/1.8/ref/contrib/contenttypes/#django.contrib.contenttypes.fields.GenericRelation.related_query_name?

Would it work if I specified a `property`?

**Comment by etianen** [comment]
Any model attribute that returns a model or a queryset should work.

**Comment by thongly** [comment]
thanks. closing this ticket for now.
