### ISSUE TITLE
Docs Unclear on createinitialrevisions management command

### ISSUE THREAD

**Issue by tyrelsouza** [etianen/django-reversion#403]
I'm adding a new model to be registered with reversion, but we're already using reversion on other models.

The docs say "It should be run after installing django-reversion" but it's unclear if I need to run this management command after I set a new model up and register it with reversion, or if only the first time.

I think the part where I am confused is whether "initial" refers to only being needed to be run when you initially add django-reversion, or if you need to create an "initial" revision for each model.

Currently I have run it after and see some data changes, but I am not 100% sure if it is necessary, would be great if the docs were a bit clearer.

**Comment by etianen** [comment]
Good point. I’ve put a note in the docs.
