### ISSUE TITLE
Problem catching exceptions in the admin.py

### ISSUE THREAD

**Issue by timfenney** [etianen/django-reversion#411]
Hey there,

I am trying to use django-reversion to customize the admin. What I need is some kind of UI to allow me to undelete multiple models at the same time. What I have working now is the following. I have a "MyVersionAdmin" class that inherits from reversion.admin.VersionAdmin, and has it's own implementation of "render_revision_form"--a copy of the method from VersionAdmin, except for the "# Render the form" section. Under "elif recover:" I have the following logic:

```

            try:
                version.revert()
                obj = version.object_version.object
                obj.archived=False
                obj.save()
                messages.info(request, 'Object reverted.')
                return HttpResponseRedirect('..')
            except:
                try:
                    with transaction.atomic:
                        version.revision.revert()
                        for v in version.revision.version_set.all():
                            v.object_version.object.archived = False
                            v.object_version.object.save()
                    messages.warning(
                        request,
                        'Object reverted with other objects from revision.')
                    return HttpResponseRedirect('..')
                except:
                    messages.error(
                        request,
                        'Unable to revert object.')
                    return HttpResponseRedirect('..')
```

When the revert() succeeds, everything works just fine. However, I find that sometimes this method results in an exception being thrown, but control doesn't pass to my "except" blocks... It looks like the exceptions are raised from line 297 in the __call__ method of the RevisionContext class in reversion/revisions.py ("return func(*args, **kwargs))").

I am guessing this is not exactly a bug, but I'm posting it here just in case. I am using django-reversion 1.8.5 and Django 1.6.11.

How do I:
  * intercept the Exceptions, if any, raised in this context (above)? (I.e. so I can report success/failure to the user)
  * find a better way, if any, to do this and obtain the desired result? (undelete a revision_set from the admin)

**Comment by etianen** [comment]
The admin class now has built-in handling of revert errors, displaying an error message to the user and redirecting to the changelist.
