### ISSUE TITLE
Generic View Mixin

### ISSUE THREAD

**Issue by thenewguy** [etianen/django-reversion#416]
It would be handy if there was a mixin for generic views packaged with django-reversion that did this http://django-reversion.readthedocs.org/en/latest/api.html#reversion-create-revision-context-manager automatically

**Comment by thenewguy** [comment]
The following seems to work well enough for generic views and django-rest-framework serializers.
```
import reversion
from django.db import transaction

class ReversionViewMixin(object):
    def dispatch(self, *args, **kwargs):
        with transaction.atomic(), reversion.create_revision():
            return super(ReversionViewMixin, self).dispatch(*args, **kwargs)

class ReversionSerializerMixin(object):
    def create(self, *args, **kwargs):
        with transaction.atomic(), reversion.create_revision():
            return super(ReversionSerializerMixin, self).create(*args, **kwargs)
    
    def update(self, *args, **kwargs):
        with transaction.atomic(), reversion.create_revision():
            return super(ReversionSerializerMixin, self).update(*args, **kwargs)
```

**Comment by thenewguy** [comment]
This actually caused some problems for me.  I.e. for integrity errors you cannot query the database to figure out which field caused the issue without getting a TransactionManagementError.  I guess it is better to leave this to manual management as is

**Comment by thenewguy** [comment]
Well I said that and then discovered that something like following let me handle the IntegrityError while using the mixin:

```
class ReversionViewMixin(object):
    def dispatch(self, *args, **kwargs):
        with transaction.atomic(), reversion.create_revision():
            response = super(ReversionViewMixin, self).dispatch(*args, **kwargs)
            reversion.set_user(self.request.user)
            return response

class FooList(ReversionViewMixin, generics.ListCreateAPIView):
    ...
    
    def perform_create(self, serializer):
        try:
            with transaction.atomic(), reversion.create_revision():
                serializer.save(
                    created_by=self.request.user,
                    modified_by=self.request.user,
                )
        except IntegrityError:
            ...

            try:
                foo = Foo.objects.get(bar=value)
            except Foo.DoesNotExist:
                foo = None
                        
            if foo:
                raise ValidationError("Integrity error: Foo already exists with pk '%s'." % foo.pk)
            
            raise ValidationError("Unexpected Integrity Error Encountered.")
```

Going to reopen.  If I encounter any other issues I will mention them here

**Comment by etianen** [comment]
I wonder if a better approach might be to use a view middleware, thus wrapping all requests in a revision?

**Comment by thenewguy** [comment]
It is my understanding that there is already a [middleware shipped with the project](http://django-reversion.readthedocs.org/en/latest/api.html#revisionmiddleware) but according to the documentation the middleware approach cannot be transitionally secure and recommends wrapping the views and anywhere else a save is called.  Maybe I misunderstood?  I read that notice in the docs and decided not to investigate the middleware any further

**Comment by thenewguy** [comment]
Using a view mixin has another benefit over the middleware in that it doesn't open transactions for each request even when not needed

**Comment by etianen** [comment]
Good point. I think your code snippet here pretty much nailed it:

``` py
import reversion
from django.db import transaction

class ReversionViewMixin(object):
    def dispatch(self, *args, **kwargs):
        with transaction.atomic(), reversion.create_revision():
            return super(ReversionViewMixin, self).dispatch(*args, **kwargs)

class ReversionSerializerMixin(object):
    def create(self, *args, **kwargs):
        with transaction.atomic(), reversion.create_revision():
            return super(ReversionSerializerMixin, self).create(*args, **kwargs)

    def update(self, *args, **kwargs):
        with transaction.atomic(), reversion.create_revision():
            return super(ReversionSerializerMixin, self).update(*args, **kwargs)
```

An open question - perhaps only the post() and put() methods should be wrapped with a revision, since get() shouldn't perform and database updates?

I'd be happy to take a pull request that contained the following:

- A views.py file containing the RevisionViewMixin.
- A serializers.py file containing the RevisionSerializerMixin.
- A views.rst and serializers.rst file containing some basic documentation, linked under index.rst "Futher documentation".

**Comment by brsbilgic** [comment]
I've used this way and it did pretty well. 

```python
class ReversionViewMixin(object):
    def dispatch(self, *args, **kwargs):
        with transaction.atomic(), reversion.create_revision():
            response = super(ReversionViewMixin, self).dispatch(*args, **kwargs)
            if not self.request.user.is_anonymous():
                reversion.set_user(self.request.user)
            return response

class UserApi(ReversionViewMixin, ModelViewSet):
```

The other cool feature would be able to filter or exclude models when using middleware. I'd like to register only couple of models but middleware keep changes for all models, am I right?

**Comment by etianen** [comment]
The middleware only keeps changes for models you register with reversion.

**Comment by niknokseyer** [comment]
Thanks for this one. I'm using @brsbilgic solution as well.
