### ISSUE TITLE
Configure a default VersionAdapter in settings.py

### ISSUE THREAD

**Issue by jrief** [etianen/django-reversion#419]
Currently the default ``VersionAdapter`` is hard-coded in the ``RevisionManager`` as:
```
def register(self, model=None, adapter_cls=VersionAdapter, signals=None, eager_signals=None, **field_overrides):
```

It would be great, if this could be overridden by a special settings variable. Would you accept a PR, adding this feature?

**Comment by etianen** [comment]
I'm not sure that this needs to be a Django setting. You can implement this in code by defining your own register method with a different, and using that.

I general, I think it's best to keep the number of Django settings to an absolute minimum. It makes the behaviour of code more explicit.
