### ISSUE TITLE
Custom meta data requires specific field name

### ISSUE THREAD

**Issue by james8aus** [etianen/django-reversion#420]
Hi Guys,

When using custom meta data i noticed you must use "revision" as the name of the field which is the FK to Revision. Anything else gives you an error. Took me a while to figure it out. Might be worth clarifying in the doco?

http://django-reversion.readthedocs.org/en/latest/api.html#custom-meta-data 

```python
from reversion.models import Revision

class VersionRating(models.Model):
    revision = models.ForeignKey(Revision)  # There must be a relationship with Revision
    rating = models.PositiveIntegerField()
```

I was attempting to use the standard i follow.

```python
from reversion.models import Revision

class VersionRating(models.Model):
    fk_revision = models.ForeignKey(Revision)  # There must be a relationship with Revision
    rating = models.PositiveIntegerField()
```

**Comment by etianen** [comment]
Fair point. The docs have been updated.
