### ISSUE TITLE
User making a change not shown in history when using RevisionMiddleware

### ISSUE THREAD

**Issue by therocode** [etianen/django-reversion#422]
Hello!

I have installed django-reversion for my django 1.8 project and I want to track changes to my models regardless of how they were changed (admin panel, other forms etc) and I saw that you can use RevisionMiddleware for this. I activated this and reversions are created successfully. However when I change models outside of the admin panel, the name of the user does not get tracked on the change, instead it just shows "----" as the username as seen here: http://puu.sh/iILyz/3a58b67650.png

Is this intended behaviour? Is there any way I can get the user name added to the revision when using the middleware for automatic revisioning on all changes?

**Comment by etianen** [comment]
You need to access the request.user somewhere in your view or template for it to be added to the revision.

It’s an optimisation to prevent spamming of the DB on every request. Django does something similar, somewhere, (but I forget where)>

**Comment by therocode** [comment]
Oh that worked indeed. Thanks for that!
