### ISSUE TITLE
Any way to delete all versions/revisions of an object when you want it to completely disappear?

### ISSUE THREAD

**Issue by brendangree** [etianen/django-reversion#426]
Django-reversion works great exactly as expected.  I recently came across the use case where I want to delete a reversioned object and all of it's associated revisions and versions.  Is there a straightforward way to do this?

Note: Using reversion 1.8.6 with django 1.8.1

**Comment by etianen** [comment]
This should probably work:

Revision.objects.filter(version__in=reversion.get_for_object(your_model)).delete()
