### ISSUE TITLE
@reversion.register in abstract models

### ISSUE THREAD

**Issue by lorinkoz** [etianen/django-reversion#428]
Is there a way to make it work as if every inheriting model was decorated. Problem arose when I tried to create some sort of  html_diff for all my version controlled models. My approach was to make an abstract model with the intended functionality, decorate it with `reversion.register`, and then just inherit that model every time I wanted versioning functionality. But it's not working on inheriting models. (using Django 1.8)

**Comment by etianen** [comment]
I’m afraid not. You’ll need to decorate each inheriting model separately. Auto-registration is a bit dangerous, as it would lead to models being registered without the user’s intention. Explicit is better than implicit.

**Comment by lorinkoz** [comment]
Fair enough. I'll go the wrapper decorator way.
