### ISSUE TITLE
Deleted objects not appearing on "Recover deleted models" page

### ISSUE THREAD

**Issue by suvansh** [etianen/django-reversion#429]
I have implemented django-reversion-compare, and have several models that follow this pattern:

    from reversion_compare.admin import CompareVersionAdmin
    from django.contrib import admin

    class Model(models.Model):
        # some code

    class ModelAdmin(CompareVersionAdmin):
        ignore_duplicate_revisions = True

    admin.site.register(Model, ModelAdmin)

If I alter a model object from the admin view, the compare feature and the version history both work perfectly. However, if I delete one or more model objects, I am unable to recover them. The "Recover deleted models" button in the admin view leads to a page with a "There are no deleted objects to recover" message.

Did the implementation of django-reversion-compare perhaps interfere with this ability of django-reversion? Any help is appreciated.

Thanks in advance.

**Comment by etianen** [comment]
First thing to check - use the standard version admin class and see if it works.

**Comment by suvansh** [comment]
I changed CompareVersionAdmin to reversion.VersionAdmin and found the same behavior (deleted models not appearing in "recover deleted" view. However, the version history still works fine (without the compare feature, of course).

**Comment by suvansh** [comment]
Figured it out. Recovering deleted models works only for models created from the admin page itself. Thanks!

**Comment by etianen** [comment]
Well, more precisely, it only works for model instances which have had at least on revision created with them. You can create revisions by saving the model in the admin, or using the low-level API to create a version. For historical data, the createinitialrevisions management command will create an initial revision for all registered models.
