### ISSUE TITLE
Recover option shown for users that are not allowed to create new content

### ISSUE THREAD

**Issue by int-ua** [etianen/django-reversion#433]
I'm making a moderation setup with Django and I don't want the moderators group being able to create content, just change the existing instances (edit non-readonly-for-them fields).
So I've added just the 'change' permission for them. But they still can see the recover button and even allowed to the recovery page. Good (?) thing it just breaks (with IntegrityError exception) because some readonly and simultaneously mandatory fields end up being empty.

Looks like the Recover button should only be shown for users with the 'create' permission, isn't it?

**Comment by etianen** [comment]
Try the latest master. I’ve just pushed a change that requires add AND change permission for the recover views. The revert views just need the change permission.

**Comment by int-ua** [comment]
Oh, I've found the problem: now it's not working for the superuser.

**Comment by etianen** [comment]
What's not working for the superuser?

**Comment by int-ua** [comment]
The Recover button is shown but it points to the same admin page (the one with the list, what's the term?)

**Comment by int-ua** [comment]
Actually, all three users see the button and in all cases it points to nowhere (the same page)

**Comment by etianen** [comment]
That's really odd. The URL is correct in my tests, and the button is hidden for users without permissions.

I'm not sure what's going wrong for you.

**Comment by etianen** [comment]
Closed, as this works for me.
