### ISSUE TITLE
Python 3.4.0 and postgres issues

### ISSUE THREAD

**Issue by dmr** [etianen/django-reversion#441]
Hi,

we use django-reversion in production and it works nicely but if we try to rebuild our database we get this error:

```

operator does not exist: integer = text
LINE 1: ... OUTER JOIN "reversion_version" ON ( "io_io"."id" = "reversi...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
```

Has anyone experienced something similar?
We use postgres 9.4.

Thanks,
Daniel

**Comment by etianen** [comment]
It looks like reversion is trying to join the pk of your model to the
object_id of reversion using an incorrect type. It supports integer and
char/text primary keys. It's best to use integer primary keys with
reversion, as its substantially faster.

What field type are you using for the PK of your model?

**Comment by dmr** [comment]
I think we are just using the default id/ok field django uses for every model, but I'll check.
Thank you for the quick reply!

**Comment by etianen** [comment]
Can I have the full traceback to your exception?

**Comment by dmr** [comment]
Oh, I completely forgot to answer. The issue was resolved shortly after that, thanks for cleaning up closed issues :)
