### ISSUE TITLE
VersionAdmin.ignore_duplicate_revisions regression

### ISSUE THREAD

**Issue by tdruez** [etianen/django-reversion#442]
http://django-reversion.readthedocs.org/en/latest/admin.html#admin-customizations

Since 1.9.x the ignore_duplicate_revisions does not work as advertised anymore.

The value of the variable is not given to the revision manager anymore, it was removed in 
https://github.com/etianen/django-reversion/commit/001b0f5d02bec479ba258d4813754c61adb277da#diff-d35a2fc6cde4f9f34719a75b9dd3ef6fL162 
and 
https://github.com/etianen/django-reversion/commit/001b0f5d02bec479ba258d4813754c61adb277da#diff-d35a2fc6cde4f9f34719a75b9dd3ef6fL173

**Comment by etianen** [comment]
Crappski! I shall fix this tomorrow and issue a new release.

**Comment by tdruez** [comment]
Sounds good, thanks! :)

**Comment by etianen** [comment]
Could you confirm that the master branch fixes your issue? I'll then push out a new release.

**Comment by tdruez** [comment]
Issue is not fixed in Master branch (1.9.3).
On top of a proper fix, we should also add a test to avoid such regression in the future.

**Comment by etianen** [comment]
I'm happy to take a pull request. :P

Rushing things at the moment, because I've got to leave for holiday in 30
mins...

**Comment by tdruez** [comment]
Hi @etianen,
Any progress on this one?
Thanks :)

**Comment by etianen** [comment]
So, it turns out that, at some point, the ignore_duplicate_revisions functionality got broken in a non-deterministic way. :/

The way that duplicate revisions are detected is by comparing the new serialized representation of the object, to see if it's different from the previous serialized representation of the object. It looks like, at some point, the Django JSON encoder stopped ordering keys, so repeated serializations of the same object yield different results!

Which leads us to the difficult question: how do we compare two sets of Django models for deep equality?

**Comment by tdruez** [comment]
What about comparing on de-serialized data as dict?

**Comment by etianen** [comment]
Yes, I think that could work. You'd need to compare the field_dict of the
Version models.

I'd take a pull request for this, but can't dive into the implementation
myself for the next few weeks.

**Comment by carlmjohnson** [comment]
Counter-proposal: On save run `json.dumps(json.loads(data), sort_keys=True)`.

**Comment by etianen** [comment]
Not all version data is stored as JSON, so this won't work, sadly.

**Comment by carlmjohnson** [comment]
True, but maybe we could add a `get_canonical_form` method that normalizes JSON and lets the other formats keep doing whatever they're doing.

**Comment by etianen** [comment]
What's wrong with just comparing the two version dicts? So long as they
consist of simple python types, it should work.

**Comment by carlmjohnson** [comment]
Yes, I suppose that's true. Since we aren't testing for what the differences are, it should be reasonably fast.

**Comment by tdruez** [comment]
So after looking deeper into my problem, I realized that the issue is not about the comparison logic of `save_revision()`, but rather about the `ignore_duplicates` value passed to `save_revision()`.

`ignore_duplicates` in `save_revision()` is always `False`, even if `ignore_duplicate_revisions = True` is set on the ModelAdmin.

It actually comes back to my original comment from https://github.com/etianen/django-reversion/issues/442#issue-99490015
> The value of the variable is not given to the revision manager anymore

At https://github.com/etianen/django-reversion/blob/master/src/reversion/revisions.py#L188
`_stack` contains 2 RevisionContextStackFrame objects, the first one has `ignore_duplicates=False`,
the second one `ignore_duplicates=True`.

The second one (proper value) is poped and when we reach https://github.com/etianen/django-reversion/blob/master/src/reversion/revisions.py#L206 ,
`stack_frame.ignore_duplicates` value is `False`.

@etianen let me know what you think, I'm not sure why we end up with ignore_duplicates as False in the save logic. This is a blocker for me to upgrade to reversion 1.9.x, that's required to upgrade Django to 1.9.x as well, as reversion 1.8.x is not compatible.
Thanks.

**Comment by etianen** [comment]
I'm not sure how you're getting that behaviour. I just set
ignore_duplicate_revisions to True in the admin of one of my sites, then
added print(ignore_duplicates) at the top of RevisionManager.save_revision.
It was coming through as True just fine.

Have you customised the admin in any way?

**Comment by tdruez** [comment]
Same issue on a clean admin, with nothing but ignore_duplicate_revisions:
```
@admin.register(Test)
class TestAdmin(VersionAdmin):
    ignore_duplicate_revisions = True
```

Note that this works fine on reversion 1.8.7

**Comment by etianen** [comment]
Sorry, but I can't reproduce it.

Give me a minimal test project that shows the issue, and I'll investigate
further.
