### ISSUE TITLE
Using follow with VersinAdmin

### ISSUE THREAD

**Issue by RamezIssac** [etianen/django-reversion#444]
First, Thank you for this wonderful piece.
Second, as i understand, we can not set `follow` when using `VersionAdmin`, we have to use the `reversion.register` method.
Am i right ? If i am then we should be able to do so as an enhancement

**Comment by etianen** [comment]
That is correct. Currently, setting follow required using
reversion.register().

**Comment by RamezIssac** [comment]
Well, after inspecting a little bit, in fact the VersionAdmin perform an introspect to follow the admin inlines.
The case is that the parent and the child models are proxies. and the `VersionAdmin._introspect_inline_admin` return the base inline model not the proxy.

How about to add a `VersionAdmin` attribute called `reversion_follow_append' , to be appended to the introspected fields ?

**Comment by etianen** [comment]
I'm reluctant to add additional functionality, since this can all be
supported by a manual call to reversion.register().

Is much gained by adding this admin shortcut?

**Comment by RamezIssac** [comment]
Dear @etianen , 
The reason i wanted to add this is because i wanted to register inlines (which 'seems" unregistered) 
BUT actually the reversion.register works smartly with the inlines and do auto detect and follow them.
The main issue i was facing i added it here #465 .

"Recorded changes for proxy models within inlines are not visible on the history view"
