### ISSUE TITLE
How to delete old reversion in v.1.7

### ISSUE THREAD

**Issue by AlanAlbuquerque** [etianen/django-reversion#446]
Hi, sorry any mistake, this was translated by google. 
I'm entered into a project that already possess the django-reversion reversion but the tables are too big and I need to lower these tables, in the documentation I found what I wanted, the command: 

```django-admin.py deleterevisions --keep = 10```

But django-admin.py not find the command and returns:
```
Unknown command: 'deleterevisions'
Type 'django-admin.py help' for usage.
```

How can I clean the old data?

**Comment by etianen** [comment]
If you can't upgrade to the latest reversion, then just import Revision and
Version from reversion.models, and use the standard Django ORM to filter
and delete old revisions.

**Comment by AlanAlbuquerque** [comment]
Hi, thanks for your reply ... I imagined it, but I thought I had another way, thanks =)

**Comment by AlanAlbuquerque** [comment]
How you indicate exclude items Version of keeping up the last 3 months? Has no date field in Version table.

**Comment by etianen** [comment]
The date field is in the Revision table.

Version.objects.filter(revision__date_created)
