### ISSUE TITLE
RevisionManagementError at password change in custom user model

### ISSUE THREAD

**Issue by lucheol** [etianen/django-reversion#448]
Hi!

I'm using custom user model (AbstractBaseUser).

Reversion is working on admin changes (like name, email..), but when I use password change (admin password change) I got error:
```
RevisionManagementError at /admin/cadastro/pessoa/1/password/
Exception Type:	RevisionManagementError
Exception Value:	
There is no active revision for this thread
Exception Location:	/usr/local/lib/python2.7/dist-packages/reversion/revisions.py in _assert_active, line 168
```
Some ideia?

**Comment by etianen** [comment]
I assume that you've created a custom admin that inherits from both
VersionAdmin and the base Django user admin?

You'll need to wrap any admin view that saves the user model and generates
a change message with a revision. For example:

https://github.com/etianen/django-reversion/blob/master/src/reversion/admin.py#L174

So, look up the admin view function that's doing the password change, and
wrap it like the above example in your admin subclass.

**Comment by lucheol** [comment]
Hi!

It works. I put:

````
    def change_view(self, request, object_id, form_url='', extra_context=None):
        with self._create_revision(request):
            return super(UserAdmin, self).change_view(request, object_id, form_url, extra_context)
```
on my Admin Class.

Thank you very much for the tip and quickly answer.

If you need some contribution, I'm here!

**Comment by lucheol** [comment]
One comment.

Using your suggested fix I had to change django core files.

I realized that putting reversion.middleware.RevisionMiddleware on MIDDLEWARE_CLASSES at settings works also.

So with this config, above workaround isn't necessary.

But, thank you anyway!

**Comment by etianen** [comment]
You don't actually have to change core Django. Just subclass the relevant
admin and override the method to wrap it.

Or just use the middleware!

**Comment by BertrandBordage** [comment]
Thanks for the workaround @lucheol! It didn’t work for me as is, but applying it on the correct view worked:

```python
    def user_change_password(self, request, id, form_url=''):
        with self._create_revision(request):
            return super(YourUserAdmin, self).user_change_password(
                request, id, form_url=form_url)
```

**Comment by hex2a** [comment]
this problem still exists, while the workaround from @BertrandBordage works, i'd prefer not to save password revisions at all.
Is there any solution to this(autoregister user Model (excluding the password field) + inlinemodels via VersionAdmin)?

**Comment by etianen** [comment]
Try the master branch. There should no longer be any need for workaround in custom model admins.

Any view you wrap in a revision will create a revision, and any views you don't won't create a revision. None should raise errors.

**Comment by hex2a** [comment]
works as intended without workarounds and not storing any password revisions
