### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by matheusjardimb** [etianen/django-reversion#451]
Hello there,

This lib looks awesome! It'll probably save me a lot of hard work! But I'm facing problems getting started. I've followed the three steps here http://django-reversion.readthedocs.org/en/latest/ and I think it's incomplete or outdated.

I think the third step should be ```manage.py makemigrations / migrate``` instead of ```syncdb```. Am I right?

Also, this steps should lead to new migrations, right? If so, this did not happend to me. Should I change anything in my models? Inherit any class? 

I'm using django 1.8 and django-reversion 1.9.3.

Great!

**Comment by etianen** [comment]
Those steps work just fine. syncdb still works, and will run all the
reversion migrations.

If you just want the admin integration, then the steps listed in the
getting started guide are all you need. Reversion does not alter your
models, or require you to create additional migrations.
