### ISSUE TITLE
VersionAdapter should handle Version.revert()

### ISSUE THREAD

**Issue by longhotsummer** [etianen/django-reversion#453]
It'd be useful if `VersionAdapter` handled `Version.revert()` to support more complex version handling.

If I want to adjust how version data is calculated and saved (in my case I want to calculate and store diffs) it's pretty easy to override methods in `VersionAdapter`, which is great. However adjusting the other half of the operation -- revert -- is difficult because modifying the behaviour or `Version` isn't supported and there's no extension point. If `Version` called back to the appropriate `VersionAdapter` we could place all the new logic, both version creation and revert code, in VersionAdapter.

Another way of looking at this is that the current implementation isn't symmetrical: VersionAdapter does all the hard work dealing with versions and Version is (almost always) treated as a naive data object. The `revert` call is the exception where suddenly `VersionAdapter` has no say and `Version` handles all the business logic.

My straw-man implementation looks something like this. It's a small change but would be a powerful extension point for more complex implementations of VersionAdapter handling.

```python
class Version(object):
    # ...
    def revert(self):
        default_revision_manager.get_adapter(self.get_model_type).revert(self)

class VersionAdapter(object):
    # ...
    def revert(self, version):
        version.object_version.save()
```

Or did I miss something and is this actually easy? :)

**Comment by etianen** [comment]
I'm away on hols at the moment, so can't look too much into this, but your
suggestion seems perfectly valid. I'll have to verify it when I get back,
but I think your implementation is largely correct.

**Comment by etianen** [comment]
It's a bit more complicated than that. Something like:

``` py
class Version(object):
    
    def revert(self):
        RevisionManager.get_manager(self.revision.manager_slug).get_adapter(self.get_model_type).revert(self)

class VersionAdapter(object):
    
    def revert(self, version):
        version.object_version.save()
```
