### ISSUE TITLE
how to set different comment for different table in one transaction

### ISSUE THREAD

**Issue by lovemyliwu** [etianen/django-reversion#455]
FYI, we need update multi row data in a loop, and need set different comments to different row.
The python code as below:

        for package_availability in package_availabilities:
                package_availability.amount -= package_availabilities_count[package_availability.id]
                package_availability.save()

                reversion.set_user(user)
                reversion.set_comment("Consume %d stock(booking_id: %s) from new booking" % (
                    package_availabilities_count[package_availability.id], booking_object.booking_id))

As Now, all package_availability data comments go with the last set_comment step.

Can someone help me?

**Comment by etianen** [comment]
Something like this:

``` py
    for package_availability in package_availabilities:
        with reversion.create_revision():
            package_availability.amount -= package_availabilities_count[package_availability.id]
            package_availability.save()

            reversion.set_user(user)
            reversion.set_comment("Consume %d stock(booking_id: %s) from new booking" % (
                package_availabilities_count[package_availability.id], booking_object.booking_id))
```

**Comment by lovemyliwu** [comment]
@etianen thanks, now in my view problem solved, but i still had this issue in django admin, please help.

**Comment by etianen** [comment]
It's hard to know what to do without seeing your admin code. The same
principal applies, however. Separate out your package_availability rows
into different revisions using the reversion.create_revision() decorator.

**Comment by lovemyliwu** [comment]
@etianen i mean the same code in save_model function of CustomAdmin inherit from VersionAdmin not work.
                class CustomAdmin(VersionAdmin):
                        def save_model(self, *args, **kwargs):
                                for package_availability in package_availabilities:
                                           with reversion.create_revision():
                                                  package_availability.amount -= package_availabilities_count[package_availability.id]
                                                  package_availability.save()

                                                  reversion.set_user(user)
                                                  reversion.set_comment("Consume %d stock(booking_id: %s) from new booking" % (
                package_availabilities_count[package_availability.id], booking_object.booking_id))

**Comment by etianen** [comment]
In the admin, the whole view is wrapped in a create_revision, which takes
precedence.

To implement this, you'll need to subclass ModelAdmin, instead of
VersionAdmin, and re-implement the version control functionality yourself.
