### ISSUE TITLE
Add custom button to model admin

### ISSUE THREAD

**Issue by Ajeetlakhani** [etianen/django-reversion#459]
I am trying to add django-reversion with existing admin. All works fine but it is replacing my custom buttons which i created by extending admin/change_list.html

Initially i had buttons like this 
![custom_buttons](https://cloud.githubusercontent.com/assets/8472589/11037312/289e576e-8723-11e5-8586-f6adb9a7072c.png)

after adding django-reversion it created new button but replaced my custom button

![recoverdata](https://cloud.githubusercontent.com/assets/8472589/11037362/63669a46-8723-11e5-8b01-5f673cdadeb3.png)

I figured out that this is happening because this package is also extending admin/change_list.html template and overiding object-tools-items block.

and i want something like this

![final](https://cloud.githubusercontent.com/assets/8472589/11037382/7abda50e-8723-11e5-9f48-d11a68c0811a.png)

**Comment by etianen** [comment]
Just extend the reversion/change_list.html template with your own custom
template. :)

**Comment by Ajeetlakhani** [comment]
I extended reversion/change_list.html  as you said and gave template path to change_list_template in admin model. Now it works great.

Thanks for the help. :)
