### ISSUE TITLE
Field.rel deprecated

### ISSUE THREAD

**Issue by jarekwg** [etianen/django-reversion#462]
According to the deprecation warning, as of django19 Field.rel has become deprecated and Field.remote_field should be used instead.

However according to the django docs (https://docs.djangoproject.com/en/1.9/releases/1.9/#field-rel-changes), it might not be as simple as just a quick rename, so thought I'd pop this in a ticket instead.

Offending occurences in code:
reversion/reversions.py:59
reversion/admin.py:127
reversion/admin.py:135

**Comment by etianen** [comment]
Thanks! If it's too complicated to change I'll just make the next release
of reversion support Django 1.9+. Pretty much the only reason for new
releases these days is django compatibility, in any case.

**Comment by EyePulp** [comment]
It looks like this was fixed by @ticosax with commit  ebc43b412ac25d3be401ce5bd437224d480017d7  -- but it doesn't look like that's in PyPi yet.  Any ETA on when it might get published there?

Thanks for the work - this is nice project. =)

**Comment by etianen** [comment]
I can see if it's good for a quick release on Monday.

**Comment by EyePulp** [comment]
Awesome - thank you.

- andrew -

On January 23, 2016 at 10:28:03 AM, Dave Hall (notifications@github.com) wrote:

I can see if it's good for a quick release on Monday.

**Comment by etianen** [comment]
No problem. 1.10.1 is now out.

**Comment by claudep** [comment]
Couldn't this issue be closed?
