### ISSUE TITLE
The method to get a version by ID

### ISSUE THREAD

**Issue by LeoQuote** [etianen/django-reversion#464]
There's only one way to get a version in the doc 
you get the object ,and find version related with this object ,and get the version

I think I found a way to get the version by ID

```python
from reversions.models import Version
version_by_id = Version.objects.get(pk=6800)
version_by_id.field_dict
```
should that be added to the doc ?

**Comment by etianen** [comment]
That' the correct method to get a version by id.

It could be added to the docs as an example, by all means. It's more
important, though, I think, to document that Version is just a django
model, so all the normal Djano ORM methods work just fine.
