### ISSUE TITLE
./manage.py createinitialrevisions gives the following error

### ISSUE THREAD

**Issue by tilaprimera** [etianen/django-reversion#467]
./manage.py createinitialrevisions 

Gives the following traceback, 

    /home/tilaprimera/Envs/tp/lib/python2.7/site-   
    packages/reversion/management/commands/createinitialrevisions.py:68:  
    RemovedInDjango19Warning: [a.models_module for a in get_app_configs()] supersedes
    get_apps().
    for app in get_apps():
    /home/tilaprimera/Envs/tp/lib/python2.7/site-packages/django/utils/lru_cache.py:101:   
    RemovedInDjango19Warning: The app_mod argument of get_models is deprecated.
    result = user_function(*args, **kwds)

Installed packages:

    Django==1.8.3
    django-reversion==1.9.3

**Comment by etianen** [comment]
That's not an error, just a deprecation warning. I think most of them have
been squashed in the master branch.
