### ISSUE TITLE
extra_context is ignored in recover_view

### ISSUE THREAD

**Issue by yakky** [etianen/django-reversion#470]
Around 1.9 ``extra_context`` argument became ignored in ``VersionAdmin.recover_view`` (see https://github.com/etianen/django-reversion/blob/master/src/reversion/admin.py#L209) this makes harder to customize the behavior of the view. Any specific reason for this change?

**Comment by etianen** [comment]
Please check out the master branch, and let me know if it works for you!

**Comment by yakky** [comment]
@etianen thanks, issue fixed
