### ISSUE TITLE
AttributeError: 'module' object has no attribute 'commit_on_success'

### ISSUE THREAD

**Issue by Dean-Christian-Armada** [etianen/django-reversion#473]
This happends when I include 'reversion' on the INSTALLED_APPS, every django command in shell will throw this error. I am using django 1.8.2
![selection_030](https://cloud.githubusercontent.com/assets/9837087/11707653/30f2128e-9f42-11e5-801f-82afad88872f.png)

**Comment by etianen** [comment]
Try upgrading to the latest release of django-reversion.

http://django-reversion.readthedocs.org/en/latest/django-versions.html

**Comment by Dean-Christian-Armada** [comment]
pip-install django-reversion. you mean this command line does not get the latest relsease?

**Comment by etianen** [comment]
If you haven't already installed django-reversion, then you'll get the
latest release. However, if an older release of django-reversion is already
installed, it'll just use that.

Your traceback is from an older release of django-reversion.

**Comment by Dean-Christian-Armada** [comment]
Thank you seems like that was the case,, Can this package also revert the ones that was updated?

**Comment by etianen** [comment]
Sorry, I don't quite follow what you mean. Could you clarify?

**Comment by Dean-Christian-Armada** [comment]
Let's say:

x = Foo.objects.get(id=3)
x.name = "New Update Name"
x.save()

Can this update can be reverted by the package?

**Comment by etianen** [comment]
Yes, of course. :)

http://django-reversion.readthedocs.org/en/latest/api.html

**Comment by danielmanser** [comment]
@Dean-Christian-Armada: You can always upgrade to the latest version with:

    pip install -U django-reversion

**Comment by Dean-Christian-Armada** [comment]
@etianen Wow Thanks! Will check it out
