### ISSUE TITLE
AttributeError: 'module' object has no attribute 'create_revision'

### ISSUE THREAD

**Issue by danielmanser** [etianen/django-reversion#474]
I recently migrated from Django 1.8.5 to 1.9. Now, i get this error:

  File "/opt/djangoapps/.../import_rir.py", line 99, in handle
    with transaction.atomic(), reversion.create_revision():
AttributeError: 'module' object has no attribute 'create_revision'

Before 1.9, I used:

    with reversion.create_revision():
        # Code...
        r.save()

I discovered that this has changed with a new release of django-reversion, so I did:

    with transaction.atomic(), reversion.create_revision():
        # Code...
        r.save()

But that didn't help. What am I doing wrong? I use django-reversion 1.10.0:

    (virtualenv)daniel@spitfire:~$ pip freeze | grep reversion
    django-reversion==1.10.0

**Comment by etianen** [comment]
Check the changeling here:

https://github.com/etianen/django-reversion/blob/master/CHANGELOG.md#110---02122015

**Comment by danielmanser** [comment]
Thanks, I didn't see this. Working now.
