### ISSUE TITLE
Having trouble with parent pointers starting with an underscore

### ISSUE THREAD

**Issue by LegoStormtroopr** [etianen/django-reversion#478]
I'm not sure if this is a bug, or if my code is causing the problem. But I'm covering all my bases as I can't get my reversions to work.

Basically, I have a parent model called `_concept` that and the child models are defined using:

    reversion.register(ObjectClass,follow=['_concept_ptr'])

However the version for the parent model is never access from the database, despite being stored. I'm at my wits end and need this to work pretty bad. Any ideas?

http://stackoverflow.com/questions/34479124/how-to-store-parent-pointers-and-data-in-a-django-reversion

**Comment by LegoStormtroopr** [comment]
After some digging it seems that I've got some sort of conflict between reversion and haystack thats causing things to fail.

After disabling the haystack indexers everything works fine, the issue is the Haystack signals are called when django-reversion tries to save the deserialized items to check consistency - but then django calls the haystack post_save signals which try to update the index with incomplete data.

What I need in my haystack handler is either a way to determine if I'm inside a revisions transaction, or a way to prevent reversion from letting those signals fire. The latter is probably a better long term goal as I suspect that just by looking at revisions it is updating the Haystack index.

**Comment by LegoStormtroopr** [comment]
And the answer is...

Tying the Haystack updates to the reversion `post_revision_commit` signal instead of the regular `post_save` signal in Django. It also helps to not use the Haystack `RealTimeSignal` processor as that also adds a `post_save` hook to every item save as well.

**Comment by etianen** [comment]
Thanks for posting your solution! This sounds like a signal conflict, like
you say.

The reversion admin integration makes the assumption that calling save() on
a model, followed by a database rollback, causes no side-effects. I guess
in the case of haystack, there are indeed side-effects...

I'm not sure of a better solution, however.

**Comment by LegoStormtroopr** [comment]
Its was a save assumption to make. It seems that the biggest conflict is with the 'reversion.Middleware' on that page, but I need to do some more testing.

Apart from having to add more explicit reversion control, everything else seems to work fine. I'll report back when I get a better idea.
