### ISSUE TITLE
empty lists using shell 

### ISSUE THREAD

**Issue by k0ssi** [etianen/django-reversion#479]
im currently trying to use the "low level api" to receive an old version of object. Django-reversion is registered within my model. 
```
class CatalogAdmin(VersionAdmin,admin.ModelAdmin):
``` 
everything works fine using the admin menu 
<img width="397" alt="screen shot 2016-01-07 at 10 51 05" src="https://cloud.githubusercontent.com/assets/4948414/12167485/a88e3aac-b52c-11e5-9c74-cd5ee5a8e863.png">

now im trying to get revisions by using the low level api which results in empty lists
```
from reversion import revisions as reversion
from appsupport.models import Catalog
xx = Catalog.objects.get(pk=2) 
reversion.get_for_object(xx)        
[]
len(reversion.get_for_object(xx))
0
```
PK=2 belongs to objects "anderer katalog test" displayed in picture which works fine in admin menu

same problem while recovering deleted items
<img width="512" alt="screen shot 2016-01-07 at 10 51 23" src="https://cloud.githubusercontent.com/assets/4948414/12167486/a8900012-b52c-11e5-913e-8f81e9ba1d70.png">
```
>>> reversion.get_deleted(Catalog)
[]
>>> len(reversion.get_deleted(Catalog))
0
```
works fine using the admin menu, returns empty lists using shell

**Comment by etianen** [comment]
If you’re using django-reversion in a management command or shell, and are
using the automatic VersionAdmin registration method, then you’ll need to
import the relevant admin.py file at the top of your management command
file.

**Comment by k0ssi** [comment]
wow this answer was really fast, thanks a lot !

unfortunately importing the admin.py results in following error:
(started a new shell already)
```
(InteractiveConsole)
>>> import appsupport.admin
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/vagrant/XXX/appsupport/admin.py", line 40, in <module>
    admin.site.register(Question,QuestionAdmin)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 90, in register
    raise AlreadyRegistered('The model %s is already registered' % model.__name__)
AlreadyRegistered: The model Catalog is already registered
>>> 
```

**Comment by etianen** [comment]
Looks like you're double-importing the admin.py file, somehow.

Are you using relative imports in your python code anywhere?

**Comment by k0ssi** [comment]
i just added admin.py to my previous post

**Comment by etianen** [comment]
Okay, in some places you're calling the module AppSupport, and in others you're calling it appsupport. That's probably the issue.

Your issue is arising because Python is importing your admin.py file twice. This can happen either if you're inconsistent with the casing of the module name in your imports, or if you use relative Python imports anywhere in your codebase.

Note that the error you're receiving is a Django admin error. It's got nothing to do with reversion at this point!

**Comment by k0ssi** [comment]
arghhh your right. I didn't realize django isn't case sensitive. 
Now everything works fine !
````
>>> reversion.get_for_object(xx)
[<Version: anderer katalog test>, <Version: anderer katalog>
````
i know the last error was coming form django it has nothing to do with my initial problem. 
Thanks a lot !!
