### ISSUE TITLE
Compatibility release issue

### ISSUE THREAD

**Issue by Stranger6667** [etianen/django-reversion#480]
Hi!
I'm looking for Python 3.2 compatible django-reversion version for Django 1.5.x. release-1.7.x branch seems to be compatible, but latest release in this branch is not.
Can you create one extra release (1.7.2) from 1ef455a?
Anyway for now I'm using direct commit version.  It will be very useful for me and some other people if it will be available on PyPI.
Thanks

**Comment by etianen** [comment]
Not a problem! I've also updated the compatibility table in the docs.

**Comment by Stranger6667** [comment]
Thank you, Dave! :)
