### ISSUE TITLE
Django 1.9/ Python 3.4 error: OptionParser deprecated, use ArgumentParser instead

### ISSUE THREAD

**Issue by khlumzeemee** [etianen/django-reversion#483]
Hi
when trying to generate the initial revision for a class I get the below error:

```
/home/cabox/Envs/my_virtual_env/lib/python3.4/site-packages/django/core/management/base.py:265: RemovedInDjango110Warning: OptionParser usage for Django management commands is deprecated, use ArgumentParser instead                                                                               
  RemovedInDjango110Warning)  
```
The exact command is as follows:
```
python manage.py createinitialrevisions reservation.Reservation                           
```

Additonal details:
* django-reversion==1.10.0
* Django==1.9.1

**Comment by etianen** [comment]
It's only a warning, and won't stop the command from working.

Nevertheless, it'll need to be fixed at some point, and I'll take a pull
request to squash the error.

**Comment by khlumzeemee** [comment]
Hi
Actually the command doesn't do anything,  doesn't create any migration
script. That doesn't seem right.. 😞

**Comment by etianen** [comment]
What was the full output of the command?

**Comment by khlumzeemee** [comment]
It's only warnings, it doesn't seem to do anything else.

I followed the instructions, pip install django-reversion, added 'reversion' to the INSTALLED_APPS, created and registered a class extending VersionAdmin

```
python manage.py createinitialrevisions                                                   
/home/cabox/Envs/myproject/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use 
Field.from_db_value instead.                                                                                                                   
  return meta(name, bases, d)                                                                                                                  
                                                                                                                                               
/home/cabox/Envs/myproject/lib/python3.4/site-packages/django/core/management/base.py:265: RemovedInDjango110Warning: OptionParser usage for Djan
go management commands is deprecated, use ArgumentParser instead                                                                               
  RemovedInDjango110Warning)     
```

**Comment by etianen** [comment]
Hmm, so in a Django shell, try:

from reversion.models import Version
Version.objects.count()

You should see some versions in the database.

**Comment by khlumzeemee** [comment]
You were right it works, I redid the procedure from the start and migration scripts were generated and run.
Thank you for your help! :)
