### ISSUE TITLE
Renaming a model during a migration 

### ISSUE THREAD

**Issue by jeffrand** [etianen/django-reversion#485]
Hey! So first off, I love reversion and use it extensively. I'm currently working through a large refactor which including moving and renaming a number of models we track with reversion. Is there any way to migrate the reversion history to follow the new model?

**Comment by etianen** [comment]
I'm afraid not. The serialized Django model representation is really
indexable or parsable by the database, so migrating a huge revision history
is a time-consuming an inefficient process.

I tend to just axe the revision history on a major migration, notifying the
site admins before doing so, of course!
