### ISSUE TITLE
django.core.exceptions.ImproperlyConfigured: Cannot use VersionAdmin with a database that does not support savepoints.

### ISSUE THREAD

**Issue by davneet4u** [etianen/django-reversion#486]
It occurs on the line  admin.site.register(Post,PostAdmin)

Cannot use python manage.py on my local, though everything works fine in my production.

Have even tried changing the database(postgresql) but to no avail.

**Comment by etianen** [comment]
What database are you using locally? All core Django database support save
points.

**Comment by davneet4u** [comment]
The problem was that settings did not take my database.

I was using local settings which had a typo error. And it was not showing error because in try, except block, I did not write ImportError.
