### ISSUE TITLE
Upgrade management commands to ArgumentParser

### ISSUE THREAD

**Issue by claudep** [etianen/django-reversion#487]
Django 1.10 will stop supporting optparse-based management commands.

The question is: will the next django-reversion still support Django < 1.8? If yes, some compat glue code will be needed. If no, things are a bit simpler to update the commands.

**Comment by etianen** [comment]
I think dropping Django 1.7 support is reasonable now, given that Django
has itself dropped the support.

https://www.djangoproject.com/download/
