### ISSUE TITLE
"exclude" does not seem to mean "ignore"; how to ignore?

### ISSUE THREAD

**Issue by 2manydjs** [etianen/django-reversion#489]
Hello,

Firstly, thanks for releasing this package.  
I am faced with one issue though: I am using the `exclude` argument for a field that is recording the number of views on the page: for obvious reasons I don't want a revision to be created every time someone visits the page.  I have excluded the field and it is not stored in the version data, however the save still triggers a revision entry.

How can I make it such that if only the excluded field is updated, no revision is triggered?

**Comment by etianen** [comment]
I'm afraid that there's no efficient way to compare the current revision
data against the older revision data. If you don't want to save a revision,
don't decorate the view with the reversion.create_revision() decorator.

**Comment by 2manydjs** [comment]
Thanks,  I am using the middleware to catch all changes.  Is it possible to have a decorator that makes the middleware exclude the revision?

For now I have excluded the view value from the model: it's not that important to have at the moment.  If I do want to include the view I'll likely switch to explicit decorators instead of the middleware.

**Comment by etianen** [comment]
The middleware isn't recommended for use any more, as it results in
revisions being saved outside of transactions, with the potential for
database inconsistency. See the warning here:
https://django-reversion.readthedocs.org/en/latest/api.html#revisionmiddleware.
It's better to decorate invididual views with create_revision()

That being said, if you want a backdoor to stop revisions being created,
use reversion.create_revision(manage_manually=True) as a decorator or
context manager to disable revision control for a block of code.
