### ISSUE TITLE
Deprecation Enquiry

### ISSUE THREAD

**Issue by mrtorks** [etianen/django-reversion#491]
In 1.8, VERSION_ADD,VERSION_DELETE and VERSION_CHANGE were removed. I took over a client's project and the code uses these three instances for filtering ``version_set()``. Is there a work around for this and if not what do you suggest I do to handle this issue. 40% of the code contains these three instances.

**Comment by etianen** [comment]
There are a few options:

1. Use the django admin LogEntry module, which stores the same information,
but only for models in the admin system.
2. Create your own signal handlers and you own models that store this
information in parallel with the revisions being created.

The reason these fields were removed from django-reversion was that they
were only useful for generating statistics about user activity on the site,
and were not used internally by django-reversion. As such, they are a prime
candidate for writing as a separate set of functionality.

**Comment by mrtorks** [comment]
@etianen In respect to creating my own signal handlers. I have never done so before. Could you point me in the right direction and would it be a custom integration into the django-reversion or just specific to the models that use the reversion module

**Comment by etianen** [comment]
Here you go: https://docs.djangoproject.com/en/1.9/topics/signals/

Basically, listen to the post_save and pre_delete signals of models you
want to track, and store whatever meta information you want in the database.
