### ISSUE TITLE
Dynamically adding additional foreign key relationships when using VersionAdmin

### ISSUE THREAD

**Issue by chris-erickson** [etianen/django-reversion#493]
We use the VersionAdmin extensively around a large site, and it has some functionality to add translations from parler which are a different, but related, model (we subclassed VersionAdmin and register those models in `__new__`).  I have a few places where I would like to add additional foreign key relations that aren't otherwise picked up.  Typically, one would just register the model with these fields added [in accordance with the docs](https://django-reversion.readthedocs.org/en/latest/api.html#advanced-model-registration).  In a quick test, I can't register this in the admin this way because `VersionAdmin` has already stepped in at this point.  I've seen references to registering in the `models.py` but that doesn't scale as nicely when I have many models (30+).

I'll try to illustrate with a crude example.

```python
class Car(models.Model):
    color = ...
    wheels = ...

class Garage(models.Model):
    cars = models.ManyToManyField(Car, related_name="my_garages"),

class Driver(models.Model):
    cars = models.ManyToManyField(Car, related_name="my_drivers"),
```

```python
class CarAdmin(VersionAdmin):
    ... normal admin things here
```
My thought is to add an attribute to the `ModelAdmin` definitions that I could somehow add fields above and beyond what the `VersionAdmin` does, like so:

```python
class CarAdmin(ExtendedVersionAdmin):
    ... normal admin things here
     additional_reversion_relations = ['my_garages', 'my_drivers']
```
These M2M's are managed with inlines so it would be nice to see changes to them in the change history for `CarAdmin`.

Is there a strategy for revising these registrations?  Perhaps by grabbing the existing relations and re-registering with the addition of those in `additional_reversion_relations`?  Or maybe just directly accessing the `reversion` internals and appending them somehow?

-- EDIT: [Asked on SO](https://stackoverflow.com/questions/35560678/adding-reverse-manytomany-relations-to-change-history-with-reversion) in attempt to cast a wider net.

**Comment by etianen** [comment]
In your case, it's probably simpler to overide _autoregister().

def _autoregister(self, model, follow=None):
    follow =  follow or []
    if model === MyModel:
        follow.append("also_this_field")
    super()._autoregister(model, follow)

**Comment by etianen** [comment]
(To be honest, though, manually registering the models using
reversion.register() is a one-time setup, and gives you more control and
avoid this sort of hackery)
