### ISSUE TITLE
Has django-reversion 1.11 been released?

### ISSUE THREAD

**Issue by zvovov** [etianen/django-reversion#494]
Was looking through the docs at http://django-reversion.readthedocs.org/en/latest/django-versions.html. 
django-reversion 1.11 is listed to be compatible with django 1.8+, but has 1.11 been released yet?
If yes, where can I find it?

**Comment by etianen** [comment]
It's not released yet. I'm not sure why that was in the version table, but
I've corrected it. :)

**Comment by eskhool** [comment]
Hi, sorry to bug you but do you have an idea when you might be able to release it by? Just asking since Django 1.7 is no longer officially supported even for security bug fixes ...
Should we start testing with the master branch if that's what you need right now?

**Comment by etianen** [comment]
What part of 1.11 do you need? I'm not aware of any important features on
the master branch beyond 1.10.0. It just suppresses a few warnings.
