### ISSUE TITLE
User ID when revert a version ?

### ISSUE THREAD

**Issue by cesclondon87** [etianen/django-reversion#495]
Hi,
I'm a newbie (I use django 1.9 & python 3.4 & postgresql 9.4).
I see that django-reversion (1.10.1) doesn't save user_id when a user revert a version (it only save author when save a new revision). 
Why? Can I set author with a signal or I have to add Custom metadata table (with add_to_meta method)?
Thanks

**Comment by etianen** [comment]
Are you using the admin integration, or your own custom views?

**Comment by cesclondon87** [comment]
I'm using custom views.

**Comment by etianen** [comment]
Reverting a revision is identical to creating a new revision.

with reversion.create_revision():
    reversion.set_user(your_user)
    reversion.get_for_object(your_object)[0].revision.revert()

**Comment by cesclondon87** [comment]
>with reversion.create_revision():
>    reversion.set_user(your_user)
    reversion.get_for_object(your_object)[0].revision.revert()

I'm sorry but I'm not able to use transaction.Anyway i'm using reversion.middleware.RevisionMiddleware. 

> Reverting a revision is identical to creating a new revision.

I'm agree but if i use RevisionMiddleware why doesn't save user id when execute a revert operation?

**Comment by etianen** [comment]
The user ID is only added automatically to a revision if the request.user
attribute is accessed elsewhere in your view. I guess your revert view
isn't doing this.

In your case, just add a reversion.set_user(your_user) line above the place
where you revert the revision.

**Comment by cesclondon87** [comment]
Thanks !!! @etianen !!!
