### ISSUE TITLE
query over deleted object by fields

### ISSUE THREAD

**Issue by molavy** [etianen/django-reversion#501]
hi
i want query over deleted object to show in recover page
reversion.get_deleted(product_price).filter(process_id=50)
there is no option for doing such things

**Comment by etianen** [comment]
I'm afraid not. The serialized representation of the model is serialized as JSON, which can't be efficiently indexed. There's no way to do this without creating a per-model version table, which isn't how django-reversion works.

If you need this sort of functionality, you probably want to implement your own versioning solution.

**Comment by molavy** [comment]
without such ability getting deleted objects are useless , because in progress and large table , you are not able doing any filter against deleted objects

**Comment by etianen** [comment]
It's pretty useful if you want to show admin users a list of deleted
objects, and allow them to recover them. You can sort by date over the
deleted objects, which is useful for putting recently-deleted objects first.

It might be useless to you, but plenty of people do find the current
functionality very useful.

**Comment by molavy** [comment]
this is true for very small apps with small dataset
in large dataset, getting recent deleted objects become meaningless, it should be multi level admin for each section of dataset according to filters

**Comment by etianen** [comment]
The only way to code that efficiently would be to have a separate revision table, with relevant indices, for for each table under version control. It's do-able, but it's very complicated and comes with some caveats of it's own (unique constraints, foreign keys).

**Comment by silviogutierrez** [comment]
Any possibility of opt-in use of JSONField for us lucky Postgres users? That would keep the simplicity of the current model but make the data easily queryable.

See here: https://docs.djangoproject.com/en/1.9/ref/contrib/postgres/fields/

I believe this can be done with a custom model right now.

**Comment by etianen** [comment]
The only tricky thing with this would be that serialization formats other than JSON are currently supported on a per-model basis.

TBH, I'd love to standardize on the JSON serialization format and use a JSONField for postgres. I've never been sure why people want to use alternative serialization formats. It would be a tricky database migration to write though, and potentially a very slow one if a massive revision database containing non-JSON data is present.

I've added this as a separate issue, here: #557
