### ISSUE TITLE
How to make explicit vertion comments automatically?

### ISSUE THREAD

**Issue by satyrius** [etianen/django-reversion#502]
I add `django-revertion` to my project, make some changes and see the following in my change log

![image](https://cloud.githubusercontent.com/assets/278630/14528879/7cb182a6-025a-11e6-8018-61813c23856b.png)

1. Why they are all named as "Reverted to previous version"?
2. How could I make comments more verbose, showing changed columns at least?

**Comment by etianen** [comment]
That "reverted to previous version" should only happen if you load up a previous version from the history view, then revert it.

Normal model saving in the admin should give a normal django admin comment, listing the fields that were changed.
