### ISSUE TITLE
Migrating to django-reversion. Any easy API?

### ISSUE THREAD

**Issue by georgema1982** [etianen/django-reversion#503]
The original developer of the project I'm working on rolled out a versioning solution of his own. It's designed in a bad way and I'd like to migrate to django-reversion. My plan is read each old versioning data and feed them into django-reversion'd database. I wonder if there's an easy API to work with.

**Comment by etianen** [comment]
I'm away at the moment, but can give you a good starter when I'm back on
Monday!

**Comment by etianen** [comment]
Okay, I think you're best off doing this with the Django ORM.

For each "entry" in your version history, create a `reversion.Revision` model. Each `Revision` needs one or more `Version` models associated with it, where is `Version` is one of the models in that version history entry. For example, for a given admin page, a `Revision` would contain a `Version` for the main model, plus another `Version` for every inline model on the page.

The only difficulty is that the `date_created` field on `Revision` has `auto_now_add` set on it, making a small hack required to override it. This is very annoying, and is being tracked in #482. A pull request is welcome!

``` py
from django.db import transaction
from django.core import serializers
from django.contrib.contenttypes.models import ContentType
from reversion.models import Version, Revision

for legacy_entry in list_of_your_legacy_version_history:
    with transaction.atomic():
        revision = Revision.objects.create(
            user=legacy_entry.user,
            comment=legacy_entry.comment,
        )
        # HACK: Override date_created.
        Revision.objects.filter(pk=revision.pk).update(date_created=legacy_entry.date_created)
        # Assumes that it's possible to get a list of model instances from the legacy entry.
        # You may have to create `serialized_data` manually from the legacy entry, by looking into
        # the format of the django serialization framework.
        for instance in legacy_entry.instances:
            Version.objects.create(
                revision=revision,
                object_id=instance.pk,
                object_id_int=instance.pk,  # Assuming instance.pk is an integer.
                content_type=ContentType.objects.get_for_model(instance),
                format="json",
                serialized_data=serializers.serialize("json", instance),
            )
```
