### ISSUE TITLE
Fix supported version table

### ISSUE THREAD

**Issue by pquentin** [etianen/django-reversion#506]
http://django-reversion.readthedocs.org/en/latest/django-versions.html says that 1.10.2 supports Django 1.7+ but it actually requires Django 1.8+. (I have no issues with this, but I think the table is misleading or wrong.)

Thank you for continuing to work on this year after year, it's really appreciated.

**Comment by etianen** [comment]
Damn damn damn, you're right. 1.10.0 supports Django 1.7.

That should really have been a minor version bump, I guess. Drat. Damage
done.

Thanks for pointing it out!
