### ISSUE TITLE
Is there a way to update reversion info regarding (simple) DB migrations?

### ISSUE THREAD

**Issue by acidjunk** [etianen/django-reversion#509]
We did run a migration which added a required, non null, field. When we try to revert older records, with a reversiond date from before the migrate, we get an error like this:
```
IntegrityError: null value in column "category_id" violates not-null constraint
DETAIL:  Failing row contains (112, 2016-04-11 19:54:54.366+00, null, 10, TEST, null)
```
Is there a way to fix old reversions? Are there tools to edit stuff in all stored revisions, so we can fix this manually?

**Comment by etianen** [comment]
There's no built-in tools for migrating old revisions to new model schema,
unfortunately. Even if there were, it would be an extremely slow process,
involving rewriting huge amounts of textual data from the database.

You can do it manually by looping over the relevant Version objects,
parsing the serialized_data property, modifying it, then re-saving the
Version.

**Comment by acidjunk** [comment]
Ok thanks, will try that.
