### ISSUE TITLE
Add `--no-input` flag like every other Django command

### ISSUE THREAD

**Issue by crccheck** [etianen/django-reversion#516]
Currently, Reversion uses `--no-confirmation`, but no one else does that. The expected behavior is `--no-input`.

**Comment by etianen** [comment]
A valid point. This should be added as an alias for the time being, with a
deprecation notice. I'll take a pull request, or have a look myself when
time permits.

**Comment by crccheck** [comment]
I'll see if I can bang out a quick PR. I've been really into the "Principle of least astonishment" lately.

**Comment by etianen** [comment]
Would be appreciated! django-reversion needs some love at the moment, but
I'm snowed under with the sort of work where I get in trouble if it's not
done on time at the moment. I'm looking forward to a break in my schedule
so I can give django-reversion some more attention.
