### ISSUE TITLE
Version accesses private code since django 1.8

### ISSUE THREAD

**Issue by wimglenn** [etianen/django-reversion#518]
This has caused me some issues when resolving GFKs:  in [Version.field_dict](https://github.com/etianen/django-reversion/blob/master/src/reversion/models.py#L183) there is access on `obj._meta.fields`.  Since Django 1.8, when the interface of the Options class was firmed up, this property is marked as [Private API intended only to be used by Django itself](https://github.com/django/django/blob/stable/1.8.x/django/db/models/options.py#L381-L383).   External access should go through `get_fields()` method instead.

**Comment by etianen** [comment]
GFKs?

**Comment by wimglenn** [comment]
GenericForeignKey sorry!

**Comment by etianen** [comment]
:)

So, you're saying that django-reversion should use get_fields() in all
places it currently uses .fields?

**Comment by wimglenn** [comment]
Yes, that's mentioned in the docstring of Options.fields since 1.8 

`get_fields() combined with filtering of field properties is the public API for obtaining this field list`

thanks!
