### ISSUE TITLE
Django reversion and PG Bouncer?

### ISSUE THREAD

**Issue by ckcollab** [etianen/django-reversion#522]
Heyo! Thanks so much for releasing and supporting this!

I got this error as soon as I tried setting up pgbouncer on Heroku -- I could have been doing something else wrong, but it seems like that's the source of the problem:
```django.core.exceptions.ImproperlyConfigured: Cannot use VersionAdmin with a database that does not support savepoints.```

Is this package compatible with pgbouncer? Do I need to swap some settings or something? Using my Google skills didn't show anything, apologies if it's in the docs somewhere!

**Comment by etianen** [comment]
I take it that pgbouncer is implemented as a custom database backend for
Django?

Basically, Django-reversion introspects the capabilities of the database
backend to see if it supports save points, which is needed for the admin
preview functionality. It looks like pgbouncer backend doesn't advertise
this capability.

You should contact the team behind the pgbouncer backend and ask them to
add the save point capability flag to their backend (assuming it does
actually support this capability!).

**Comment by ckcollab** [comment]
PG Bouncer is for pooling Postgres connections, but yeah that makes sense!

Thanks for the quick response and all the work on this project. One of my clients was concerned we didn't have an "audit trail" or anything to keep track of model changes. Took about an hour to get this working :) saved me a ton of time, appreciate it!

**Comment by etianen** [comment]
No worries! Feel free to update this issue with your progress or other
questions from the PGBouncer team!
