### ISSUE TITLE
Small clarification to docs about Version vs Revision management

### ISSUE THREAD

**Issue by jasonm** [etianen/django-reversion#523]
From [django-reversion Google Group thread "Clarification on automatic revisions and context managers
"](https://groups.google.com/forum/#!topic/django-reversion/cM7p7Dq4WKg):

Jason wrote:

>> By default, django-reversion saves a new revision whenever a model is saved, using the post_save signal. 

> -- http://django-reversion.readthedocs.io/en/latest/api.html#registering-with-custom-signals (emphasis mine)

> But that's not actually true, right?  From reading the source and using django-reversion, it seems that in addition to registering models of interest that I have to manage the creation of Revisions myself (through middleware, explicitly calling create_revision, etc.), and that the operation that gets automatically performed by RevisionManager._signal_receiver is the addition of a Version into the Revision's context.  There's no save to the database going on  until we exit the create_revision context or call revision_context_manager.end().

Dave Hall wrote:

> Yes, you understand correctly. The documentation is a little unclear on this. If you could raise an issue about it on the project issue tracker, I'll attend to it next week.

**Comment by etianen** [comment]
Fixed in refactor branch:

https://github.com/etianen/django-reversion/tree/refactor
