### ISSUE TITLE
Confusion over use of model vs object

### ISSUE THREAD

**Issue by stephenross** [etianen/django-reversion#529]
Reading the documentation for this app, I see that it all talks about saving a snapshot of a model, but all of the supporting information makes it seem like this is really meaning to say object, not model, and the disconnect is causing me some confusion. If this is meant to track and save model changes, that would make this a replacement for migrations, but I understand that you tag a model for reversioning, but the actual versions saved are snapshots of the objects created under that model of the data itself. If this is correct, would it be possible to update the README and associated documentation in the project to correct that inconsistency?

**Comment by etianen** [comment]
It's unfortunate that, in different context, "model" is regularly used to refer to both model instances and model classes.

I'm in the process of refactoring the docs at the moment, so I'll bear this in mind.

**Comment by etianen** [comment]
Fixed in refactor branch:

https://github.com/etianen/django-reversion/tree/refactor
