### ISSUE TITLE
Migration 0003 is extremely slow

### ISSUE THREAD

**Issue by BertrandBordage** [etianen/django-reversion#535]
On my projects I currently can’t run migration 0003. It’s taking forever, I let it run more than 3 hours in vain. I’m using exclusively PostgreSQL.

That’s because of this query: https://github.com/etianen/django-reversion/blob/v2.0.0/reversion/migrations/0003_auto_20160601_1600.py#L15
It’s not returning distinct results because of [the default ordering of Version](https://github.com/etianen/django-reversion/blob/v2.0.0/reversion/models.py#L99). It’s therefore returning a gigantic list. This list is used to generate ludicrous SQL queries containing thousands of  `OR` (even millions in my case).

The solution is simply to add an empty `.order_by()` at the end of the line.

**Comment by etianen** [comment]
Goodness, that's bad. I've applied your fix. A new release will hit shortly, once I've addressed #536.

**Comment by JanMalte** [comment]
Running the migration on my system with the new release including the bugfix still takes hours to finish (~4h, it is still running)

**Comment by etianen** [comment]
I'd suggest using the deleterevisions command to prune your revision database. Migrating huge datasets takes a while and there's no getting around it.
