### ISSUE TITLE
Migration 0004 cannot create the unique constraint

### ISSUE THREAD

**Issue by BertrandBordage** [etianen/django-reversion#536]
After dealing with #535, I’m stuck at the migration 4. There are duplicate rows that contradict the new unique constraint. I get this error (sorry, it’s in French):

```
django.db.utils.IntegrityError: ERREUR:  n'a pas pu créer l'index unique « reversion_version_db_1aa3bc5d8084070f_uniq »
DETAIL:  La clé (db, content_type_id, object_id, revision_id)=(default, 31, 1054, 205095) est dupliquée.
```

I never did anything manual with django-reversion. I’ve been using it for 4 years on this project, and the only source of data creation in django-reversion tables is through the admin.
From what I see when I read the detail of the versions and the revision, the problem concerns an inline. An inline object was modified, but it seems the old and the new state of this inline object were linked to the revision of the main object. That’s why there is two times the same version for the same revision of the same object.

This is not an isolated case in the database, I removed hundreds of blocking cases like this, and the unique constraint still can’t be added.

I may have done something wrong without knowing it, but I can’t find it…

**Comment by etianen** [comment]
I suspect that some bug in a previous version of django-reversion has created some duplicate Version instances in some Revisions.

The solutions, I suspect, is to include a data migration that de-dupes these before applying the migration by deleting duplicate rows. Sound sensible?

**Comment by etianen** [comment]
You'll probably have to run the data migration I've added to 0003 manually, since your database will have already have applied it, and I can't create a new migration between 0003 and 0004. Once you've run the data migration in 0003, 0004 should apply just fine.

**Comment by BertrandBordage** [comment]
Thank you very much!
No worry, I didn’t apply 0003 in production, so I don’t even have to run this part manually :)

From what I see, you implemented `de_dupe_version_table` exactly the way I would have. I’m not totally sure which versions should be removed, but from what I saw in the few examples I checked, the most recent one seemed to be the one to keep.

So great job :)

**Comment by etianen** [comment]
Sorry for the initial cock-up! :P

**Comment by BertrandBordage** [comment]
No problem, you’ve done an outstanding work on django-reversion for years, you really don’t have to be sorry for the first issue I’ve spotted in years ;)
