### ISSUE TITLE
Problem with m2m through field

### ISSUE THREAD

**Issue by ashish2py** [etianen/django-reversion#538]
***master-branch*** : m2m through field throws an error while running,
```
./manage.py createinitialrevisions
```

and without m2m, ***createinitialrevisions*** works fine.

***error***
  _File "/project_path/models.py", line 39, in <module>
    class Person(models.Model):
  File "/project_path/reversion/revisions.py", line 390, in register
    m2m_changed.connect(_m2m_changed_receiver, sender=remote_field(field).through)
  File ".virtualenvs/project_env/lib/python3.5/site-packages/django/db/models/signals.py", line 39, in connect
    "Specified sender must either be a model or a "
ValueError: Specified sender must either be a model or a model name of the 'app_label.ModelName' form._

***sample code ***
```
@reversion.register()
class Person(models.Model):
    name = models.CharField(max_length=200)
    groups = models.ManyToManyField('Group', through='GroupMember', related_name='people')
    
    class Meta:
        ordering = ['name']
    
    def __unicode__(self):
        return self.name
    
@reversion.register()
class Group(models.Model):
    name = models.CharField(max_length=200)
    
    class Meta:
        ordering = ['name']
    
    def __unicode__(self):
        return self.name
    
@reversion.register()
class GroupMember(models.Model):
    person = models.ForeignKey(Person, related_name='membership')
    group = models.ForeignKey(Group, related_name='membership')
    type = models.CharField(max_length=100)
    
    def __unicode__(self):
        return "%s is in group %s (as %s)" % (self.person, self.group, self.type)
```

**Comment by etianen** [comment]
I think you need to specify your through argument as
"your_app.GroupMember". Could you try that and let me know if it works?

**Comment by ashish2py** [comment]
It doesn't work. 
In v2.0.0 reversion.py below code was not present.
```
def register(model):
    .......
    #Connect signals. v2.0.1
    post_save.connect(_post_save_receiver, sender=model)
    for field in opts.local_many_to_many:
        m2m_changed.connect(_m2m_changed_receiver, sender=remote_field(field).through)


def unregister(model)
    ......
    # Disconnect signals. v2.0.1
    post_save.disconnect(_post_save_receiver, sender=model)
    for field in opts.local_many_to_many:
        m2m_changed.disconnect(_m2m_changed_receiver, sender=remote_field(field).through)
```
I revert back to v2.0.0 and everything works!!

**Comment by etianen** [comment]
Cool, I'll try to get to the bottom of this tomorrow!

**Comment by etianen** [comment]
Could you try using the master branch of django-reversion? This should now be fixed.

A couple of other issues relating to custom through models have also been addressed.

**Comment by joaoponceleao** [comment]
Was having the same problem. Very quick check suggests master branch has fixed it. Thanks!

**Comment by etianen** [comment]
v2.0.3 is now out with the fix! Enjoy!
