### ISSUE TITLE
Why does Version.object_repr come from __str__ instead of __repr__

### ISSUE THREAD

**Issue by pembo13** [etianen/django-reversion#540]
I couldn't find a better forum to post this question. I had been setting up appropriate `__repr__` on models assuming that that was where `Version.object_repr` came from. But I see now, rereading the docs, that it comes from `__str__`. I'm curious as to the logic for that.

The ability to use `__repr__` instead would be nice.

**Comment by etianen** [comment]
Django uses the __str__ method of models all over the place, most notably
in the admin. The standard Django admin history view uses the stored
__str__ of the object in an object_repr field on the AdminAction model.
Django-reversion does the same thing on the Version model to build the
enhanced history view that replaces the built-in one.

Django doesn't use __repr__ anywhere, and uses __str__ to refer to and
describe individual model instances, and thus so does reversion.

__repr__ is only meant to create a string that is for programmer reference,
and is ideally also a valid Python expression. It's not for end users. A
good __repr__ for a model might be 'YourModel(name="foo"), and the
equivalent __str__ would just be '"foo"'. The first is for programmers, the
second is for users.

**Comment by pembo13** [comment]
Thanks for the explanation. I think I misunderstood the intent of `Version.object_repr`

**Comment by etianen** [comment]
No worries! Ideally it would be called object_str, but I just copied Django
core. :)
