### ISSUE TITLE
recoverlist_view displays all version of each deleted object

### ISSUE THREAD

**Issue by joseph2002** [etianen/django-reversion#544]
don't know whether this is a feature or bug.

**Comment by etianen** [comment]
It's a bug! :O

I'll attend to this first this next Monday.

**Comment by Egregors** [comment]
One more question: In previous version **reversion.get_deleted(model)** returns list of last versions (one for each model instance), but now I got many versions for each instance, by **Version.objects.get_deleted(model)**. Is it the same bug?

**Comment by etianen** [comment]
Yes, exactly the same bug.
