### ISSUE TITLE
deleterevisions management command -keep delete all revisions for objects with revisions count under -keep

### ISSUE THREAD

**Issue by dpaluch-rp** [etianen/django-reversion#545]
Hi, I found unexcepted behavior in deleterevisions command with --keep parameter.
It delete all revisions for objects with revisions_count under --keep

For example: if we run
`manage.py deleterevisions --keep 100
`
```
obj_id         revisions_count       deleted
1                 103                          3                
2                 23                            23       #
3                 432                          332
4                 100                          0
5                 99                            99       # 
```

**Comment by etianen** [comment]
Just to confirm - you're using django-reversion >= 2.0.0?

**Comment by etianen** [comment]
Managed to reproduce it using >= 2.0.0. Tested and fixed.

**Comment by dpaluch-rp** [comment]
@etianen Yes 2.0.2. Thank you.
