### ISSUE TITLE
Set comment with RevisionMixin?

### ISSUE THREAD

**Issue by washougal** [etianen/django-reversion#546]
I'm using the django rest framework, and have the RevisionMixins placed in a number of class views that are called through an API. The revision framework stores the revisions perfectly, including the user. I'm wondering if there is some way to set a comment using the RevisionMixin?

**Comment by etianen** [comment]
You can call any of the revision management API functions in your view code:

https://django-reversion.readthedocs.io/en/stable/api.html#revision-api

For example:

``` py
import reversion

class YourView(RevisionMixin, YourBaseView):

    def post(self, request):
        reversion.set_comment("foo bar")
        return super().post(request)
```

**Comment by washougal** [comment]
Maybe changing the [revision mixin docs](https://django-reversion.readthedocs.io/en/stable/views.html#reversion-views-revisionmixin) to show this is possible would be helpful?

```
from django.contrib.auth.views import FormView
import reversion
from reversion.views import RevisionMixin

class RevisionFormView(RevisionMixin, FormView):
    def post(request):
        reversion.set_comment('foo bar')
```

**Comment by etianen** [comment]
Done!
