### ISSUE TITLE
Misleading datetime in revert message. Easy fix.

### ISSUE THREAD

**Issue by tuttle** [etianen/django-reversion#547]
Reversion is a wonderful project, nevertheless I found a subtle bug.

The revert action saves the admin log message "Reverted to previous version, saved on <datetime>". When the `settings.USE_TZ = True`, then the code `localize(version.revision.date_created)` makes the timezone-aware datetime object nicely human readable, but cuts off the UTC timezone info.

I believe the fix is how Django renders the datetimes in templates: `localize(timezone.template_localtime(...)`. Thanks.

**Comment by tuttle** [comment]
:-) Isn't this one really a simple change to start a fork for it so I could give you a pull rq?

**Comment by arogachev** [comment]
Faced with the same issue. Any updates on this? Or maybe we can help with PR?

**Comment by arogachev** [comment]
@tuttle As a workaround, I sublassed `CompareVersionAdmin` and overrided `_reversion_revisionform_view` method where I changed datetime formatting to respect timezone using the method you suggested. I tested it, and it works.

But of course it will be better if it will be fixed in extension.

**Comment by tuttle** [comment]
@arogachev Thanks, Alex. :+1:
