### ISSUE TITLE
Error when trying to revert

### ISSUE THREAD

**Issue by frankmaina** [etianen/django-reversion#549]
Hi, i installed django reversion and i keep getting an error when i try to revert a model,

invalid literal for int() with base 10:

ValueError at /admin/models/model/4774/history/4774/manage/
invalid literal for int() with base 10: '4774/history/4774'
Request Method:	GET
Request URL:	http://127.0.0.1:8000/admin/models/model/4774/history/4774/manage/
Django Version:	1.8.12
Exception Type:	ValueError
Exception Value:	
invalid literal for int() with base 10: '4774/history/4774'
Exception Location:	C:\Python27\lib\site-packages\django\db\models\fields\__init__.py in get_prep_value, line 985
Python Executable:	C:\Python27\python.exe
Python Version:	2.7.11
Python Path:	
['C:\\Users\\User Path\\Desktop\\SOKO\\dev',
 'C:\\Python27\\lib\\site-packages\\mysql_python-1.2.5-py2.7-win32.egg',
 'C:\\WINDOWS\\SYSTEM32\\python27.zip',
 'C:\\Python27\\DLLs',
 'C:\\Python27\\lib',
 'C:\\Python27\\lib\\plat-win',
 'C:\\Python27\\lib\\lib-tk',
 'C:\\Python27',
 'C:\\Python27\\lib\\site-packages']
Server time:	Wed, 29 Jun 2016 16:20:14 +0300

**Comment by etianen** [comment]
How did you get to that URL? It's not a valid URL for django-reversion.

Can you also include the full traceback?

**Comment by frankmaina** [comment]
Umm sorry didn't reply to this earlier, turns out it was an issue in my own code not django reversion. But thanks for your help.

**Comment by etianen** [comment]
No worries! Glad it's working! :)
