### ISSUE TITLE
Revision not showing in admin when creating a revision for a followed relationship with the decorator

### ISSUE THREAD

**Issue by felix-d** [etianen/django-reversion#550]
Hi! First of all thanks for that awesome library.

*Note: tested with v1 and v2*

I have a model A and a model B with a foreign key relationship.

```python
@reversion.register(follow=['b'])
class A(models.Model):
    pass

@reversion.register()
class B(models.Model):
    a = models.ForeignKey(A)
```

When modifying an inlined instance of `B` in `A` ModelAdmin from the admin panel, I can see the revision in `A` instance admin page history tab.

When creating a revision with `@reversion.create_revision()` decorator and update an instance of `B`, the revision is not showing in the `A` instance admin page history tab.  

I tried to see what revisions are created from the shell when I use the decorator and it seems the revision for the `B` instance is created but not the revision for `A`, hence why it is not showing in the admin page.

If I do the modification from the admin page, the revision for `A` is created as it should.

Am I forgetting something?

**Comment by etianen** [comment]
If you're using the admin integration, then the registration will be done automatically to follow the inlines. No need to manually call reversion.register!

However, if you want to do it manually, what you want is:

``` py
@reversion.register(follow=['b_set'])
class A(models.Model):
    pass

@reversion.register(follow="a")
class B(models.Model):
    a = models.ForeignKey(A)
```

That is, you specify the name of the attribute on the model that represents the relationship.

**Comment by felix-d** [comment]
Thanks @etianen!

It worked when I added both. 

1. If I only used the admin integration, then the decorator would not create the revision of `A` when editing an instance of `B` attached to it, but it would be created if I edited inlines.

2. If I only used the manual registration, strangely the same happens! The history shows in the admin panel but only the modifications created when editing inlines show.

3. When using both, the history entries finally show as they should.

**Comment by etianen** [comment]
Hmm, are you sure about that? The VersionAdmin autoregistration only kicks in if the model isn't already registered with reversion.

What registration code are you using? Is it the one from my previous comment?

``` 
@reversion.register(follow=['b_set'])
class A(models.Model):
    pass

@reversion.register(follow="a")
class B(models.Model):
    a = models.ForeignKey(A)py
```
