### ISSUE TITLE
Get rid of AUTH_USER_MODEL

### ISSUE THREAD

**Issue by GuillaumeCisco** [etianen/django-reversion#551]
Is there a way to get Rid of AUTH_USER_MODEL for dealing with user.
I explain my situation : I'd like to conserve an django admin where I can create super users who can manage admin.
But I'd like to use a simple custom Model for setting the user of the reversion.
Something as simple as :
```
class ProxyUser(models.Model):
    username = models.CharField(max_length=32, unique=True)
    class Meta:
        app_label = 'prototype'

    def __unicode__(self):
        return '%(username)s' % {'username': self.username}
```

Aim is to use a different model for dealing with user who create reversions.
And manage the creation of the reversion internally by `get_or_create` users using request.META custom HTTP.

Thank you,

**Comment by GuillaumeCisco** [comment]
I've made a Pull request for dealing with this issue.
Simply using a custom setting REVERSION_USER_MODEL will do the trick ;)
All details in pull request.
https://github.com/etianen/django-reversion/pull/552

**Comment by etianen** [comment]
Response copied from #552 for reference:

If you want to associate a non-admin user model with a revision, consider using the add_meta() feature:

https://django-reversion.readthedocs.io/en/stable/api.html#revision-api

**Comment by GuillaumeCisco** [comment]
Hello @etianen and thank you for your quick response!

Unfortunately `add_meta()` feature does not solve the problem, it's completely different.
And this feature will not break the admin integration, revision middleware and revision view helpers.
It is intended to change it.

The key here is to have access to the django admin like before by creating some admin, moderators users via django auth and to store users that change history but are not in the django auth table.

Today, a lot of new authentication process exist. For example, we use in our project a micro services oriented architecture using a gateway.This gateway identifies users with jwt token.

So I 'd like to be able to create super users on this specific service for dealing with django admin, and allow some users without asking them to identify using an email password.
Indeed, the gateway already authenticated them for me and I receive the information via custom HTTP Headers (jwt for example).
I don't need theses users to authenticate via django auth. The only thing I want is to store in a custom User model independently from AUTH_USER_MODEL their data, and set my revisions in custom wrappers.

I don't want these users (usually team members) to be recreated in an other table with django auth as they already exist in another service. All I want is a new table with fewer data (typically id and username) and if I want more information, I can make a call to my login service.

I hope this use case is pertinent enough for considering integrating this feature :)
Maybe we can describe the whole use case in the docs for avoiding misunderstanding.

Thank you,

**Comment by etianen** [comment]
Thanks for the explanation.

I still think that you can support this entirely using add_meta().

``` py
# models.py

class SimpleUserRevisionMeta(models.Model):
    revision = models.OneToOneField(Revision)
    simple_user = models.ForeignKey(SimpleUser)

# views.py

def your_view(request):
    reversion.add_meta(SimpleUserRevisionMeta, simple_user=request.get_simple_user())
```

The end result is that you associate a different user model with the revision, and leave Revision.user as null.

I mean, it would be possible to implement the existing user and comment tagging using a custom meta model, so it should therefor be possible to implement your feature with it too.

I think your pull request would break the VersionAdmin and RevisionMixin because these both set the revision user to request.user, which is going to be AUTH_USER_MODEL.

**Comment by GuillaumeCisco** [comment]
Thank you again @etianen for this quick reply!!

I've just tried your solution and it work like a charm. Only drawback, it creates a new table in the database.
Regarding,  `VersionAdmin` and `RevisionMixin`, I did not dig in these methods/Classes and have a total trust in you if you think it can be broken with my PR.
Also, I'd like to bring attention on the `add_meta` feature. I totally missed it... twice... even when you point it out to me. Only your code example helped me understand.
I think this feature need more light, maybe a complete use case in the doc, regarding the user use case. As you mention it, we have to leave the Revision.user to None, but it is not the default behavior (Anonymous User).

So I change my code (using my PR) from:
```
with reversion.create_revision():
            user, created = ProxyUser.objects.get_or_create(username=self.context['request'].META['HTTP_X_CONSUMER_USERNAME'])
            reversion.set_user(user)
            reversion.set_comment('my comment')

            # do instance saving...
```
to: with classic code and `ProxyUserRevisionMeta` (Class alike you described)
```
with reversion.create_revision():
            user, created = ProxyUser.objects.get_or_create(username=self.context['request'].META['HTTP_X_CONSUMER_USERNAME'])
            reversion.add_meta(ProxyUserRevisionMeta, simple_user=user)
            reversion.set_user(None)
            reversion.set_comment('my comment')

            # do instance saving...
```

Hope it will help others ;)
Cheers :+1: :tada: :tada: :tada:

**Comment by etianen** [comment]
Phew! Glad it works.

I've only just done a huge refactor of the docs, but I intend to do a
second pass through soon and will add this extra info in.
