### ISSUE TITLE
Standardize on JSON serialization format

### ISSUE THREAD

**Issue by etianen** [etianen/django-reversion#557]
- [ ] Use JSONField for serialization of data in Postgres.
- [ ] Remove `serialization_format` column.

Pros:
- Faster deserialization in postgres.
- Allows querying the serialized data in postgres.

Cons:
- High storage overhead (binary JSON takes up more disk space than text!)
- Some people like non-JSON serialization format, for some reason.
- A fairly expensive database migration for people using JSON serialization.
- An incredibly expensive database migration for people using non-JSON serialization.
- This would require a v3.0.0 release of django-reversion.

**Comment by danielsamuels** [comment]
It's worth noting that 1.8 LTS is going to be supported for at least another 2 years and `JSONField` wasn't added until 1.9, so this might have to wait until the 1.8 LTS ends.

**Comment by etianen** [comment]
A good point. This isn't an urgent feature, by any means.

**Comment by eronlloyd** [comment]
Is it possible to make this an option now, while not yet the default? How is JSON currently stored?

**Comment by etianen** [comment]
JSON is currently stored as a TextField, which makes it pretty impossible to query effectively.

Then again, in postgres, you could query it by using custom SQL and casting the field to json. That would let you use all the JSON operators. It would be slow, but querying over JSON is going to be slow anyway.

**Comment by etianen** [comment]
Hmm, in fact, the more I think about it, the less this seems like a good feature.

- You can already do JSON lookups in postgres using custom SQL. All this feature would add is the ability to use Django's JSON database operators.
- Binary JSON takes up more disk space, and django-reversion is already a disk hog.
- Querying binary JSON is still very slow, unless you add a GIST index. Adding a GIST index will make it take up even more space on disk!

**Comment by sliverc** [comment]
I would also love to see data be stored as json field mainly to be able to query json data easily.

As django-reversion should work on other databases then postgresl it is going to be tricky to support `JSONField` for Postgres but fall back to `TextField` on other databases in the current state of Django.

This [discussion](https://groups.google.com/forum/#!topic/django-developers/zfred27yVPg) might be of interest whereas a generic json field in Django would make life easier and more consistent.

**Comment by MRigal** [comment]
@etianen now that Django 3.2 brings json storage support to all databases, the time might has come to allow this to happen! :-)

**Comment by etianen** [comment]
I'm in two minds. A lot of people have huge reversion databases, and the migration to support this will take hours and hours to run. That seems risky IMO.

Ignoring that, while storing as JSON allows deep querying in some databases, the performance will be unusable in large reversion databases.

So I'm not sure there's a use case for it!

**Comment by MRigal** [comment]
I see your point! However it happens to me to be looking for something and I have to filter as much as possible based on other parameters (date mostly) but I sometimes do need to search for some particular data and then this would be a huge benefit.
But indeed, it is such a change that it is almost a fork worth...

**Comment by etianen** [comment]
You can already filter on the JSON data, but you need to use RawSQL to do
so. And it won't be fast. But even using a dedicated JSONField won't be
fast. So what this really comes down to is:

Do we introduce a huuuuuuge migration and a backwards-incompatible change
to make a rare use-case easer and slightly more performant?

That just doesn't sound worth it to me.

**Comment by MRigal** [comment]
I'm already doing it using `filter(json_data__contains="foobar")` and it works fine. No need for RawSQL! But it's not super fast, for sure!

As said before I fully understand the decision! I think you could add a note on the decision to the docs and then close the issue

**Comment by etianen** [comment]
Closing this issue as it's, on reflection, a bad idea.
