### ISSUE TITLE
Disable reversion for non-superusers

### ISSUE THREAD

**Issue by mick88** [etianen/django-reversion#560]
I'm working on a scenario where staff users can access filtered subset of data in django admin, but Reversion still allows those users restore deleted instances of models they should now have access to. 
In essence, reversion allows user to restore deleted objects as long as user has change permission on the model, but does not seem to respect any object-level permission. 
I think the easiest solution would be to disable reversion for non-superuser users.

**Comment by etianen** [comment]
You can do this by overriding the various revision views, checking for the
user's access permission, and raising a PermissionDenied if they don't have
superuser permission. You'd also need to disable the buttons in templates
for non-superusers.

This doesn't belong in reversion, as it's a pretty specific use-case.
