### ISSUE TITLE
Improve RevisionMiddleware behavior

### ISSUE THREAD

**Issue by spapas** [etianen/django-reversion#562]
Hello, one nice enchancement for the ``RevisionMiddleware`` would be to add the path info on the revision.comment field (which is usually left empty). From what I see this is rather easy (just inherit from ``RevisionMiddleware`` and add a ``set_comment(request.path)`` in the ``process_request`` method of yout custom middleware. However, because of how ``RevisionMiddleware`` is implemented, you'll need to copy the whole ``process_request`` method to override it. 

Instead, I propose to use an optional ``set_comment(self, request)`` method at ``RevisionMiddleware`` - if this method is defined in a middleware extending ``RevisionMiddleware`` then its output will be saved as this revision's comment.

**Comment by etianen** [comment]
How about just subclassing `RevisionMiddleware` like this:

``` py
class SuperDuperRevisionMiddleware(RevisionMiddleware):

    def process_request(self, request):
        super().process_request(request)
        if reversion.is_active():
            reversion.set_comment(request.path)
```

**Comment by spapas** [comment]
Works great , thanks ! Didn't know I could do it after the ``process_request`` had finished!
