### ISSUE TITLE
Add distinguishing context variable to the recover/revision view contexts

### ISSUE THREAD

**Issue by kezabelle** [etianen/django-reversion#564]
For reasons which are somewhat convoluted, I have a need to know within the context which change form may be being rendered, but I cannot see a way of doing so without overriding the appropriate views to pass along extra context at every modeladmin necessary.

Would it be feasible to update the context given to `_reversion_revisionform_view` to include unique keys saying who the original caller is, i.e:

```
context.update(extra_context or {})
context.update(revision_view=True)  # or recover_view=True
```

**Comment by etianen** [comment]
You can do this yourself by subclassing VersionAdmin, and overriding
revision_view and recover_view, adding the appropriate keys to
extra_context. That should probably cover your use-case.

**Comment by kezabelle** [comment]
Hiya etianen. Thanks for taking the time to respond.
Yeah, that's actually what I was trying to avoid doing (and what I was badly alluding to with: `overriding the appropriate views to pass along extra context at every modeladmin necessary.`). I figured that ModelAdmin itself already sets the precedent for distinguishing context vars with `add` and `change` and thought perhaps you'd be amenable to it. 

I have managed a workaround without touching extant modeladmins, but its grotty because it involve slicing the start of the context `title` and comparing it to a `ugettext` string of "Revert" or "Recover" so I'm not sure how well it'd hold up in a i18n scenario, but it works well enough for my purposes for now.

I'm happy for you to close this down if you don't want to burden yourself with supporting potentially unnecessary code :)

**Comment by etianen** [comment]
I had a quick scan of the Django source code, and couldn't see where
passing along "add" and "change" is done. If there's a precedent, I'm happy
to continue it.

Otherwise, you should only need to subclass VersionAdmin once, then use
that subclass in all your other ModelAdmins.

**Comment by kezabelle** [comment]
`add` is defined in `changeform_view` [here](https://github.com/django/django/blob/master/django/contrib/admin/options.py#L1421) and the distinguishers (for *state*, rather than *view*, but principally accomplishes the same) are added to the context in `render_change_form` [here](https://github.com/django/django/blob/master/django/contrib/admin/options.py#L1040-L1041).

Within the revision/revert views, these are always `add=False, change=True` as far as I can see. While conceptually for revert it might actually make more sense for both `add/change` to be `False`, there is probably already style/template changes in the wild which work based on the value of those being what they are (because after all the reversion views re-use the extant changeform view) so by adding `revert/revision=True` to the context available, you're enabling further refinement both at the template level, and at the subclass and middleware levels by doing different things based on what's in the `TemplateResponse` context data, potentially before it is rendered. I can't say whether anyone would actually want such a thing (other than me) though.

**Comment by etianen** [comment]
I think a `recover` key and a `revert` key could be added to the context.
I'd be happy to take a pull request to that effect.
