### ISSUE TITLE
References to rersion.revision.user.pk do not work when used in a template {% url %} tag

### ISSUE THREAD

**Issue by Jaxkr** [etianen/django-reversion#567]
For example
`{% url 'profile' version.revision.user.pk %}`

This throws `Reverse for 'profile' with arguments '('',)' and keyword arguments '{}' not found.` This is **really** strange.

When I reference the variable directly `{{ version.revision.user.pk }}` it works fine, but it breaks and returns and empty string when used in a url tag. This only happens with references to reversion, and the url tag for this path works with any other variable. I have used a hard coded url with a direct reference to the variable as a temporary workaround, but it's not very django-style to do that.

Curious if this behavior is the same on your side.

**Comment by etianen** [comment]
I suspect that one of your revisions does not have a user, so user.pk
breaks for that particular url tag.

Try using version.revision.user_id instead. That won't error and break the
tag if the user model is not present.

Or, use:

{% if version.revision.user %}{% url 'profile' version.revision.user.pk
%}{% endif %}
