### ISSUE TITLE
with reversion.create_revision() and my_model.objects.select_related('XXX').update_or_create

### ISSUE THREAD

**Issue by murdav** [etianen/django-reversion#570]
Hello,

This is the code:

```
@transaction.atomic
def my_func():
    """
    """

    #
    # calculate obj
    # calculate obj_dict for update_or_create defaults 
    #

    with reversion.create_revision():
        my_instance, created = my_model.objects.select_related('type')\
                                         .update_or_create(title=obj.title,
                                                           defaults=obj_dict)

        reversion.set_user(user)
        reversion.set_comment("Created revision {0}".format(datetime.now()))
```

The revision is not saved, but within update_or_create we have obj.save. 
Anyway I don't have any error.
Is there any issue having the decorator @transaction.atomic? 

Using the Django admin everything works.
Thanks,

D

**Comment by etianen** [comment]
Using transaction.atomic() isn't usually necessary, since
reversion.create_revision() will also wrap the contained code in a
transaction. However, it won't do any harm having it twice.

Is my_model registered with django-reversion?

**Comment by murdav** [comment]
Dear Author,
Yes, the model is registered using the Version decorator, and using the Django admin it works.
I need to have the transaction decorator for other issues.

**Comment by etianen** [comment]
Out of interest, does replacing the `update_or_create` code with `my_model.create(title=obj.title, **obj_dict)` work?

I'm wondering if update_or_create always calls save(), when the model is updated.

**Comment by murdav** [comment]
Dear @etianen,

I tried with:

```
@transaction.atomic
def my_func():
    """
    """

    #
    # calculate obj
    # calculate obj_dict for update_or_create defaults 
    #

    with reversion.create_revision():
		# just to test I did this
		f = MyModel.objects.create(url='http://test.com', title='test rev', inserted_by=user)

        reversion.set_user(user)
        reversion.set_comment("Created revision {0}".format(datetime.now()))

	my_instance = MyModel.objects.latest('created')
```

But without having success, I got the same app behavior, basically no revision was added, while my_instance is correctly retrieved and used in other parts of the function.

Do you have further ideas?
I will try other tests later.

D

**Comment by etianen** [comment]
Hrm....

I don't really know what to say. The exact same code is used in the admin
interface.

Try this inside that function:

print(reversion.is_registered(MyModel))

**Comment by murdav** [comment]
It returns True. I suppose it is somehow related to have `@transaction.atomic` also if the Django doc says: "atomic blocks can be nested." there is something that creates troubles.
Or maybe it's a combination of issues, I'm having problems with Taggit (https://github.com/etianen/django-reversion/issues/76) also if I didn't change/dd/delete the keywords and I also have this bug using JSONField (https://code.djangoproject.com/ticket/25532) each time I save a model using the JSONField it adds slashes.
....

**Comment by etianen** [comment]
I think something has gone a bit wrong somewhere, probably in your code,
but maybe not.

Time to debug! Try adding loads of print() statements in the reversion
codebase to pin down whether django-reversion is actually being triggered
by the model's post_save signal.

**Comment by stevekm** [comment]
Was there a solution to this? I am seeing the same behavior, where a call to 

```
    with reversion.create_revision():
        instance, created = MyModel.objects.update_or_create(sample = sample, defaults = values)
```

results in the model instance being updated successfully in the database, but reversion does not record a change or new version.

**Comment by etianen** [comment]
Does it work if you use `MyModel.objects.create()` instead?

**Comment by stevekm** [comment]
It works if I use `.create()` but that forces me to re-write the logic bundled into `update_or_create()` which I wanted to use

**Comment by etianen** [comment]
I'm afraid this is a mystery to me. Looking at the source code for
update_or_create, it seems to delegate to Model.objects.create() or
Model.save(), both of which should trigger a revision.

If you can get to the bottom of this, I'd take a MR to fix it.
