### ISSUE TITLE
`post_revision_commit` is not perfectly replaceable by `post_save` of `Revision`

### ISSUE THREAD

**Issue by carlosxl** [etianen/django-reversion#571]
Saw the `post_revision_commit` signal is removed in 2.0 release. The suggested way is to replace the existing `post_revision_commit` with `post_save` of `Revision`.

However, there is a difference that with `post_revision_commit`, the `versions` objects have already been saved to db whereas with the `post_save` of `Revision` they are not.

Got a hard time migrating from 1.9 to 2.0 because of this issue. Any suggestion?

**Comment by etianen** [comment]
Use the post_commit hook in transactions? That's generally a much better
place for post_save behaviour when the side-effects do not involve
modifying the database.

Use the post_save signal of Version?

I see your point though, and would not be adverse to putting the signal
back in if there's no alternative.

**Comment by lxiang-visualsquares** [comment]
Thanks for the suggestions!

The post_commit or on_commit hook feels like to have a more generic purpose.

On the other hand, we do have a use case in which multiple Versions are created inside a single Revision and we want to wait until all the versions are saved.

In my case, I think the `post_revision_commit` is still valuable if the user want to perform some tasks that assume the `revision` and all its related `versions` have been saved to db.

**Comment by carlosxl** [comment]
Thanks for the suggestions!

The post_commit or on_commit hook feels like to have a more generic purpose.

On the other hand, we do have a use case in which multiple Versions are created inside a single Revision and we want to wait until all the versions are saved.

In my case, I think the post_revision_commit is still valuable if the user want to perform some tasks that assume the revision and all its related versions have been saved to db.
