### ISSUE TITLE
Django 1.10 incompatibility

### ISSUE THREAD

**Issue by KhasanovBI** [etianen/django-reversion#573]
Hey,

I just upgraded Django to 1.10, and here's the error:
Internal Server Error: /api/login/
```
Traceback (most recent call last):
  File "/Users/b.khasanov/Envs/intranet/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Users/b.khasanov/Envs/intranet/lib/python2.7/site-packages/django/core/handlers/base.py", line 244, in _legacy_get_response
    response = middleware_method(request)
  File "/Users/b.khasanov/Envs/intranet/lib/python2.7/site-packages/reversion/middleware.py", line 24, in process_request
    _set_user_from_request(request)
  File "/Users/b.khasanov/Envs/intranet/lib/python2.7/site-packages/reversion/views.py", line 10, in _set_user_from_request
    if hasattr(request, "user") and request.user.is_authenticated():
TypeError: 'bool' object is not callable
```
In django1.10 is_authenticated is property.

**Comment by etianen** [comment]
Are you using a custom user model? The docs seem to indicate that is_authenticated will continue to work as a method for the time being: https://docs.djangoproject.com/en/1.10/releases/1.10/#using-user-is-authenticated-and-user-is-anonymous-as-methods

**Comment by KhasanovBI** [comment]
Yes, you right, thanks. But for future I think it makes sense to make the compatibility for the future. If you don't mind, I'll do pull request.

**Comment by GuillaumeCisco** [comment]
I have an issue too, but really weird :/
Don't understand where it comes from.
When I try to create an object from django rest framework with their Browsable API, I get:
```
 ... object has no attribute '_deferred'
```

**Comment by etianen** [comment]
@GuillaumeCisco - I don't think that this is a django-reversion error. I suspect that you're using an incompatible version of django-rest-framework and django.

**Comment by GuillaumeCisco** [comment]
@etianen Thank you for your time.
Just retested it with django 1.10.2 and djangorestframework 3.4.7.
The issue was still here.
The issue was with the django-model-utils dependency version 2.5, just upgraded to 2.6 and it works fine.
Sorry for the inconvenience.

**Comment by etianen** [comment]
No probs! :)
