### ISSUE TITLE
Setting db connection for django reversion

### ISSUE THREAD

**Issue by omago** [etianen/django-reversion#577]
Hi,

I would like to have two database connections to two different databases. 
Like this:

```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',   # Add 'postgresql_psycopg2', 'mysql', 'sqlite3' or 'oracle'.
        'NAME': config.db_name,                 # Or path to database file if using sqlite3.
        # The following settings are not used with sqlite3:
        'USER': config.db_username,
        'PASSWORD': config.db_password,
        'HOST': config.db_host,                 # Empty for localhost through domain sockets or '127.0.0.1' for localhost through TCP.
        'PORT': config.db_port,                 # Set to empty string for default.
    },
    'audit': {
        'ENGINE': 'django.db.backends.mysql',   # Add 'postgresql_psycopg2', 'mysql', 'sqlite3' or 'oracle'.
        'NAME': "wms_audit",                 # Or path to database file if using sqlite3.
        # The following settings are not used with sqlite3:
        'USER': config.db_username,
        'PASSWORD': config.db_password,
        'HOST': config.db_host,                 # Empty for localhost through domain sockets or '127.0.0.1' for localhost through TCP.
        'PORT': config.db_port,                 # Set to empty string for default.
    }
}
```

Is it possible to configure django reversion to use "audit" connection instead of "default?

Best,
Domagoj

**Comment by etianen** [comment]
Almost all of the reversion API methods take a `using` parameter, to set the database to store revision data:

https://django-reversion.readthedocs.io/en/stable/api.html

**Comment by omago** [comment]
I am not sure am i missing something but i don't see that register method is receiving "using" or "db" or something like that. I see i have a create_revision  method but i am not creating revisions manually. I just register my model and thats it.

**Comment by etianen** [comment]
You can set up a database router to map the Revision and Version models to
the "audit" db by default:

https://docs.djangoproject.com/en/1.10/topics/db/multi-db/#using-routers

**Comment by omago** [comment]
Thanks etianen, this looks promising.

**Comment by etianen** [comment]
Be advised that the user model will also need to be in the same db for foreign keys to work!

**Comment by omago** [comment]
This was actually very easy to do. I was able to remove reversion tables to different database. I just removed foreign key so my integrity could be broken but this is not a very big issue at the moment.

**Comment by djpretzel** [comment]
@omago How did you get this working? 

When I go to createinitialrevisions, it complains that django_content_type doesn't exist in the separate audit database.

I copied that table over just to fix the problem, but then it started complaining about my user table also not existing.

I've removed the foreign keys at the database level - do I need to remove them somewhere else?

**Comment by Eieyron** [comment]
Hello! I am now encountering the same problem, but the foreign keys that i have are very much needed for the models -- i cant just simply remove them. Has anyone found a work-around for this yet?

**Comment by Eieyron** [comment]
As [Django docs](https://docs.djangoproject.com/en/1.10/topics/db/multi-db/#no-cross-database-relations) say, implementation of reversion with different databases cannot be fully implemented with foreign keys because Django doesn't support "foreign key or many-to-many relationships spanning multiple databases".
