### ISSUE TITLE
get_for_model does not exist

### ISSUE THREAD

**Issue by nipuniitg** [etianen/django-reversion#582]
I'm trying to run the below command:
**Version.objects.get_for_model(Schedule)**

But it gives me the below error:
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'ManagerFromVersionQuerySet' object has no attribute 'get_for_model'

**Comment by etianen** [comment]
I don't think you're using the latest version of django-reversion.

Try updating using pip install -U django-reversion.

**Comment by nipuniitg** [comment]
Thank you etianen :) 
It works after upgrading.
