### ISSUE TITLE
ignore_duplicates=True ignores changes in related models

### ISSUE THREAD

**Issue by arogachev** [etianen/django-reversion#583]
I have `Enterprise` model and related `ContactPerson` and `Phone` models:

``` python
@reversion.register()
class Enterprise(models.Model):
    # ...

@reversion.register()
class ContactPerson(models.Model):
    enterprise = models.ForeignKey(Enterprise, on_delete=models.CASCADE)
    # Other fields

@reversion.register()
class Phone(models.Model):
    enterprise = models.ForeignKey(Enterprise, on_delete=models.CASCADE)
    # Other fields
```

In both backend and frontend, these related models are edited together with `Enterprise` using formsets. For example in admin I define inlines like this:

``` python
class EnterpriseAdmin(CompareVersionAdmin):
    inlines = [ContactPersonInline, PhoneInline]
```

Changes of related models are tracked with main model (`for_concrete_model=True` and it's `True` by default, I haven't changed it).

if I set `ignore_duplicates=True` to main model:

``` python
@reversion.register(ignore_duplicates=True)
class Enterprise(models.Model):
    # ...
```

it works fine, but when I change any of related models (`ContactPerson` or `Phone`), their changes not detected and new revision is not created.

**Comment by arogachev** [comment]
I checked `reversion_revision` table the database and saw that revision with related versions was actually created, but for some reason it's not displayed in history for that object. It's weird. By the way, I use django-reversion together with [django-reversion-compare ](https://github.com/jedie/django-reversion-compare) extension, but as far as I know, it does not modify this list in any way.

**Comment by etianen** [comment]
ignore_duplicates works by excluding a model from the revision if it's
content hasn't changed from the previous revision. It doesn't follow
relations, as that can get expensive and slow very quickly.

**Comment by Sinkler** [comment]
Hello! If you read the issue you probably want to ignore duplicates for follow relations. May be this answer on Stackoverflow can help you:

https://stackoverflow.com/a/50390432/5157209

But one more time: be careful with it 😉
