### ISSUE TITLE
Editing last revision - equals regular changing?

### ISSUE THREAD

**Issue by arogachev** [etianen/django-reversion#585]
When editing last revision, maybe it should be equal to just changing the object since we dealing with the latest actual values? During moderation done by site admin users it's also a bit ambiguous and uncomfortable to open separate tab for change after comparing two revisions in history and make changes there. Maybe use link for change?

However, the values can be changed by SQL query for example and as a result revisions will not be created, so in that case editing last revision indeed means recovering.

Related: #584.

**Comment by etianen** [comment]
Reversion was never made to be a moderation queue. It's a rollback and
recovery system. I guess it could be used for moderation, but it's going to
be a bit awkward.

Like you say, the last revision isn't always exactly the same as the
current values in the database. Why are your users editing the last
revision. That's unusual behaviour.

**Comment by shtalinberg** [comment]
django==1.8.16, reversion=2.0.7    MySQL   DB
When I see reversions history in admin  (just see), it's automatic select (and save) viewed version.

**Comment by shtalinberg** [comment]
I comment  #'reversion.middleware.RevisionMiddleware',  -  did not help

**Comment by shtalinberg** [comment]
Now I disable this app. 
It's critical bug and we lost data with related via foreign keys and restore from backup. 
I can help with any trace or debug information ?

**Comment by arogachev** [comment]
@shtalinberg It's not clear what's your problem. Are you sure it's related to this issue?

**Comment by shtalinberg** [comment]
If I view reversions history in admin any revision - this revision auto-restore. 
Maybe it's not related to this issue...  Sorry. I add new. #600
