### ISSUE TITLE
[feature request] Permissions for the admin

### ISSUE THREAD

**Issue by olivierdalang** [etianen/django-reversion#588]
Hi,

I see this matter has already been suggested (#560  #287), but would like reopen the case. I think having a specific permission to restore versions would be a great improvement.

It has been argued that restoring a version is basically the same than editing an entry. That's technically right, but it's quite more complex from an user point of view, when there are inlines, complex widgets, or specific business logic behind the edits. 

Here at least, we have some users that are only quickly trained to enter some data, and some other users that are better trained for more complex administrative tasks. I have to choose between disabling VersionAdmin altogether, or hoping un-trained users won't click on the history button to mess around with old versions.

I think a restore_revision permission would fit perfectly in the app. I don't know the code base, but am pretty sure it would be very easy to implement. Of course I could implement it here, but if there's no way this is going to land in master, it's not very encouraging.

Thanks for the awesome work !

**Comment by olivierdalang** [comment]
Alternatively, an admin for Revisions could be provided, with an action to restore the Versions from the admin. That would be even less work, and would allow to fine-grain access to revisions.

**Comment by etianen** [comment]
Would you see this permission as per-model (e.g. restore_user, revert_user), or as a site-wide permission?

The latter would be much easier to do.

This couldn't be added as a default, but a subclass of RevisionAdmin could be created to support the functionality.

**Comment by olivierdalang** [comment]
Of course per model would be much more flexible.

**Comment by tom-zeit** [comment]
+1

**Comment by TomRaz** [comment]
In my use case we wanted to disable all reverts on a specific model, so i implemented this class that extends the VersionAdmin:
```

from reversion.admin import VersionAdmin

class RevertNotSupportedValidationException(Exception):
    pass


class ReadonlyReversionAdmin(VersionAdmin):
    def _reversion_revisionform_view(self, request, *args, **kwargs):
        if request.method == "POST":
            raise RevertNotSupportedValidationException("Revert is not supported for this model")
        return super()._reversion_revisionform_view(request, *args, **kwargs)

```

Using it instead of the VersionAdmin will disable the revert on the model.

**Comment by OndrejIT** [comment]
Here is my solution...

https://gist.github.com/OndrejIT/72b6e458514c1e7615643f8d9ea3f08c
