### ISSUE TITLE
Signals importing error

### ISSUE THREAD

**Issue by cyberbudy** [etianen/django-reversion#590]
I've installed the last version of package and trying to import settings from reversion, but getting error: 
Module 'reversion' has no attribute 'post_revision_commit'
There is signals.py in master branch but not in last releases

**Comment by etianen** [comment]
Hmm? How did you resolve this?

**Comment by cyberbudy** [comment]
I've found in release notes your recommendations to use post_save and it instead. Its not so suitable for my case but I can live with this

**Comment by etianen** [comment]
Try installing from the master branch:

http://django-reversion.readthedocs.io/en/latest/changelog.html

The signals were added back in, due to popular demand. :)

**Comment by cyberbudy** [comment]
Ок, thanks
