### ISSUE TITLE
Not all objects saved when delete event occured

### ISSUE THREAD

**Issue by Novarg** [etianen/django-reversion#591]
Story: when i'm deleting few instances of the same class not all data saved in reversion. 
reversion 1.6.6 (i know it is not supported but maybe you could point me why this can happens?).  

Inside the `end` method of `RevisionContextManager` 
```python 
    def end(self):
        """Ends a revision for this thread."""
        self._assert_active()
        self._stack.pop()
        if not self._stack:
            try:
                if not self.is_invalid():
                    # Save the revision data.
                    for manager, manager_context in self._objects.iteritems():
                        manager.save_revision(
                            dict(
                                (obj, callable(data) and data() or data)
                                for obj, data
                                in manager_context.iteritems()
                            ),
                            user = self._user,
                            comment = self._comment,
                            meta = self._meta,
                            ignore_duplicates = self._ignore_duplicates,
                            db = self._db,
                        )
            finally:
                self.clear()
```

When reversion build this dict
```python 
 dict(
     (obj, callable(data) and data() or data)
     for obj, data
            in manager_context.iteritems()
 ),
```
not all data saved there because the same keys of that dict replaced by different objects. It happens because apparently equality check completes successfully for non equal objects! I'll illustrate with dumb code that i put inside `end` method:

```python
for obj in manager_context.keys():
    for obj2 in manager_context.keys():
        if obj == obj2 and obj is not obj2:
            print 'error: %s == %s' % (obj, obj2)
```
This code prints when 2 non equal objects (django models) are equal by == check, but this is totally wrong (that objs haven't overloaded any magic methods that can influence on comparison): 
```
error: 14@delme3.com == 15@delme3.com
error: 15@delme3.com == 14@delme3.com
```

How that can happens? Any ideas where to digg?

**Comment by etianen** [comment]
I'm afraid that code is from so long ago, I haven't the foggiest.

django-reversion stopped tracking the delete event because some of the behaviour it implied was inconsistent. I'd strongly recommend upgrading to a recent release.
