### ISSUE TITLE
user not saved when using middleware

### ISSUE THREAD

**Issue by sennierer** [etianen/django-reversion#592]
Hi,

I use the middleware to store revisions. Since my upgrade to 2.0.6 (Python 3.5.2 and Django 1.9.10) the users are not saved to the revision anymore. The revisions and models are saved correctly, but the user is not attached. It still works fine when I use `with reversion.create_revision()` in a view (or the shell).

**Comment by etianen** [comment]
Could you try using the master branch, and see if it solved your issues?

**Comment by sennierer** [comment]
No, that didnt help. As I said in my initial post we still use Django 1.9(.10). Might this cause the problem? I also checked that when we change an entity in the admin backend (we normally dont use the admin backend to alter the entities) the user is also not saved.

**Comment by sennierer** [comment]
I also tried to upgrade to the latest Django (1.10.2). Didnt help either. Not in the django admin backend and not via our normal forms.

**Comment by sennierer** [comment]
Hi. Tried around a bit and realized that when I move the reversion middleware to the very end of my list of middlewares it adds the users correctly again. Thanks.

**Comment by etianen** [comment]
Ah, so it's a middleware order thing. Phew!

**Comment by sennierer** [comment]
Yes ;). But I did not change the order since upgrading. So apparently earlier versions didnt bother.

**Comment by martinmaillard** [comment]
Same problem here. I think the issue comes from the fact that, in django-reversion 1.X, the user was set on the revision in `ReversionMiddleware.process_response`. It is now set in `ReversionMiddleware.process_request`.

If you happen to handle authentication somewhere else than a middleware (or in a middleware defined after `ReversionMiddleware`), the user is not going to be available on the request during `process_request`. In my case I use django-rest-framework, which handles authentication as part of the view lifecycle, so there is no way to make the user available on the request during `handle_request`.

**Comment by etianen** [comment]
Ah, in that case, it should be an easy fix to simply set the revision user in process response!

**Comment by etianen** [comment]
See if the master branch solves the issue for you. :)

**Comment by martinmaillard** [comment]
This fix would work, but you first have to verify that a revision is active before setting the user. Master breaks for requests that don't create a revision (GET, etc.)

**Comment by etianen** [comment]
Duh duh duh, of course. Will fix shortly.

**Comment by etianen** [comment]
@martinmaillard - should be fixed now.

**Comment by martinmaillard** [comment]
This time it works, thanks!

**Comment by taylor-revcascade** [comment]
just checking in to make sure this will be in 2.0.8?  Also using DRF and causing issues.

**Comment by etianen** [comment]
Yes, this fix is in the master branch, and will make it into the next release, next week.

Meanwhile, manually installing commit 932160d6f08c5beb0cfe2d99f02e8abd4584fec3 is a good workaround for now.
