### ISSUE TITLE
revisionform_view throws RevertError when there's a unique constraint

### ISSUE THREAD

**Issue by dannyadair** [etianen/django-reversion#593]
I have a unique constraint on a couple of fields of a model. I can see the "Recover deleted" list but when I click on a deleted object that - if it were to be recovered - would violate the unique constraint, then safe_revert() throws RevertError("Could not revert revision, due to database integrity errors.").

I would have hoped to see the deleted object in a form, and then get the unique constraint error when trying to save, but this seems to be happening one step earlier. It's confusing for end users, and it also means the string representation of the deleted objects in the recover list needs to show _all_ relevant information, as you won't get to see more details.

**Comment by etianen** [comment]
Unfortunately, the object has to be saved into the database in order to be viewed in the admin form. The alternative approach has major issues, and was abandoned a few releases ago.

Improving the end user error message here would be worthwhile, however.

**Comment by etianen** [comment]
In fact, this is something I'd definitely take a pull request for. Alternatively, I can have a look into it at the start of next week.

**Comment by etianen** [comment]
Hang on, in reversion 2.0.6 (latest), you do get a nice error message in the admin.

I believe you're using 1.10.2, as per your mailing list message? I'm afraid I can't support past releases to that extent. I suggest you upgrade to 2.0.6.

**Comment by dannyadair** [comment]
Thanks Dave, we shall upgrade :-)
