### ISSUE TITLE
`RegistrationError` in VersionAdmin for history with "unregistered" model in Versions

### ISSUE THREAD

**Issue by ppatc** [etianen/django-reversion#595]
Got an error after doing the follow:
- Registered model A, B 
- created revision C with instance of model A and model B
- unregistered model B by removing the line to register it
- Viewed Django admin history (aka revision C) for model A, and model B is in inlines of admin for model A

I have checked the cause is that `revision._follow_relations_recursive` is following an object that is not registered ([REF1](https://github.com/etianen/django-reversion/blob/master/reversion/models.py#L85)) ([REF2](https://github.com/etianen/django-reversion/blob/master/reversion/admin.py#L184))

Currently using django-reversion==2.0.6
Is it that I am using the wrong approach to "unregister" a model? Any suggestion? 

Thanks!

**Comment by etianen** [comment]
Unregistering a model simply means that you stop creating revisions for that model. Existing revisions remain the the database, and behave as before.
