### ISSUE TITLE
The _post_save_receiver considering "using" argument as mandatory.

### ISSUE THREAD

**Issue by Alkalit** [etianen/django-reversion#598]
Tested on django-reversion==2.0.7

On my current django project I needed to use django's signals framework.
But during test it I got the error:

```
from django.db.models.signals import post_save
from app.models import TheModel

row = TheModel.objects.last()

post_save.send(TheModel, instance=row)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-5bea38b7ce12> in <module>()
----> 1 post_save.send(TheModel, instance=row)

/Users/alkalit/.virtualenvs/project/lib/python2.7/site-packages/django/dispatch/dispatcher.pyc in send(self, sender, **named)
    187 
    188         for receiver in self._live_receivers(sender):
--> 189             response = receiver(signal=self, sender=sender, **named)
    190             responses.append((receiver, response))
    191         return responses

TypeError: _post_save_receiver() takes exactly 3 arguments (2 given)
```

I didn't used signals befor so it took some time to figure out with the error.
The problem is that [`_post_save_receiver`](https://github.com/etianen/django-reversion/blob/master/reversion/revisions.py#L300) realy want to get more args then I give (suddenly, yeah?). 

```
post_save.send(TheModel, instance=row, using='default')
```

It's would be nice if it was strongly marked in documentation or, best, `default` connection used as default (suddenly).

**Comment by etianen** [comment]
I'm afraid that if I strongly marked small implementation details like this in the documentation, the documentation would be unreadably large. :)

When django sends post_save, it always includes the `using` parameter. If your tests weren't sending this, time to update the tests. Forcing revisions to save by manually sending post_save signals isn't a recommended use-case for reversion. Consider just calling save() on a real model.
