### ISSUE TITLE
View reversions history in admin bug.  Details any revision - this revision auto-restore.

### ISSUE THREAD

**Issue by shtalinberg** [etianen/django-reversion#600]
nginx+uwsgi + django==1.8.16, reversion=2.0.7 MySQL DB
When I see reversions history in admin (just see), it's automatic select (and save) viewed version.
I comment #'reversion.middleware.RevisionMiddleware', - did not help

Now I disable this app.
It's critical bug and we lost data with related via foreign keys and restore from backup.
I can help with any trace or debug information ?

**Comment by etianen** [comment]
Are you using MyISSAM tables in MySQL? Those don't support transaction rollback, so could be causing this. InnoDB has been the default for some considerable time now.

Annoyingly, I do include a check for transaction support in django-reversion, but it doesn't catch this case.

**Comment by shtalinberg** [comment]
django-reversion  tables InnoDB
all otther MyISSAM

**Comment by shtalinberg** [comment]
In admin I just see old revision record . no save no any action.   
it's automatic select and try restore old revision with fk and remove new added values in tables via fk -  why?

**Comment by etianen** [comment]
django-reversion displays a revision for preview in the admin as follows:

1. Start transaction.
2. Roll back revision and save database models.
3. Render the admin form
4. Roll back the transaction.

For this to work, all database tables involved in the revision need to support transactions. MyISSAM does not support database transactions, hence your issue.

This should definitely be clearer in the docs! 😱
