### ISSUE TITLE
User and date in revisions history

### ISSUE THREAD

**Issue by acuatoria** [etianen/django-reversion#602]
Cannot see anymore user that made a revision in history admin page.
I figure out It stops working when update to django 1.9.5.
Now I have updated to the latest version of django and reversion but still the same.
Where can be the problem. Have I to force the fields to show up in the admin template?

Thank you in advance.

**Comment by etianen** [comment]
I'm confused. Are you saying that the object history is present, but the user associated with each revision is not shown?

A screenshot might make things clearer.

**Comment by acuatoria** [comment]
Also the comment is not showed
https://snag.gy/9VJGW0.jpg

**Comment by etianen** [comment]
I think you've overridden the object_history template somewhere. That
doesn't look like the object history template for the built-in django
admin, or django-reversion.

**Comment by acuatoria** [comment]
Can I do that? I have updated right now reversion to the latest version. Where is the template? Or how can I changed it?

**Comment by etianen** [comment]
If you're using a 3rd party ModelAdmin other than django-reversion, that
can override the object history template.

Otherwise, look in your projects templates directory for a template called
something like "object_history.html".

**Comment by etianen** [comment]
Incidentally, what version of Django are you using?

**Comment by acuatoria** [comment]
Django==1.10.3

**Comment by acuatoria** [comment]
With django 1.9.5 the same. For that I updated to latest versions

**Comment by acuatoria** [comment]
I have to object_history.html
One in reversion folder and other in django/contrib/admin/templates/admin
I think I have to override template to use in some place in configuration.

**Comment by acuatoria** [comment]
The issue is in recover_list.html

**Comment by acuatoria** [comment]
adding this to recover_list.html
<td>{{deletion.revision.user}}</td>
<td>{{deletion.revision.comment}}</td>
I've got what I want and how it was.
Problem comes when I deploy to heroku that I'm unable to change that html.

**Comment by acuatoria** [comment]
Can I override the template (html) used in settings for example, or in admin.py ?

**Comment by acuatoria** [comment]
Ok, I've got it.
https://django-reversion.readthedocs.io/en/release-1.10.2/admin.html
Overriding template location.
Thank you very much.
I think before the template show theese fields.
However it's solved

**Comment by etianen** [comment]
Glad to managed to fix it! Sorry I couldn't give any more specific help,
but it's the sort of problem that requires digging around in the
particularly codebase, as all sorts of things can lead to a template
override.

Happy coding!
