### ISSUE TITLE
Migrating reversion 1.4 to 1.5.1

### ISSUE THREAD

**Issue by eladr07** [etianen/django-reversion#603]
Hi,

I am maintaining a legacy system which I decided to move to Heroku.

It is running Django 1.3.1 and reversion 1.4.

However, reversion 1.4 is not supported in Heroku, so I had to upgrade to 1.5.1.

When I try to migrate my existing DB, I get "Table 'reversion_revision' already exists" (in the 0001_initial migration script)

When I looked at the source code, I saw that it was indeed trying to create a new table.

How can I run the migrations?

**Comment by etianen** [comment]
Try ./manage.py migrate reversion --fake 0001

**Comment by eladr07** [comment]
Fantastic!

Thanks
