### ISSUE TITLE
Delete related item on inline panel doesn't avoid adding this item to Version.

### ISSUE THREAD

**Issue by x-warrior** [etianen/django-reversion#605]
If you have an Object which has a ForeignKey and you're using InlinePanel to add/edit/delete this InlineObject when deleting and later accessing the history delete action, the delete action still has the inline object.

0. Create a `Token`
1. Create a `NotToken`
2. Create Something with Inline `SubSomething`
3. Check History of the recent object 
4. Go back to the original `Something` object (attention, outside of history)
5. Edit the original object deleting the inline item with the delete checkbox selected
6. Go back to the history
7. Open the latest History, it still has the saved data.

I'm not really familiar with your library I was just testing for a specific use case and noted this. Am I missing something? 

admin.py
```
from django.contrib import admin
from core import models
from reversion.admin import VersionAdmin


class SubSomethingInline(admin.StackedInline):
    model = models.SubSomething


class SomethingAdmin(VersionAdmin):
    inlines = [SubSomethingInline,]

admin.site.register(models.Something, SomethingAdmin)
admin.site.register(models.SubSomething)
admin.site.register(models.Token)
admin.site.register(models.NotToken)
```

model.py
```
from django.db import models


class Token(models.Model):
    name = models.CharField(max_length=255)


class NotToken(models.Model):
    name = models.CharField(max_length=255)


class Something(models.Model):
    name = models.CharField(max_length=255)


class SubSomething(models.Model):
    something = models.ForeignKey(Something)
    token = models.ForeignKey(Token)
    not_token = models.ForeignKey(NotToken)
    value = models.CharField(max_length=255, null=True, blank=True)
```

**Comment by etianen** [comment]
What version of django-reversion are you using?

**Comment by x-warrior** [comment]
```
$ pip freeze
Django==1.10.4
django-reversion==2.0.8
```

**Comment by etianen** [comment]
Thanks.

So, if I understand you correctly, the Token and NotToken are irrelevant
here. It's to do with deleting inlines.

Could you clarify the steps to reproduce. I specifically need to know which
steps are performed using the admin UI, and which are performed using
something else (CLI, non-admin views etc)

**Comment by x-warrior** [comment]
You can reproduce using the models I have added at the begin with the same steps, I have added some clarifications. Also steps done on django admin

On django admin:
0. Create a `Token`
1. Create a `NotToken`
2. Create `Something` with Inline `SubSomething`
3. Check History of the created object
4. Go back to the original `Something` object (attention, outside of history)
5. Edit the original object deleting the inline item with the delete checkbox selected
6. Go back to the history
7. Open the latest History, it still has the saved data (the inline you just removed still shows on history)

**Comment by etianen** [comment]
Thanks for the extra info. I'll dig deep into this tomorrow, once I've
cleared some other stuff.

Just to confirm - are you using any other 3rd parts admin mixins?

**Comment by x-warrior** [comment]
I was able to reproduce the error using only the code I sent on the first comment.

**Comment by etianen** [comment]
I just reproduced this. I'll try to sort a fix.

**Comment by etianen** [comment]
Hopefully the patch in the development branch will fix your issue.

**Comment by etianen** [comment]
(by development branch, I mean master branch)

**Comment by x-warrior** [comment]
Awesome, I will double check if it is working and I will let you know if I discover any other issues. 

Thanks.
