### ISSUE TITLE
post revision commit send additional kwargs

### ISSUE THREAD

**Issue by proshanto** [etianen/django-reversion#610]
Hi,
Thanks for your great project. I'm using post_revision_commit signal with django transaction on_commit to get revision and all versions after database change. I'm using RevisionMixin for my class based views. I have registered my models with follow for related models. So, when a revision is created there are many versions. Currently, I don't know which view triggered the revision or which versions are from related models. 
How can I send additional kwargs to post_revision_commit signal to know for sure which view or model triggered revision? Is there any other workaround to help me with?

**Comment by etianen** [comment]
Hi,

You can store additional meta information on a revision by creating a
custom metadata model:

class YourRevisionMeta(models.Model):
    revision = models.ForeignKey(Revision)
    view_name = models.CharField(max_length=200)

Then, in your view that is saving models, just call:

reversion.add_meta(YourRevisionMeta, view_name="some_view")

This technique can be adapted to store all sorts of additional meta info.

Simply access instances of YourRevisionMeta from the database in your
on_commit handler to get at the metadata.

**Comment by proshanto** [comment]
Thanks. It worked as expected :)
