### ISSUE TITLE
In which file django reversion API should be added?

### ISSUE THREAD

**Issue by cosmologist10** [etianen/django-reversion#614]
I'm really very confused where revisions should be created.

**Comment by etianen** [comment]
Do you mean the calls to reversion.register()?

Those are best placed in models.py.

**Comment by cosmologist10** [comment]
On Tue, Jan 10, 2017 at 3:22 PM, Dave Hall <notifications@github.com> wrote:

> Do you mean the calls to reversion.register()?
>

I have already done Admin integration, so i thought i don't need to
register models. I was asking for creating revisions, where i need to paste
this code http://paste.opensuse.org/27029075.


>
> Those are best placed in models.py.
>

So, i need to place these codes in models.py

**Comment by etianen** [comment]
That low level API code is for manually creating revisions in your own
code. If you only need the admin integration, then you don't need to touch
the low-level API.

**Comment by cosmologist10** [comment]
On Tue, Jan 10, 2017 at 11:03 PM, Dave Hall <notifications@github.com>
wrote:

> That low level API code is for manually creating revisions in your own
> code.


I want to add this only. So, in which file i need to add this.


> If you only need the admin integration, then you don't need to touch
> the low-level API.


Basically, my task was to enable version control.

**Comment by etianen** [comment]
That code you want to paste is example code for creating a revision
manually using the low-level api. It should not be used directly in your
project. It should be used as an example for writing your own version
control functionality.

For example, if you want to create revisions in a view, then you'd use
*similar* code to that in a view function in a views.py module.

**Comment by cosmologist10** [comment]
Okay, So for creating revisions in views can i follow up https://django-reversion.readthedocs.io/en/stable/views.html#views  this one

**Comment by theskumar** [comment]
Hey @cosmologist10, you should be looking at the api here: https://django-reversion.readthedocs.io/en/stable/api.html#creating-revisions.

Now where to put this really depends on the app architecture, you can either override `save()` method of form used to save the model or you can override the same method of model class itself. 

In short, you need wrap the save() method, so reversion know what has changed before saving the model instance.
