### ISSUE TITLE
Having formatting or layout problem with Grappelli and import-export

### ISSUE THREAD

**Issue by rcooke** [etianen/django-reversion#615]
I tried to add ExportMixin to my system.  Because I'm using 

https://github.com/etianen/django-reversion

Which uses its own custom admin, I had to use your ExportMixin.  When put second in the class list it did not seem to work.  So I put it first, as in:

`@admin.register(Parts)`
`class PartsAdmin(ExportMixin, VersionAdmin):`

Which works, but the change list view is not as shown in the sample photos. 

The "Add Parts" button used to be a large oval above the "Filter" tab. Both it and the "Export" button are simple text hyperlinks against the left hand margin.

Also, django-reversion had a "Recover Deleted" button beside the "add Parts" button, it seems to have vanished.

I'm going to start trying to untangle the various CSS logic in play here, but wanted to post first in case this is a know issue with a quick and easy fix.

Thanks in advance!

My setup:
 - Hosted on Python Anywhere
 - Django 1.10
 - Python 2.7

Cross-Posting this to all 3 libraries in use:
 
https://github.com/sehmaschine/django-grappelli/issues/799
https://github.com/django-import-export/django-import-export/issues/561

**Comment by etianen** [comment]
I'm afraid that django-reversion can only concern itself with looking good
in the core django admin.

If you want it to look good in grapelli, either grapelli itself of another
standalone project will need to provide the updated templates.
