### ISSUE TITLE
Is there documentation on testing?

### ISSUE THREAD

**Issue by mountainpaul** [etianen/django-reversion#617]
I believe I need to run createinitialrevisions on my applications test database prior to running my tests. Are there any suggestions on how best to do this?

**Comment by mountainpaul** [comment]
I ended up using revision_manage_manually = settings.TESTING, in any class views that were changing the database.  In settings I used: TESTING = len(sys.argv) > 1 and sys.argv[1] == 'test'.

**Comment by etianen** [comment]
You shouldn't really need to run createinitialrevisions in your tests, unless you're doing something custom with django-reversion.

Hoever, if you do need to do this, do something like:

``` py
from django.core.management import call_command

class MyTest(TestCase):

    def setUp(self):
        super().setUp()
        call_command("createinitialrevisions")
```
