### ISSUE TITLE
Importing models causes already registered error

### ISSUE THREAD

**Issue by burhan** [etianen/django-reversion#62]
Sample case:

in appA.models.py:

import reversion
from django.db import models
class MyModel(models.Model):
    name = models.CharField(max_length=20)
reversion.register(MyModel)

in AppB.models.py:
from django.db import models
from appA.models import MyModel

class MyOtherModel(models.Model):
    name = models.CharField(max_length=20)
    other = models.ForeignKey(MyModel)

Save, sync db

now in django shell:

from appA.models import *
from appB.models import *

RegistrationError: class 'appA.models.MyModel' has already been registered with Reversion.

**Comment by suvansh** [comment]
I'm getting the AlreadyRegistered error as well.
How would the fix described above be implemented if using the automatic registration associated with admin integration? (i.e. admin.site.register(Model, ModelAdmin))
I tried using the above fix as is, but got the same error.

**Comment by etianen** [comment]
So you're only using the admin integration, and you're still getting `AlreadyRegistered`?

That should be impossible: https://github.com/etianen/django-reversion/blob/master/src/reversion/admin.py#L66

**Comment by suvansh** [comment]
Is it possible that the model is being registered by something else after _autoregister() has run? This is what I have, using django-reversion-compare as well:

    class MyModel(models.Model):
       #some fields
    class MyModelAdmin(CompareVersionAdmin):
       ignore_duplicate_revisions = True
    admin.site.register(MyModel, MyModelAdmin)
Is there any reason this might be registered twice, perhaps some unexpected behavior from django-reversion-compare?

**Comment by etianen** [comment]
Can you provide a full traceback?
