### ISSUE TITLE
Clarification and Examples in documentation

### ISSUE THREAD

**Issue by bgrantdev** [etianen/django-reversion#620]
I would like to suggest some updates to the documentation.

Update the views documentation [http://django-reversion.readthedocs.io/en/stable/views.html](url) to include an example of the decorator use.  The usage seems to differ from the standard decorators like @login_required.  There is an example of the mixin usage so it seems appropriate for another.

Specify somewhere in the documentation when revisions are created, there is a section [http://django-reversion.readthedocs.io/en/stable/api.html](url) about creating revisions.  Is it required to explicitly create revisions for registered models?  I am getting revisions saved when model instances are edited/created with a model form, but not in some other cases where a change & save is done manually in the code.

**Comment by etianen** [comment]
Why don't you hit me with a pull request showing how you'd improve it? I'll
probably tweak it for editorial style, but it's the best way to show what
you're talking about, I think.

This sort of feedback is invaluable. I've obviously explained what *I* think
is important information, but since I wrote the library, I'm obviously not
a typical user! :P

**Comment by bgrantdev** [comment]
That's fair I will take a stab at it when I get a chance.  


Could you clarify on the second point, about when revisions are logged, are users required to explicitly set revision blocks every time they want to log one, or are there times where a revision is created simply because the model is registered I ask because I am seeing revisions created when instances are changed in a model form.

**Comment by etianen** [comment]
A block of code has to be wrapped in a revision for revisions to be created
in the DB.

You can do this explicitly with reversion.create_revision(), or you can use
view decorators, view mixins, or middleware to do this automatically. A
model form by itself will not create a revision.
