### ISSUE TITLE
No version history when using the register decorator

### ISSUE THREAD

**Issue by limbera** [etianen/django-reversion#622]
## Package versions
python v3.5.2
django v1.10
django-reversion v2.0.8

## Details
I've made a small sample model and some test cases to demonstrate the issue:

```python
import reversion
from reversion.models import Version

from django.db import models
from django.test import TestCase

@reversion.register()
class MyModel(models.Model):
    title = models.CharField(max_length=255)

class ReversionTest(TestCase):
    def test_reversion_history_log(self):
        obj = MyModel(title='An old title')
        obj.save()
        self.assertEqual(Version.objects.get_for_object(obj).count(), 1)

        obj.title = 'A new title'
        obj.save()
        self.assertEqual(Version.objects.get_for_object(obj).count(), 2)

        obj.title = 'A newer title'
        obj.save()
        self.assertEqual(Version.objects.get_for_object(obj).count(), 3)
```

Tests fail with `AssertionError: 0 != 1`

If I replace my assertions with print statements the output is:
```
<QuerySet []>
<QuerySet []>
<QuerySet []>
```

If I manually override save, 
```python
def save(self, *args, **kwargs):
    with reversion.create_revision():
        super().save(*args, **kwargs)
```

The tests pass and the output of printing (instead of asserting) is:
```
<QuerySet [<Version: MyModel object>]>
<QuerySet [<Version: MyModel object>, <Version: MyModel object>]>
<QuerySet [<Version: MyModel object>, <Version: MyModel object>, <Version: MyModel object>]>
```

**Comment by limbera** [comment]
Could be related to this issue? https://github.com/etianen/django-reversion/issues/612

**Comment by etianen** [comment]
Try decorating `test_reversion_history_log` with `reversion.create_revision()` 😄 

https://django-reversion.readthedocs.io/en/stable/api.html#creating-revisions

**Comment by limbera** [comment]
I was under the impression that by registering the model (by decorating it with reversion.register), that calling save would automatically make a revision for you?

**Comment by etianen** [comment]
I'm afraid that's not the case.

https://django-reversion.readthedocs.io/en/stable/api.html#creating-revisions

You can enable your desired behavior using the RevisionMiddleware.
