### ISSUE TITLE
Get reference to revision object/pk in/after revision block.

### ISSUE THREAD

**Issue by wjdp** [etianen/django-reversion#623]
Apologies for posting a question here.

I'm using both reversion and activity-stream and want to add a reference to revisions from the activity. Activity-stream allows arbitrary data to be saved to the actions via a jsonfield.

My code currently looks like this. I'm hoping to patch in a reference to the revision in action.send.

```python
with reversion.create_revision() and transaction.atomic():
    reversion.set_comment('Updated')
    model.save()

action.send(self.request.user, verb='updated', target=mode, revision_pk=?)
```

How do I get a reference to the revision?

**Comment by etianen** [comment]
This is tricky, as the revision is only created when the outermost create_revision() block ends, so there's no way to know a given block will create revision or not.

Could you use one of the signals provided by the library?

https://django-reversion.readthedocs.io/en/stable/signals.html

**Comment by wjdp** [comment]
I've only used signals in a global context, hence thinking them to be tricky to use for this. I've wrapped the block with a signal.connect and after .disconnect. Do you see any issue with the following (i.e. could it somehow handle another event, or fail to fire as the signal is handled later?)

```python
post_revision_commit.connect(self.send_action)
with reversion.create_revision() and transaction.atomic():
    reversion.set_comment('Updated')
    model.save()
post_revision_commit.disconnect(self.send_action)
```

In a very brief manual test it seems to be working fine.

**Comment by etianen** [comment]
This will kinda work, but you've got a latent problem here. If, at a later
point, a developer puts in the RevisionMiddleware, or otherwise wraps your
function in another create_revision() call, then your signal handler will
disconnect before the revision is created. That's the crux of the problem.

Provided nobody else does this, I think this will work. To be sane, it
might be worth protecting the post_revision_commit signal with a
threading.Lock().

**Comment by wjdp** [comment]
Thanks for the insight. I think I've gotten my head a little further around how reversion works.

(More importantly I've an activity feed with version integration :smile: 

![image](https://cloud.githubusercontent.com/assets/1690934/23217407/0996ac0c-f911-11e6-8518-3e8f47e1de26.png)

 )

**Comment by wjdp** [comment]
In case anyone comes across this later, the solution I came up with was a class `DoAction` to use in a `with` block: https://gitlab.com/wjdp/xSACdb/blob/develop/src/xsd_frontend/activity.py

To 'approve a trip' as in the above screenshot you would do:

```python
with DoAction() as action, reversion.create_revision():
            self.state = STATE_APPROVED
            self.save()
            revisions.set_user(actor)
            action.set(actor=actor, verb='approved trip request', target=self, state=STATE_APPROVED,
                        style='trip-approved')
```
