### ISSUE TITLE
revert option in custom page

### ISSUE THREAD

**Issue by srikanth148** [etianen/django-reversion#626]
How to move revert option from admin site to custom page

**Comment by etianen** [comment]
You'll need to examine the code in reversion/admin.py and copy the logic to your own custom page.

https://github.com/etianen/django-reversion/blob/master/reversion/admin.py#L176

Currently it uses a bit of a hack with database transactions to roll back the revision after preview. The plan is to eventually abstract this into a reusable API, but at the moment you're limited to recreating the same hack in your own code.
