### ISSUE TITLE
Help creating model instance from field_dict for models with m2m fields

### ISSUE THREAD

**Issue by jonesnc** [etianen/django-reversion#627]
I could use some help. I have django-reversion set up, it's tracking changes to one of my models that has a few many-to-many relationship with other models.

The problem I'm running into is in my UpdateView. I'm trying to create a model instance for my ModelForm, but the many-to-many field data is ignoring reversion's field_dict data and is displaying what's currently in the actual db associated with that model.

The "parent model" is called `Allergy`, which has a many-to-many relationship to `Allergen`.

Here's my `UpdateView`'s `get_object` method and a helper function to construct an instance of the Allergen model that represents reversion's version data:
```
def get_object(self, queryset=None):
    allergy_id = self.kwargs['allergy_id']
    allergy_inst = get_object_or_404(Allergy, pk=allergy_id)

    version_id = self.kwargs.get('version_id')
    if version_id:
        return create_allergy_from_version(allergy_inst, version_id)
    else:
        return allergy_inst


def create_allergy_from_version(allergy_inst: Allergy, version_id: int) -> Allergy:
    versions = Version.objects.get_for_object(allergy_inst)
    version_with_id = versions.get(revision_id=version_id)
    allergy_inst = Allergy(**version_with_id.field_dict)
    allergen_versions = version_with_id.revision.version_set.filter(
        content_type=ContentType.objects.get_for_model(Allergen)
    )
    # do something here to associate *reversion's* allergen data to allergy_inst, not sure what!
    return allergy_inst
```

I hope this gave you enough to go on, please let me know if you'd like more code and/or details with what I'm trying to do.

**Comment by etianen** [comment]
The related fields on Django models perform database lookups, so unless you save the revision to the database, they will always reference the live data.

There are two solutions:

1. Manually look up relations in `version.revision.version_set.all()`. This is very tedious, and means abandoning the ORM.
2. Use the same transaction hack that the admin integration uses: https://github.com/etianen/django-reversion/blob/master/reversion/admin.py#L176

I'm planning on formalizing the admin transaction hack into a helper method at some point, but for the time being you need to duplicate the logic in your own codebase.
