### ISSUE TITLE
Concrete inheritance + version ordering bug

### ISSUE THREAD

**Issue by mailbackwards** [etianen/django-reversion#628]
I have a group of versioned models that inherit from a concrete base model:

```python
# MODELS

class Content(models.Model):
    headline = models.CharField()
    # more fields...

class Story(Content):
    copy_edited = models.BooleanField(default=False)
    # more fields...

class Video(Content):
    aspect_ratio = models.CharField()
    # more fields...

# ADMIN

class ContentAdmin(VersionAdmin):
    model = Content

class StoryAdmin(ContentAdmin):
    model = Story

class VideoAdmin(ContentAdmin):
    model = Video
```

For half of my Story and Video objects, when I go to a revision view, the formfields for the parent Content are completely blank (`headline` in this example). It's happening whenever the parent's version has a higher pk than the child's version. But when the child's version reverts before the parent's everything is fine, and it's able to find and display the parent's fields. It looks like the ordering of versions on save/revert doesn't matter in the current code. Why might it be mattering here?

The issue occurs when reverting rather than when rendering the change form-- it has already lost the fields after the `revert()` [here](https://github.com/etianen/django-reversion/blob/master/reversion/admin.py#L184). It looks like the `Deserializer` only picks up local fields and doesn't traverse the parent, but I think this is expected behavior. Beyond this I'm at a loss. Any help much appreciated.

python 2.7, Django 1.8, django-reversion==2.0.8

Thanks!

**Comment by etianen** [comment]
What database are you using?

**Comment by mailbackwards** [comment]
DB is Postgres 9.4

**Comment by etianen** [comment]
That is really odd. Postgres supports deferred foreign keys, so the order
of revert should be completely irrelevant.

I'll have a look and see what I can come up with.

Could you check the field_dict of the version instances and verify that the
data is correctly saved for the parent and child models? That way we can
narrow it down to revert behaviour.

Are you using any sort of queryset-level caching?

**Comment by etianen** [comment]
Possibly. Can you test this hypothesis by removing all cached_property
decorators from reversion.models, and report on your findings?

**Comment by davmlaw** [comment]
Hi, I have a similar issue - field_dicts are ok, but the object isn't:

```

@reversion.register()
class Pathogenicity(models.Model):
    rank = models.IntegerField(primary_key=True)
    description = models.TextField()


@reversion.register(follow=('classification', ))
class VariantClassification(models.Model):
    classification = models.ForeignKey(Pathogenicity, null=True)

@reversion.register(follow=('variantclassification_ptr',))
class GenomicVariantClassification(VariantClassification):
    pass


In [40]: versions[0]._object_version.object.classification

In [41]: versions[2]._object_version.object.classification

In [42]: versions[0].field_dict['classification_id']
Out[42]: 1

In [43]: versions[2].field_dict['classification_id']
Out[43]: 5
```

Replacing @cached_property with @property didn't fix it. My libraries:

```
Postgresql 9.6.4
Django==1.11.6
django-reversion==2.0.10

```

**Comment by etianen** [comment]
I don't really have time to debug this myself, but if anyone feels brave,
I'll take a pull request!
