### ISSUE TITLE
Apply Reversion to Single Model

### ISSUE THREAD

**Issue by andrewheyer** [etianen/django-reversion#629]
Not so much as an issue but a question I was unable to find answered in the documentation or Issues. 

**What I want**
I want to add model tracking to a project I am currently working on. This is a very large project with certain models going under constant changes. For efficiency I want to only track certain models.

**what I see & assume**
From the documentation it appears that ALL models get tracked. And by either implementing the API or registering to Admin I can "reveal" the previous versions stored. In other words, all models are being stored for every change. Regardless of how I can see and revert those changes. 

_Am I right in thinking that all models are saved? If so can I specifically chose what models are tracked?_

**Comment by etianen** [comment]
Only models that you register using `reversion.register()` get tracked.

Or do you mean model **instances**?

**Comment by andrewheyer** [comment]
_Only models that you register using reversion.register() get tracked._

I am currently tracking a custom "User" object like this...

```
from apps.models import User
from reversion.admin import VersionAdmin
...

class UserAdmin(VersionAdmin, HijackUserAdminMixin):
    ...
    ...


admin.site.register(User, UserAdmin)
```
'User' is one of many models inside it's configured App. And this app is one of many registered in Settings.py. So is what you mean by "tracked" that nothing goes on behind the scenes for my other models so long as I do not have them registered? If so this is the desired behavior I want.

**Comment by etianen** [comment]
Correct. Unless a model is registered with reversion, the other models are
ignored.

Reversion uses the Django signals framework to listen for save events.
Registering a model connects to the save signal. All unregistered are
completely ignored.

**Comment by andrewheyer** [comment]
Awesome! Thank you!
