### ISSUE TITLE
Does reversion 1.10.x support Django 1.10?

### ISSUE THREAD

**Issue by guettli** [etianen/django-reversion#630]
We are unsure if reversion 1.10.x supports Django 1.10?

Or should we upgrade to reversion 2.x?

According to this page, reversion 1.10.x should support Django 1.10: http://django-reversion.readthedocs.io/en/latest/django-versions.html

**Comment by etianen** [comment]
I'm afraid you're reading that table wrong. If you have Django 1.8+, you need reversion 2.00+.

**Comment by etianen** [comment]
(I can see how the confusion might arise 😄 )

**Comment by TZanke** [comment]
| Django version        | Reversion release           |
| ------------- |:-------------:|
| 1.8-current      | 2.0.0 |
| 1.7      | 1.10.0      | 
| 1.6 | 1.8.5      |

**Comment by etianen** [comment]
Yes, that would make more sense. I'll happily take a pull request to fix it.

**Comment by guettli** [comment]
I created a pull request. https://github.com/etianen/django-reversion/pull/631
