### ISSUE TITLE
403 error when accessing /history without change permission

### ISSUE THREAD

**Issue by olivierdalang** [etianen/django-reversion#634]
Hi !

It seems the user gets a 403 Forbidden page when trying to access the /history page of a VersionAdmin without having the "change" permission. I think he should still be able to see the change list, just not to save the changes.

Thanks !

Olivier

**Comment by etianen** [comment]
If the user does not have change permission, the history button should be
hidden from the UI, as the user cannot access the change form page.

Is this only a problem when the user directly visits the URL?

I think this is how the base Django admin handles this, so I'm not sure it
should be changed in django-reversion.
