### ISSUE TITLE
How to know version id which was reverted?

### ISSUE THREAD

**Issue by NogerbekNurzhan** [etianen/django-reversion#641]
Hello! I am little bit comfused. I want to know ID of version which was reverted. How to add this id in comment? Here you can see my view function.

**views.py:**
```
@reversion.create_revision()
def project_revert(request, project_code, project_reversion_id):
    project = get_object_or_404(Project, pk=project_code)

    revision = get_object_or_404(Version.objects.get_for_object(project), pk=project_reversion_id).revision
    revision_id = revision.id

    reversion.set_user(request.user)
    reversion.set_comment("REVERT {}".format(revision_id))

    revision.revert()
    return redirect('project:project_detail', project_code=project.code)
```

**urls.py:**
```
url(r'^(?P<project_code>[0-9a-f-]+)/(?P<project_reversion_id>\d+)/project_revert/$',
        project_revert,
        name='project_revert'),
```

**button in template:**
```
<a href="{% url 'project:project_revert' project_code=project.code project_reversion_id=version.revision.id %}">
      {% trans 'Revert' %}
</a>
```

**Comment by etianen** [comment]
revision = get_object_or_404(Version.objects.get_for_object(project),
pk=project_reversion_id).revision
revision_id = revision.id
reversion.set_comment("REVERT {}".format(revision_id))
revision.revert()

**Comment by NogerbekNurzhan** [comment]
@etianen Hello! I am tring to use that code but have strange behavior.

When I click `'revert'` button it must redirect user to `project_detail` page but it redirect me `project_revert` url. I update my post with code. Is it correct? Do you have any ideas about that? I am little bit comfused cause before after clicking 'revert' button it worked.

ERROR in console:
`Not Found: /ru/account/dashboard/projects/c9623d40-bac3-49cc-8416-f2cce6944e1a/23/project_revert/`

**Comment by NogerbekNurzhan** [comment]
@etianen Hello! I used your code but `reversion.set_comment("REVERT {}".format(revision_id))` dont work cause there is no ID of version which was reverted. Look the picture below.

![3](https://cloud.githubusercontent.com/assets/8999232/25582247/016a8f8a-2eae-11e7-87f0-5576723d420c.PNG)

**Comment by NogerbekNurzhan** [comment]
Thank you very much! Thats what I am looking for! =)
