### ISSUE TITLE
Error: No module named 'rest_frameworkreversion' after installing

### ISSUE THREAD

**Issue by gitanupam** [etianen/django-reversion#642]
I needed a good model version maintenance library and django-reversion seems like a good bet that seems to have stood the test of time and @etianen seems to be pretty active too! So I installed it as follows:
`pip install django-reversion` and added `'reversion'` to `INSTALLED_APPS`

but getting the following error on the console:
`No module named 'rest_frameworkreversion'`

A Google search for the above didn't reveal much. Anyone?

(using Django 1.10)

**Comment by amureki** [comment]
@gitanupam seems like you've forgot to add comma separator after 'reversion'.
So you have something like this:
```
INSTALLED_APPS = (
    ...,
    'rest_framework'
    'reversion',
    ...
)
```

while it should be:
```
INSTALLED_APPS = (
    ...,
    'rest_framework',
    'reversion',
    ...
)
```

🙃

**Comment by gitanupam** [comment]
Thanks so much @amureki. I am embarrased :-)

**Comment by amureki** [comment]
@gitanupam same happens with me all the time. :)
