### ISSUE TITLE
Handling migrations

### ISSUE THREAD

**Issue by Visgean** [etianen/django-reversion#643]
Hi, I have described my issue here: https://stackoverflow.com/questions/44124100/django-reversion-fails-to-recover-object-after-migration 

any thoughts?

**Comment by etianen** [comment]
In general, database migrations do not work well with django-reversion, as
the data stored in the revision table will no longer match the structure of
the live database table. I typically clear out revision data after
performing a migration.

Adding an integer field should be fine, though. The error you're getting
implies that a foreign key can't be satisfied during the revert.

**Comment by Visgean** [comment]
There must be a bug then, I just tried with fresh DB on the model I described and it fails.

**Comment by etianen** [comment]
What exact set of steps do you carry out to recreate that error.

That error is probably being caused by the User referenced by the author
relation no longer existing.

**Comment by Visgean** [comment]
Ok, I am going to recreate it from start:

I have this model: 
```
@reversion.register()
class BlogPost(models.Model):
    title = models.CharField(max_length=32)
    content = models.TextField()
    # random_field = models.PositiveIntegerField(null=False, blank=False)

```
I create migration, db and superuser. 

I login to admin and create one blog article and change it few times. 

I create migration and migrate it. I go to admin and use the interface to try to revert it to the state when it was created. It says Could not save title A version - missing dependency.

There was no user created between any of those steps, there is no foreign key relating to user.

**Comment by etianen** [comment]
Hmm. Odd.

To debug this, you need to edit the reversion source code. Underneath line
27 in models.py, add "raise". It should look like this:

https://gist.github.com/etianen/c876c2c56124fd24dae828c3fcf69b03

That will allow the original error to propagate, and we''l see what's
causing it.

**Comment by Visgean** [comment]
```
IntegrityError at /admin/blog/blogpost/1/history/1/
NOT NULL constraint failed: blog_blogpost.random_field
```
full log:
https://gist.github.com/Visgean/bae9e041273abee44719e0af8a48cc5a 

I mean I understand where this error is coming from, the one solution I can imagine is to take the json of the latest object and update it with the json of the object that we are reverting to.

**Comment by etianen** [comment]
Ah, I see. annoying. It appears that the revisions can handle deleting a
field, but not adding one.

Automating this is pretty much impossible. There are revision databases out
there with gigbytes of old revisions, and updating old revision data when a
new migration occurs could take days of runtime per migration. It's not
really feasible.

My general approach is to delete the revision data after a migration. If
you really want to keep it, then you can write your own data migration the
in the app.
