### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Dellsouth** [etianen/django-reversion#644]
When I delete an object, Is It not saved in reverse database?. I try it but it doesn't work for me.

Exist the possibility of save automatically all CRUD operations with some models given?.

Do application allow to return to previous state of database?. Do any view exists where return to previous state?

Thanks for your attention.

**Comment by etianen** [comment]
A version is saved when a model is saved. Nothing is done when a model is deleted. Saving a record when a model is deleted isn't relevant for django-reversion. More information in #164 

Reversion doesn't snapshot the whole database. Instead, it snapshots individual and groups of models. You can use the built-in admin integration to roll back individual models. You can use the low-level API to write your own non-admin views.

https://django-reversion.readthedocs.io/en/stable/admin.html
https://django-reversion.readthedocs.io/en/stable/api.html
