### ISSUE TITLE
Calling field_dict fails when serialized_data contains BooleanField which is null

### ISSUE THREAD

**Issue by sajoku** [etianen/django-reversion#645]
I'm storing revisions with a few BooleanFields which don't have to be True or False. When calling field_dict on the revisions this returns an ```RevertError: Could not load 87 version - incompatible version data.```

### Reproducable by doing the following

models.py
```
class Customer
  is_customer = models.BooleanField()
```
serialized_data
```
[{"model": "app_name.customer", "pk": 87, "fields": {"user": 1, "is_customer": null}]
```
console
```
customer = Customer.objects.get(pk=87)
customer.revisions()[0].field_dict
```
This will fail with the  following backtrace:

```
----> 1 revisions[0].field_dict

/Users/sajoku/.pyenv/versions/3.6.1/lib/python3.6/site-packages/django/utils/functional.py in __get__(self, instance, cls)
     33         if instance is None:
     34             return self
---> 35         res = instance.__dict__[self.name] = self.func(instance)
     36         return res
     37

/Users/sajoku/.pyenv/versions/3.6.1/lib/python3.6/site-packages/reversion/models.py in field_dict(self)
    243         This method will follow parent links, if present.
    244         """
--> 245         field_dict = self._local_field_dict
    246         # Add parent data.
    247         for parent_model, field in self._model._meta.concrete_model._meta.parents.items():

/Users/sajoku/.pyenv/versions/3.6.1/lib/python3.6/site-packages/django/utils/functional.py in __get__(self, instance, cls)
     33         if instance is None:
     34             return self
---> 35         res = instance.__dict__[self.name] = self.func(instance)
     36         return res
     37

/Users/sajoku/.pyenv/versions/3.6.1/lib/python3.6/site-packages/reversion/models.py in _local_field_dict(self)
    221         """
    222         version_options = _get_options(self._model)
--> 223         object_version = self._object_version
    224         obj = object_version.object
    225         model = self._model

/Users/sajoku/.pyenv/versions/3.6.1/lib/python3.6/site-packages/django/utils/functional.py in __get__(self, instance, cls)
     33         if instance is None:
     34             return self
---> 35         res = instance.__dict__[self.name] = self.func(instance)
     36         return res
     37

/Users/sajoku/.pyenv/versions/3.6.1/lib/python3.6/site-packages/reversion/models.py in _object_version(self)
    204         except DeserializationError:
    205             raise RevertError(ugettext("Could not load %(object_repr)s version - incompatible version data.") % {
--> 206                 "object_repr": self.object_repr,
    207             })
    208         except serializers.SerializerDoesNotExist:

RevertError: Could not load 87 version - incompatible version data.
```

Changing the `null` value to true or false will load in the field_dict nicely.

https://github.com/etianen/django-reversion/blob/master/reversion/models.py#L234
Seems to load in the field_dict but I'm not entirely sure how to go about fixing this.
Any pointers?

**Comment by etianen** [comment]
If the Django serialisation framework can't load the data, then it's a bug
in your code, or the serialisation framework.

How are there null values in the database, if you're using a BooleanField?
A Boolean field does not permit null, only True or False.

If this is because of a database migration, then you will need to clear
your old revisions, as they are now invalid.

If it's because of setting null=True in your field definition, then
consider using NullBooleanField. I believe this is what the Django docs
recommend, and may be the cause of your problems.

**Comment by sajoku** [comment]
Ah that's it!

I'm coding against an existing database so all my models have `Meta: managed: False` and wil only read the kind of types I give them. Which in this case was `models.BooleanField`. Setting it to `models.NullBooleanField` does indeed load the `field_dict` in correctly.

Thanks for taking a look and the advice 👍
