### ISSUE TITLE
Regression in version data collection for ManyToMany fields

### ISSUE THREAD

**Issue by claudep** [etianen/django-reversion#646]
I think that issue #138 is striking again! I will soon link a pull request containing a test to reproduce the issue.

**Comment by etianen** [comment]
Thanks for your help on this. It is fixed in master.

**Comment by claudep** [comment]
Thanks Dave for the quick reaction!

**Comment by etianen** [comment]
The fix is in v2.0.9, just released. Thanks for the help!
