### ISSUE TITLE
migration problem

### ISSUE THREAD

**Issue by Andertaker** [etianen/django-reversion#650]
Hello!
I try to update reversion in existing project, and got next problem:
The project was on Django 1.6 with south plugin for migrations, I update django to 1.10.
But I was't able to appy reversion migrations.
I already have reversion tables in db so I run ./manage.py migrate reversion --fake-initial
It should to
0001_initial   Faked
0002             apply
...

But this migration "migrations/0001_squashed_0004_auto_20160611_1202.py" replace other migrations,
so I cant apply migrations one by one manually or all with --fake-initial.
Can you please remove this migration "migrations/0001_squashed_0004_auto_20160611_1202.py"

**Comment by etianen** [comment]
I'm afraid I can't just remove a migration without breaking a lot of things
in people's existing projects.

Upgrading your reversion tables is likely to be a manual process at this
point, since you're upgrading from south, and from a very old reversion
release.
