### ISSUE TITLE
request.user is not set when using RevisionMixin

### ISSUE THREAD

**Issue by genomics-geek** [etianen/django-reversion#651]
I have setup django-reversion and it is creating records in the database on POST requests. But for some reason the user is not registered.

Here is the view in question:

```python
class PhenotypeViewSet(RevisionMixin, viewsets.ModelViewSet):
    """A simple ViewSet for viewing and editing Phenotypes."""

    queryset = models.Phenotype.objects.fast()
    serializer_class = serializers.PhenotypeSerializer
    filter_backends = (django_filters.rest_framework.DjangoFilterBackend, )
    filter_class = filters.PhenotypeFilter
```

I have POST to the REST API and it creates the records below, but you will see user is empty.

```
sqlite> select * from reversion_revision;
1|2017-07-07 01:46:54.193729|Initial version.|
2|2017-07-07 02:07:54.511354||
3|2017-07-07 02:08:32.504194||
```

Do I need to override the `.update()` and `.create()` methods in the ViewSet? Or is there a way to set it up in the decorator? Thanks for the help.

**Comment by etianen** [comment]
Can you try using the latest master? A fix recently went in that might sort
your problem.

**Comment by genomics-geek** [comment]
Yup it works. Thanks.
