### ISSUE TITLE
M2M relationships are not saved in associated version (they appear on subsequent saves)

### ISSUE THREAD

**Issue by JaydenIvanovic** [etianen/django-reversion#652]
Version 2.0.9
Django 1.8.9
I'm seeing an issue where changes to a many-to-many field made through the django admin interface are not saved in the version record. For example given the following classes:

```
class Users:
    pass

class Computers:
    users = models.ManyToManyField(User, related_name='computers', blank=True)
```

 I register them via:

```
class UserAdminModel(VersionAdmin):
    def reversion_register(self, model, **options):
        options["follow"] = ("computers",)
        super(UserAdminModel, self).reversion_register(model, **options)

class ComputerAdminModel(VersionAdmin):
    def reversion_register(self, model, **options):
        options["follow"] = ("users",)
        super(ComputerAdminModel, self).reversion_register(model, **options)
```

If I use the m2m "filter_horizontal" widget on the user edit page and change the computers they are assigned to, it is reflected in the saved object but not the one in the history list. Its worth noting that this problem does not happen in reverse i.e. when changing the m2m relationship from the computers screen. I believe this issue is directly related to https://groups.google.com/forum/#!topic/django-reversion/gg9q65LuX7Q and the open issue linked to in the first comment (for django-reversion-compare although I believe the problem exists within django-reversion).

**Comment by etianen** [comment]
django-reversion only stores the m2m info on the model that contains the
m2m field. That's a constraint from the django serialization framework, I'm
afraid.

I'd suggest removing the m2m widget from the user admin to avoid confusion,.

**Comment by JaydenIvanovic** [comment]
That's a shame as I'm unable to remove the widget due to a specific requirement, but I understand the current limitations.
Is it possible to listen to the pre_revision_commit signal and do some "magic" by adding version objects to the revisions? If not are there any hacky solutions which come to mind which I may be able to use in this situation?

**Comment by etianen** [comment]
Unfortunately, you're going to be fighting the django serialization
framework here. The ManyToMany field data is stored on one side of the
relationship only. Reverting the non-storing side won't touch the M2M data
that is stored on the other model.

I guess maybe you could somehow add the storing side of the M2M
relationship to the revision. I think this would create suprising
behaviour, though, as reverting the non-storing side wold roll back the
storing side too.

**Comment by JaydenIvanovic** [comment]
No worries, I'd rather not fight against the framework so perhaps its time to go back to the drawing board. Thanks for your help!

**Comment by etianen** [comment]
No worries. Feel free to steal whatever you might find useful from
django-reversion. :)
