### ISSUE TITLE
Excluded fields reset on revert.

### ISSUE THREAD

**Issue by bguggs** [etianen/django-reversion#653]
I have a Question model that I am using django-reversion to track changes on. Each question has a vote score that I do not want to be changed if a question is edited and then reverted. I've excluded the vote fields:

`@reversion.register(exclude=["vote_score", "num_vote_up", "num_vote_down"])`

However, every time I do a version.revert() the fields are reset to their default value of 0, even though they are not in the field_dict. Is there a way to either set these values manually before revert or prevent them from being overwritten by the revert?

Thanks for your help :)

**Comment by etianen** [comment]
I'm afraid I don't think there is. The django serialization framework is
responsible for this behavior, and I don't know of any way to change it.

If this behaviour could be added as an option to the django serialization
frameowork, then django-reversion could also add support for it.
