### ISSUE TITLE
Updating from 2.0.8 to 2.0.9 will force install last (1.11.3) version of Django instead current version 

### ISSUE THREAD

**Issue by Egregors** [etianen/django-reversion#656]
So, if I have project with Django 1.10.7 for example, and I will try to update django-reversion by usual way, it force update current Django (I don't know why) and all will break.

**Comment by etianen** [comment]
Are you doing `pip install -U django-reversion`?

If so, that's going to update every other installed package.

Try this:

pip install -U --upgrade-strategy only-if-needed django-reversion

Nothing to do with django-reversion, this is just how pip works. The
default behaviour is a little surprising, I'll agree.

**Comment by Egregors** [comment]
Oh. You are exactly right. Thanks, and sorry for silly question.

**Comment by etianen** [comment]
You're not the first to ask it! :P Compared to npm (nodejs) and cargo
(rust), pip is starting to feel a bit inadequate.
