### ISSUE TITLE
Problem when upgrading from 2.0.8 to 2.0.9

### ISSUE THREAD

**Issue by jfscyberpub** [etianen/django-reversion#658]
Hello,

I use Django 1.10.7 with python 2.7 and when I updgrade the django-reversion package from 2.0.8 to 2.0.9, I got this error when I add or update an entry: 

> invalid literal for int() with base 10: 'None'

Here is the problem:

![selection_130](https://user-images.githubusercontent.com/23479272/29134484-c439a66e-7d04-11e7-9767-11770c4d48f2.png)

**Comment by r3m0t** [comment]
I'm also seeing this. It's when you have an inline with a OneToOneField and reversion is set to follow that field.

**Comment by jfscyberpub** [comment]
Hello r3m0t,

How did you solve your issue ?
Thank you.

**Comment by r3m0t** [comment]
I'm downgrading!

**Comment by jfscyberpub** [comment]
That's exactly what I did. But I'd like to upgrade :(

**Comment by etianen** [comment]
I'm having a hard time tracking down the cause of this, but I may have
pushed a solution to the master branch.

Could you please try installing the github master, and let me know if it's
fixed / differently broken?

pip install -e git+git://github.com/etianen/django-reversion.git

**Comment by jfscyberpub** [comment]
Hello @etianen 

I installed Reversion from your last commit and it's not working. Here is what I get:
![selection_133](https://user-images.githubusercontent.com/23479272/29280264-8ac9ccd2-80e8-11e7-97e0-87f2934fad37.png)

![selection_132](https://user-images.githubusercontent.com/23479272/29280241-72556b70-80e8-11e7-8bd7-b8310f5534dc.png)

**Comment by etianen** [comment]
I think that your database has some corrupt data in.

Can you run the following in a django shell, and see if the problem goes
away?

from reversion.models import Version
Version.objects.filter(version_id="None").delete()

**Comment by jfscyberpub** [comment]
Hello @etianen 

Are you sure about your last query ? Because when I ran it, I got this error message:

> FieldError: Cannot resolve keyword 'version_id' into field. Choices are: content_type, content_type_id, db, format, id, object, object_id, object_repr, revision, revision_id, serialized_data

Also, shouldn't be `version_id__isnull=True` instead of `version_id="None"` ?

**Comment by etianen** [comment]
Sorry, I meant:

from reversion.models import Version
Version.objects.filter(object_id="None").delete()


The string "None" is deliberate. I believe that the bug resulted in
incorrect object IDs being inserted into the version database. If the bug
is fixed, then these corrupt entries can still cause crashes.

**Comment by jfscyberpub** [comment]
Hello @etianen ,

It did fix the problem. Should I be worried to run your query in a production environment ?

**Comment by etianen** [comment]
The only thing to (probably) worry about is if you have registered a model
with django-reversion where:

   1. The model has a string primary key.
   2. A valid primary key is the string "None".

The usual warnings about ensuring you have backups apply, of course!

**Comment by etianen** [comment]
v2.0.10 is out with the fix.

**Comment by jfscyberpub** [comment]
Thank you for your help and for the fix :) :+1:
