### ISSUE TITLE
ValueError when trying to review a version

### ISSUE THREAD

**Issue by jfscyberpub** [etianen/django-reversion#659]
Hello,

I found a problem where I got this error message when I try to check a version:

`invalid literal for int() with base 10: 'None'`

After further investigation, found that it's because one of my inline model were not versioned.

So I ended up replacing in reversion/models.py this line (l.80):
`except model.DoesNotExist:`

By this line:
`except (model.DoesNotExist, ValueError):`

It fixed my problem and of course I lost the data in the inline form (which makes sense and I'm totally fine with that).

I thought I'd share this so maybe you could (or not) add this fix.

**EDIT:** I use django 1.10.7 with django-reversion 2.0.8

**Comment by etianen** [comment]
Does this fix the issue you mentioned in your previous email? If so, I'll
get it merged in a bug fix release this coming Monday.

**Comment by etianen** [comment]
I've pushed a fix to master that may help.
