### ISSUE TITLE
AttributeError: 'module' object has no attribute 'VersionAdmin'

### ISSUE THREAD

**Issue by unityliving-saravanan** [etianen/django-reversion#660]
import reversion
from reversion.admin import VersionAdmin

class HouseReversionAdmin(reversion.VersionAdmin):
......
AttributeError: 'module' object has no attribute 'VersionAdmin'

getting above error.

i referenced this issue https://github.com/etianen/django-reversion/issues/100 . Yet issue not resolved.

django : 1.10.7
django-reversion : 2.0.9

**Comment by etianen** [comment]
Don't use: reversion.VersionAdmin

Use just: VersionAdmin

**Comment by unityliving-saravanan** [comment]
Issue Resolved !

**Comment by kambala2018** [comment]
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404
from .models import Board, Topic, Post

def new_topic(request, pk):
    board = get_object_or_404(Board, pk=pk)

    if request.method == 'POST':
        subject = request.POST['subject']
        message = request.POST['message']

        user = User.objects.first()  # TODO: get the currently logged in user

        topic = Topic.objects.create(
            subject=subject,
            board=board,
            starter=user
        )

        post = Post.objects.create(
            message=message,
            topic=topic,
            created_by=user
        )

        return redirect('board_topics', pk=board.pk)  # TODO: redirect to the created topic page

    return render(request, 'new_topic.html', {'board': board})
Please I gets 

url(r'^$', views.home, name='home'

AttributeError: module boards.views has no attribute 'home'

U can reply me on umarkambala@gmail.com

**Comment by etianen** [comment]
Does the views module actually have a "home" function.

Possibly you have a circular import.
