### ISSUE TITLE
Test suite depending on test discovery ordering

### ISSUE THREAD

**Issue by claudep** [etianen/django-reversion#668]
Tests seem to fail currently on Travis on certain configs. My analysis showed that `TestModel` and `TestModelParent` are registered initially in the process of the admin autodiscovery soon in general test setup.
Then you are unregistering models in most tests `tearDown` method. So if your first discovered test is using a mixin class which is registering a model, you'll get a double registration and the test fails. If by chance the first discovered test is not registering a model, it will succeed and unregister any registered model in its `tearDown` and the state is then clean for all subsequent tests.

Does that make sense?

**Comment by etianen** [comment]
Perfect sense, thanks! I've uploaded a fix to master.
