### ISSUE TITLE
History button for a model

### ISSUE THREAD

**Issue by efi-mk** [etianen/django-reversion#670]
Hello,

Thank you very much for the effort you are putting into this.

Is there a way to view a summary for the changes that happened to a model without checking each record, very similar to the history button that you have per record, but for a model.

Thank you

**Comment by amureki** [comment]
@efi-mk Hi!

You can check out separate package called [django-reversion-compare](https://github.com/jedie/django-reversion-compare), which has a basic functionality of comparing records.

And based on this package in my project I created history view for checking list of changes happened to a record.

Hope this helps you!

**Comment by etianen** [comment]
Not built in, no.

You could write your own using the django-reversion API. It shouldn't be
too hard.

On 30 September 2017 at 10:54, Efi Merdler-Kravitz <notifications@github.com
