### ISSUE TITLE
Not saving revision

### ISSUE THREAD

**Issue by billytotochan** [etianen/django-reversion#671]
I was wonder if I have to override each model save() method to use the reversion module or not.

In the models.py

`from django.db import models`
`import reversion`

`@reversion.register()`
`class YourModel(models.Model):`

and i run `python manage.py createinitialrevisions` .

I saw

`Creating revision for your model`
`- Created 0 / 0`

But when I created a model,
then updated it twice by changing some field.

`from reversion.models import Version`
`versions = Version.objects.get_for_object(instance)`

return a empty queryset for me.

Did I miss something ?
Or I have to manually add `with reversion.create_revision():` for save() method of each model?

**Comment by etianen** [comment]
In order to save a revision, you need to wrap all calls to save() with
reversion.create_revision().

**Comment by billytotochan** [comment]
It means I have to override all models .save() method by

`def` save():`
`    with reversion.create_revision():`
`       blablabla`

I thought once I have registered and init a revision and it will automatically do it for me.
Or there exists some method like the above?

**Comment by etianen** [comment]
If you are just using the admin integration, then it will all just work
with no further effort.

If you are saving revisions in front end code, then consider using
RevisionMiddleware.

http://django-reversion.readthedocs.io/en/stable/middleware.html
