### ISSUE TITLE
Multi Table inheritance in Admin problem

### ISSUE THREAD

**Issue by platico** [etianen/django-reversion#677]
So I have a multi table inheritance of type:

```
class TypeA:
       smth = models.CharField()

 class TypeB(TypeA):
      smth1 = models.CharField()

  class TypeC(TypeA):
      smth2 = models.CharField()
```
and I register them in admin in order to have admin integration. I also add `typea_ptr` in the follow arrays of TypeB and TypeC in order to follow the parent class. But when I create a new revision it normally appears in 'History' page of TypeA but not in TypeB and TypeC. Do you have any idea what it might be?

**Comment by etianen** [comment]
Are all three models registered with the admin?

When you save a TypeA, which admins does it appear in?
What about a TypeB?
What about a TypeC?

**Comment by platico** [comment]
Yes they are registered because when I run `createinitialrevision` their initial revisions are created and their initial revision appears on admin panel history.

I forgot to mention that there is also a TypeD class where typeA has a foreign key to it. The problem is that when I create a revision for TypeD object, the revision appears in TypeA, but not in TypeB and TypeC. Normally they should appear as the revision is done recursively for inherited objects, right?

**Comment by etianen** [comment]
Sorry, can you also answer these?

When you save a TypeA in the admin, which admins does it appear in?
When you save a TypeB in the admin, which admins does it appear in?
When you save a TypeC in the admin, which admins does it appear in?

**Comment by platico** [comment]
Sorry for the misunderstanding. So when I save TypeA, a new revision is appears in TypeA but not in TypeB or TypeC

**Comment by etianen** [comment]
Surely that's the expected behavior? All TypeA instances are not TypeB or
TypeC.

Here's what should happen:

Saving a TypeA should create a new revision in TypeA.
Saving a TypeB should create a new revision in TypeA and TypeB.
Saving a TypeC should create a new revision in TypeA and TypeC.

You could register TypeA with follow=["typeb", "typec"]. That would mean
that if you save an existing TypeA that happens to be a part of a TypeB or
TypeC instance, it would still show up in the relevant admin.

**Comment by platico** [comment]
Ok as you said the problem was that I didn't include in the "follow" dict the reverse relationship, so it's solved! Maybe you should include in the documentation, in the info box that you mention about the "parent_ptr" that we should include the reverse relationship, too. Thanks again for the help I appreciate it!
