### ISSUE TITLE
MySQL error when performing rollback

### ISSUE THREAD

**Issue by jamesmalone** [etianen/django-reversion#683]
Seem to get a MySQL error with the latest reversion (2.0.11) when performing an UNDO to restore previously deleted objects:

ProgrammingError: (1064, You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near varchar(191))\n WHERE\n V.db = default AND\n  at line 4)

I'm running MySQL version 5.7.13

Thanks!

**Comment by etianen** [comment]
I've just pushed a fix to master. Can you confirm it works, and I'll push the fix to PyPi.

**Comment by etianen** [comment]
Fixed in 2.0.12
