### ISSUE TITLE
AttributeError: 'Section' object has no attribute 'section_ptr'

### ISSUE THREAD

**Issue by platico** [etianen/django-reversion#686]
I use multi-table inheritance and I keep track of changes for the following structure:

```
@reversion.register(follow=('emailsection', 'linkssection', ))
class Section(models.Model):
   pass

@reversion.register(follow=('section_ptr', ))
class EmailSection(Section):
   pass

@reversion.register(follow=('section_ptr', ))
class LinksSection(Section):
  pass
```

I have also implemented a custom page where the user can create revision using:
```
 with reversion.create_revision():
    object.save()
    reversion.set_user(request.user)
    reversion.set_comment(comment)
```
where object is a related object that is saved in a revision along with all the related objects (including the Section, EmailSection and LinksSection.

Also in the same page the user can revert to a revision using:
```
  revision = Revision.objects.get(id=revision_id)
  revision.revert(delete=True)
```

but when reverting I get error `AttributeError: 'Section' object has no attribute 'section_ptr'`

The specific traceback I get is:

```
  File "/Users/platico/PycharmProjects/news-service/src/configs/ajax.py", line 51, in revert_to_revision
    revision.revert(delete=True)
  File "/Users/platico/PycharmProjects/news-service/src/lib/python2.7/site-packages/reversion/models.py", line 91, in revert
    collector.collect([item for item in current_revision if item not in old_revision])
  File "/Users/platico/PycharmProjects/news-service/src/lib/python2.7/site-packages/django/db/models/deletion.py", line 212, in collect
    parent_objs = [getattr(obj, ptr.name) for obj in new_objs]
AttributeError: 'Section' object has no attribute 'section_ptr'
```

**Comment by platico** [comment]
The problem is noticed when I try to revert to a revision that contains objects (EmailSection or LinksSection objects) that have not been registered to a revision before.

As you can see in the traceback, reversion sends in .collection() all the objects that need to be deleted: https://github.com/etianen/django-reversion/blob/de5862a60e8fcfc9c14634dd51e004a0420a50b5/reversion/models.py#L91)

But, in the `.collect()` function the objects that are passed are not only the child objects, but also the parent objects. In my case it sends the EmailSection objects but also the Section objects, too.The problem is that within the `.collect()` function, it searches for a specific field, which in our case is `section_ptr` and exists only in the EmailFeed objects, so the error is thrown. 

As you can see in line 202 of deletion.py in django project (https://github.com/django/django/blob/d2afa5eb2308e672b6313876856e32e2561b90f3/django/db/models/deletion.py#L202),
 the function searches for the attribute `section_ptr` which exists only in the EmailSection and LinksSection objects and not in the Section objects

**Comment by platico** [comment]
**Update:** It seems like the problem exists in the version of Django I use. I will update the version and I will let you know, if it's fixed.

**Comment by bluesurfer** [comment]
@platico @etianen 

I had this exact same problem but I am using the latest version of Django 2.0.6. I really don't understand why is this happening (cannot replicate with a unit test). 

In the end, I decided to customize the `revision.revert` method as follows:

```
def revert(revision, delete=True, keep_parents=False):
    # Group the models by the database of the serialized model.
    versions_by_db = defaultdict(list)
    for version in revision.version_set.iterator():
        versions_by_db[version.db].append(version)
    # For each db, perform a separate atomic revert.
    for version_db, versions in versions_by_db.items():
        with transaction.atomic(using=version_db):
            # Optionally delete objects no longer in the current revision.
            if delete:
                # Get a set of all objects in this revision.
                old_revision = set()
                for version in versions:
                    model = version._model
                    try:
                        # Load the model instance from the same DB as it was saved under.
                        old_revision.add(model._default_manager.using(version.db).get(pk=version.object_id))
                    except model.DoesNotExist:
                        pass
                # Calculate the set of all objects that are in the revision now.
                current_revision = chain.from_iterable(
                    _follow_relations_recursive(obj)
                    for obj in old_revision
                )

                items = [item for item in current_revision if item not in old_revision]
                if not keep_parents:
                    items = [item for item in items if not item._meta.parents]

                # Delete objects that are no longer in the current revision.
                collector = Collector(using=version_db)
                collector.collect(items)
                collector.delete()
            # Attempt to revert all revisions.
            _safe_revert(versions)
```

Basically, I added a `keep_parents` parameter. If `False` then ignore parent items from deletion. Hope this helps.
