### ISSUE TITLE
REST operation don´t save coments

### ISSUE THREAD

**Issue by jvp2003d** [etianen/django-reversion#692]
Inside the admin django-reversion works fine. But from REST api operation don´t save any comment in table reversion_revision
![image](https://user-images.githubusercontent.com/7420074/34258116-d5553bae-e65c-11e7-9945-0a938b43bb6c.png)

**Comment by etianen** [comment]
The comments in the admin are generated by the django admin class, and there is no provided way to access this functionality outside of the admin.

If you want to include comments in your revision, you will need to add them yourself using reversion.set_comment("Comment here.") somewhere in your view.

**Comment by jvp2003d** [comment]
Ok, perfect. Thanks for your help
