### ISSUE TITLE
Reversion Middleware issue when migrating to Django 2

### ISSUE THREAD

**Issue by samifahed** [etianen/django-reversion#693]
Hi,

When migrating from the `MIDDLEWARE_CLASSES` django setting to the `MIDDLEWARE` setting, django calls `__init__` and `__call__` methods on the middleware instead of `process_request` and `process_response`.
In the case of `RevisionMiddleware`, the behavior is different when we use the `MIDDLEWARE` setting instead of the `MIDDLEWARE_CLASSES` one, because the [create_revision in the views](https://github.com/etianen/django-reversion/blob/51abcac5db7f3b73eb1503c3bcf591b9f7240523/reversion/views.py#L22) rolls back when the status code of the http request > 400, however the old behavior uses the [create_revision context manager](https://github.com/etianen/django-reversion/blob/51abcac5db7f3b73eb1503c3bcf591b9f7240523/reversion/revisions.py#L297) which doesn't roll back the transaction of what happened in the request.

One is used in the `__init__` and the other is used in the `process_request` in the [RevisionMiddleware](https://github.com/etianen/django-reversion/blob/master/reversion/middleware.py#L6).

What I see is that the migration from one setting to the other is not consistent, which makes the behavior with Django 2 different.

Is this intended to be different?

**Comment by etianen** [comment]
Oops. Good spot.

The behavior shown by the MIDDLEWARE setting is the intended behavior. It
looks like the handling of >= 400 status codes was not added correctly to
RevisionMiddleware for the MIDDLEWARE_CLASSES pathway.

I'm not sure if it's worth doing anything on this, however. The old
behavior is now deprecated, and changing it now will only break people's
code.

**Comment by samifahed** [comment]
I see, okay then we will adapt to the new code :) thanks!

**Comment by syphar** [comment]
for future reference: the behaviour to revert transactions for status codes >= 400 was removed in #878 and version 4.0.0
