### ISSUE TITLE
How can I create revisions without calling obj.save() for each model?

### ISSUE THREAD

**Issue by mehtadev17** [etianen/django-reversion#695]
How do I create a revision without saving the object? I create a version for all my models during a specific action from the user. There are too many objects to save at that time which causes the process to be slow. How can I create revisions without calling `obj.save()` for each model?

**Comment by etianen** [comment]
Use this:

reversion.add_to_revision(obj)

Behind the scenes, the django signal handlers call this on object save().

More API methods:

http://django-reversion.readthedocs.io/en/stable/api.html#revision-api

**Comment by mehtadev17** [comment]
@etianen Thanks! However, I would like to generate revisions but not save them to the db. Something along the lines of `reversion.add_to_revision(obj, commit=False)`

**Comment by etianen** [comment]
Generate revisions but not save them to the db? That doesn't really make
sense to me.

The database is where revisions are stored. If they're not saved to the DB,
then what is the point?

**Comment by mehtadev17** [comment]
My use case is to show them the revisions as a draft before saving it. I am generating a diff of all the objects between revisions and showing them a list of changes.

**Comment by etianen** [comment]
I'm afraid that the entire revision mechanism is based around saved
Revision and Version models. You'll need to implement this using some other
mechanism, probably by comparing the live models in the database to the
last revision.

**Comment by mehtadev17** [comment]
Yep, sounds good. 
Thanks for the quick responses.

**Comment by shaneikennedy** [comment]
Will add_to_revision() create a Version for a new object or only for existing objects?
