### ISSUE TITLE
Data is corrupted

### ISSUE THREAD

**Issue by ebsaral** [etianen/django-reversion#696]
Hello,

When I traceback the error at `reversion/models.py` in `_object_version`, I see that this line produces corrupted data: `data = force_text(data.encode("utf8"))`

The data is like this:

`u'[{"pk": 82, "model": "accounting.incominginvoice", "fields": {"vendor_bank_name": "", "active": true, "update_date": "2018-01-15T16:19:02.343Z", "due_date": "2018-01-05", "notes": "", "set_paid_by": null, "invoice_address": null, "subtotal": -9203.73, "vendor_invoice_address": "", "client": 103, "approved_by": 890, "is_paid": false, "created_by_scheduler": false, "vendor_swift_bic": "", "is_approv'`

As you can see at the field `is_approved`, data gets corrupted.

Any guess why it can be like this?

**Comment by etianen** [comment]
Are you certain that Python has not split the string on multiple lines to
display it in your console?

There is nothing in that code snippet that will truncate the string.

Is the data stored truncated in your database?

**Comment by ebsaral** [comment]
@etianen You were right about data not being fully displayed. The issue is related to deserialization. I debugged the issue by putting a debugger in `reversion.models.Version._object_version` do see the detailed error. 

So, my model is like this:

```
class Company(models.Model):
    incorporation_date = models.DateField(null=True, blank=True)
```

but when I am the line `return list(serializers.deserialize(self.format, data, ignorenonexistent=True))[0]`, I print `data` and I see that `data` contains this field as like this: `"incorporation_date":"2014-12-04T00:00:00"` so of course it causes `DeserializationError: [u"'2014-12-04T00:00:00' value has an invalid date format. It must be in YYYY-MM-DD format."]`. This field was never touched or altered. 

Do you have any guess why this could be saved like this? And do you have any idea how to solve this? 

Thanks.

**Comment by ebsaral** [comment]
Okay, I found the conversation in this issue: https://github.com/etianen/django-reversion/issues/61
So it's fucking Django. :/ Thanks.

**Comment by etianen** [comment]
As far as I can tell, yes it's a Django bug. 😒
