### ISSUE TITLE
Roadmap for v2.0.13

### ISSUE THREAD

**Issue by passuf** [etianen/django-reversion#698]
Without wanting to push you, is there a roadmap for the release of the next version?
It would be very nice if PR #691 would be included in an official release, as my project depends on it.

Thanks for all your work!

**Comment by etianen** [comment]
Okay, I guess you **did** contribute the PR, and it **is** a useful addition, and I really **should** have some sort of release policy! 😛 

Instead, I mostly release after a big feature has landed, or when someone asks me to do so.

django-reversion v2.0.13 has landed on PyPi. Enjoy! Thanks for the PR!

**Comment by passuf** [comment]
Wonderful, thank you very much! :D
