### ISSUE TITLE
Why ignore version in _add_to_revision function when explicit = False ?

### ISSUE THREAD

**Issue by yanlong** [etianen/django-reversion#702]
Hi,

I have a model with parent model. When I change the field which belong to the parent model only the first change can be store in the revision. I found the _add_to_revision function ignore non-explicit (explicit = False) versions which I can not figure out why ?

**Comment by etianen** [comment]
When a model is saved by calling it's save() method, it is added to the
current revision. If the model has been registered with any `follow`
arguments, then those relations will also be followed and added to the
revision.

http://django-reversion.readthedocs.io/en/stable/api.html#registration-api

To use multi-table inheritance with django-reversion, you have to register
both the parent and the child model, and for both of them specify the link
to the other model in `follow`.

For example:

class Parent(models.Model):
    pass

class Child(Parent):
    pass

reversion.register(Child, follow=("parent_ptr",))
reversion.register(Parent, follow=("child",))

Have you set up your model correctly?
