### ISSUE TITLE
Edit reason

### ISSUE THREAD

**Issue by pikrzysztof** [etianen/django-reversion#703]
How hard would it be to add a proper implementation of "edit/delete/add reason" which would be visible in the change history?

It could be pretty well emulated by adding an extra text field in every model which users would use change to store edit comments, but it looks like an ugly way of doing it (and you can't have "delete reason" in this case).

Just to be clear, I'm not asking you to implement this feature, I'm just interested in description how to do this and possibly submit a MR later if it's doable.

**Comment by pikrzysztof** [comment]
I think `set_comment` does it, but you can't set your comment when editing objects through Django Admin page interface.

**Comment by etianen** [comment]
Oh, I see! :)

I think that you could implement this by overriding the following hooks in
Django admin:

   - get_form() - add a "comment" field to the form.
   - get_fieldsets() - add the "comment" field to the fieldsets.
   - construct_change_message() - Get the comment from the form data and
   return it.

The actual implementation is up to you. If you make something worth
sharing, consider open-sourcing your subclassed VersionAdmin on GitHub and
PyPi. I'm happy to link to django-reversion extensions.

**Comment by pikrzysztof** [comment]
Cool, thank you very much for your help. I will do this in the following weeks.
