### ISSUE TITLE
Change history doesn't record deletions

### ISSUE THREAD

**Issue by pikrzysztof** [etianen/django-reversion#704]
Deletions are not visible in the change history. Restoring deleted stuff is not obvious too. The only way we can presume that a revert was a restoration is when we see an entry which reverts to a latest version.

See the change history of an object deleted and reverted twice.
![screenshot from 2018-02-12 18-25-58](https://user-images.githubusercontent.com/3964215/36112800-a5c91a14-1022-11e8-8e49-0953c3f40a8a.png)

**Comment by etianen** [comment]
Deletions are not recorded in the database. See here:

https://github.com/etianen/django-reversion/issues/164

In general, reversion only cares about saving snapshots of models, and
restoring those snapshots. It's not a full audit trail application. It
tried to be once (see above issue), and it was a very bad idea.

If you want to include deletions in the change history, consider writing a
custom object_history that includes the admin.LogEntry information merged
in.

**Comment by pikrzysztof** [comment]
Oh. Thank you very much and apologies for doing a bad research before asking.

**Comment by etianen** [comment]
Not worries, it's a very common question. :)
