### ISSUE TITLE
Is it possible to store Version.serialized_data in an encrypted format?

### ISSUE THREAD

**Issue by BillBrower** [etianen/django-reversion#705]
I looked for a setting that allow you to specify a subclassed `Version` but I didn't see anything like that. I also looked into the Django serialization formats to see if I could leverage `Version.format` but that seems like a dead end too (I didn't see any way to register a custom serializer so that it could be used with `serializers.serialize`).

Is storing the serialized data in an encrypted format possible at all? 

If not, does the `exclude` parameter on the `register` decorator keep any fields that are listed from being stored in `Version.serialized_data`? I read in issue #387 that excluded fields just get stored as null. Is that still the case? My intention is just to use django-reversion as an audit log, I don't need to be able to rollback so storing sensitive fields as null would work just fine.

**Comment by etianen** [comment]
Using exclude will avoid fields being included in the serialised data. So
it's good for sensitive data (although the data is still in your primary
table, of course!).

Under the hood, django-reversion uses the django serialization framework:

https://docs.djangoproject.com/en/2.0/topics/serialization/

You could use this to write your own custom serializer that subclasses the
json serializer and performs a final emcryption step, and use this for
django-reversion.

**Comment by BillBrower** [comment]
Thanks @etianen! I'll just exclude the fields then since I don't actually need the ability to rollback. It's great to know that I could write a custom serializer if I ever needed to though!
