### ISSUE TITLE
New revision appears when open a recover object view (before saving or changing it)

### ISSUE THREAD

**Issue by alu0100608939** [etianen/django-reversion#706]
Whenever I access a 'recover' view of my objects, there is a change in the database.
A new entry appears in the table revision_reversion with "now" as date_created and blank comment.
This happens even before I do any change or save it.

I think this happens at the line:
`    version.revision.revert(delete=True)`

at VersionAdmin.revisionform_view

I can fix this moving this line inside the 'with' statement. However, I don't know if this is correct.
``` 
def revisionform_view(self, request, version, template_name, extra_context=None):
        try:
            with transaction.atomic():
                # Revert the revision.
                # version.revision.revert(delete=True)  # < ----- Not here
                # Run the normal changeform view.
                with self._create_revision(request):
                    version.revision.revert(delete=True) # <---- But here
```

**Comment by etianen** [comment]
Are you using MySQL MyISSAM tables? Reversion admin needs a working transaction system to avoid doing this.

**Comment by alu0100608939** [comment]
I am sorry, I was using an old version. I updated and worked as expected. 

Thank you for your time, I'm closing this issue.
