### ISSUE TITLE
migrate command does nothing

### ISSUE THREAD

**Issue by famagusta** [etianen/django-reversion#713]
Hi,

I am trying to run the migrations for this project but I get "No migrations to apply" response.
I am using django 1.11 with python 3.6.

Any help would be appreciated.

Thanks & Regards
Robin Philip

**Comment by amureki** [comment]
Hi @famagusta 

Did you add the app into `INSTALLED_APPS` setting?
Make sure, that you follow https://django-reversion.readthedocs.io/en/stable/#installation instructions.

**Comment by famagusta** [comment]
I have done this.

**Comment by amureki** [comment]
@famagusta oh, okay.
Can you, please, run `python manage.py showmigrations` command and provide an output here?
At least parts that are related to `django-reversion` app.

Thank you!

**Comment by famagusta** [comment]
Sorry, my bad. settings file was being overridden by a local settings file. 

@amureki : thanks for the assist.
