### ISSUE TITLE
Support for soft deletable models

### ISSUE THREAD

**Issue by ivissani** [etianen/django-reversion#720]
I recently run into trouble trying to use reversion within an app. The problem, I believe, was due to the fact that I was overriding the default manager of a model to filter some instances in a similar way as [SoftDeletableModel](https://django-model-utils.readthedocs.io/en/latest/models.html#softdeletablemodel) does. 
As far as I could track it, the error is located in the `_save_revision` method. Specifically the variable `model_db_existing_pks` is populated by checking the tracked objects' primary keys against those objects that exists in the DB. The problem is that this check is done by querying the DB using the `_default_manager` for each model. As you can guess, when the default manager filters out some instances, those instances' PKs will not survive the filter.
I wonder whether it would be more appropriate to use the `_base_manager` instead which is [not allowed to filter out any instances ](https://docs.djangoproject.com/en/2.0/topics/db/managers/#don-t-filter-away-any-results-in-this-type-of-manager-subclass).
This behaviour could at least be made explicit in the documentation. I believe this could save time to some other folks.
As you can see this is a question not an issue really.

**Comment by etianen** [comment]
Did you run into an actual exception, or did you just get incorrect results
back.

Yes, I think a pull request to use _base_manager is probably a good idea.
