### ISSUE TITLE
GenericRelation as a ManyToMany?

### ISSUE THREAD

**Issue by bluesurfer** [etianen/django-reversion#732]
I would like to version a `GenericRelation` field. Consider the following models: 

```
@reversion.register(fields=['url', 'tags'], follow=['tags])
class Bookmark(models.Model):
    url = models.URLField()
    tags = GenericRelation(TaggedItem)

@reversion.register(fields=['tag'])
class TaggedItem(models.Model):
    tag = models.SlugField()
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
```

Every time I create a revision for `Bookmark` I would expect to found the following `serialized_data` inside `Version`:

`{'pk': 1, 'fields': {'url': 'someurl', 'tags': ['tag1', 'tag2']}}`

Plus when I change the `slug` field in the `Tag` I am expecting to see a new revision also in `Bookmark` since I define the `follow` option.

What I am getting instead is this:

`{'pk': 1, 'fields': {'url': 'someurl'}}`

There's no `tags` field! Furthermore any change on slug in `TaggedItem` is ignored from the revisions of `Bookmark` (but there exists a revision for `TaggedItem`).

This is my first time using this library. I probably must have misunderstood something.

**Comment by etianen** [comment]
A Version represents a single serialized model. Multiple Versions are
grouped together in a Revision.

So, when you create a revision for Bookmark, you will get a single Revision
object containing a Version object for the bookmark, plus several other
Version objects for each of the followed tags.

To make the same thing work when you save TaggedItem, you also need to add
follow=["content_object"] to the register() call for TaggedItem.
