### ISSUE TITLE
Revert only a subset of fields

### ISSUE THREAD

**Issue by bluesurfer** [etianen/django-reversion#734]
Me again, sorry 😄 

I would like to revert only a subset of specific fields and ignore the others. As the docs states, that is achieved by filling the `fields` argument during the registration step. Ok!

But when trying to revert the model I get some integrity errors because `django-reversion` sets to none all the fields that I did not specify in the `fields`argument during registration.

I am not interested in recovering an object once it gets deleted but just to provide a field-specific versioning. By now I guess I will have to define a custom revert method and use the `field_dict` method inside `Version` and use it to retrieve the field version data.

**Comment by etianen** [comment]
django-reversion uses the django serialization framework to do it's heavy
lifting.

If this is how the serialization framework does it's thing, then I guess
that's how reversion works too.

I think the fields/exclude functionality is there to support excluding
fields that contain empherameral state. It doesn't seem that useful in
reality.

**Comment by bluesurfer** [comment]
@etianen 

The serialization framework seem to offer the option to select only a subset of fields ([see here]).(https://docs.djangoproject.com/en/2.0/topics/serialization/#subset-of-fields). And that is what django-reversion does when specifying the fields argument (looking at `serialized_data`). 

The problem is when reverting: you are **obliged** to specify all the required fields of a model otherwise you would run into integrity errors. Furthermore, when reverting the excluded fields are not ignored by the reversion but considered to be `none`. I think that this functionality is a little misleading.

**Comment by etianen** [comment]
I agree, it's rarely useful functionality. It was only really included
because the Django serialization framework supported it.

I guess the big question is: why does the serialization framework even have
this feature?
