### ISSUE TITLE
How to store the timestamp and author of a delete operation?

### ISSUE THREAD

**Issue by kklingenberg** [etianen/django-reversion#735]
I'm requesting advise :grimacing:. I need to be able to tell who deleted an object, and when it happened. I'm considering three options:

1. Fork and add the `post_delete` signal that would create a revision, where the corresponding version would be tagged as a delete. An attempt at this can be seen [here](https://github.com/kklingenberg/django-reversion/commit/88a35040a927922d050ce9d228d3700d2caa4f4d). However, I believe this goes against the scope of django-reversion, since the `get_deleted` queryset method already deals with half of what I need, and this would overlap with it somewhat.
2. Inherit from `reversion.models.Version` and add a foreign key to the user (the author of the deletion) and an extra timestamp, so that a previous version can be tagged as 'the last one before a delete' and can be annotated with what I need. I'd also need to handle the `post_delete` for each registered model. I dislike this because the table inheritance will create another version table.
3. Fork and allow users to provide their own version model, by making `Version` abstract and providing a default concrete model. This would require app configuration though, and I think that's also a major change from the current status.

I'd appreciate any guidance on this, and am willing to submit a PR for whichever approach you're willing to include in the library, if any.

**Comment by etianen** [comment]
There's no need to add a foreign key from Version to User. Such a foreign
key already exists on Revision, so you should use that.

A good solution is to save a revision in the pre_delete signal of a model,
and tag that revision with the user. This means that you can tell who
deleted the object by looking at the user associated with the last revision
of the object.

**Comment by kklingenberg** [comment]
Aha! I see :smile: 

Thank you very much! I was blocked on tagging the version as deleted, but `VersionQuerySet.get_deleted()` does that

**Comment by depaolim** [comment]
I connected a pre_delete signal for the model
In the connected function I issued an explicit reversion.add_to_revision(instance)
But I can't get any stored version/revision
The reason is that reversion._save_revision "Only save versions that exist in the database." (as the comment states)
Am I missing something?
Thank you

**Comment by kklingenberg** [comment]
I checked again and found your problem (and a bug in my setup). What I was doing was:

```python
def pre_delete_receiver(sender, instance, **kwargs):
    with reversion.create_revision():
        reversion.add_to_revision(instance)
```

This was working, until I nested the original `delete()` in a revision block. Then, the `_save_revision` ocurred after the final frame was popped, and by then the object wasn't in database anymore. So you're right @depaolim, I believe, in that by itself adding to the revision in `pre_delete` won't help. Now I see that the correct receiver should have been:

```python
def pre_delete_receiver(sender, instance, **kwargs):
    if reversion.is_active():
        reversion.add_to_revision(instance)
```

And that doesn't work.

**Comment by depaolim** [comment]
if I comment the "filter logic" in the following line:

https://github.com/etianen/django-reversion/blob/master/reversion/revisions.py#L229

and I transform in:
`
                pks  # model._base_manager.using(db).filter(pk__in=pks).values_list("pk", flat=True),
`

All the actual existing test cases run correctly
... so I'm not sure to understand the rationale behind that check... maybe a protection against race-conditions?

Anyway, with that simple modification, the following new test case now passes
`
class TestDeleteModel(TestModelMixin, TestBase):
    model = TestModel

    @staticmethod
    def mock_pre_delete(instance, using, **kwargs):
        reversion.add_to_revision(instance)

    def setUp(self):
        super(TestDeleteModel, self).setUp()
        django.db.models.signals.pre_delete.connect(self.mock_pre_delete, sender=self.model)
        self.model.objects.create(id=987, name="created")  # no revision

    def tearDown(self):
        super(TestDeleteModel, self).tearDown()
        django.db.models.signals.pre_delete.disconnect(self.mock_pre_delete, sender=self.model)

    def test(self):
        instance = self.model.objects.get(id=987)
        with reversion.create_revision():
            instance.delete()
        self.assertEqual(
            list(Version.objects.get_for_model(self.model).values_list("object_id", "serialized_data")), [
                (
                    "987",
                    '[{"model": "test_app.testmodel", "pk": 987, "fields": {"name": "created", "related": []}}]'
                ),
            ])
`

I'd appreciate any hint on this, and I am willing to submit a PR if you prefer

**Comment by etianen** [comment]
It's to protect against models being added and removed in the same
revision.

Now I think about it, storing deletion information probably won't work
using reversion. I'd suggest making your own model to hold this info, and
connecting to the post_delete signal of the model you want to track
deletions for.
