### ISSUE TITLE
How to modify a saved version?

### ISSUE THREAD

**Issue by wolfgang-reutz** [etianen/django-reversion#737]
Hi,

I did some googling and could not find a hint how to deal with this problem I have:

I have some object with a valid_from and a valid_thru attribute and a name and shortname.

Usecase:

- User x changes the name or the shortname
- this change gets saved with create_revision and I now have 2 saved versions of this object
- now comes the tricky part: As this is a new version of the same object, the newest version should have a valid_from date time **from** now, but the old version should get a valid_thru date time set too
- I need this to work with the current versions, but have a history with dates to calculate which version was current to a given point in time

What I found out so far:
I can get the different versions, work with them and manipulate the serialized_data directly by converting the string to a dictionary, change a field and then convert it back to JSON and overwrite serialized_data

Is this the recommended way to change a version or is there a better way to do it?

**Comment by etianen** [comment]
I don't think you want to be modifying previous revisions, or using them
for anything other than recovering past versions of an object.

**Comment by Netizen29** [comment]
I think you can also find an easier solution to your problem.
You should know that when creating a revision, you can access the date of this revision [thanks to its metadata](http://django-reversion.readthedocs.io/en/stable/api.html#revision-metadata). Your valid_from and valid_thru fields seem redundant.
