### ISSUE TITLE
Support for multlanguage tables?

### ISSUE THREAD

**Issue by chrda81** [etianen/django-reversion#740]
Hi,
I'm trying to implement a multilanguage package in my project, while using django-reversion to keep track of any model changes. Is it possible to use django-reversion with a splitted model? Let's say I have a model 'News' with columns title, body, date, author, published, and archived. By using the package django-parler for multi language support for columns title and body, it separetes this two columns in its own tables and sets references in the original model. Would this work with django-reversion? If yes, is there an example project/snippet? Thanks.

Regards,
Sky

**Comment by etianen** [comment]
Use the "follow" argument when registering your model.

https://django-reversion.readthedocs.io/en/stable/api.html#registration-api

It will allow any relations you specify to be included in the revision.
