### ISSUE TITLE
How to call fields from Revision model in a custom  inherited model?

### ISSUE THREAD

**Issue by photonauta35** [etianen/django-reversion#741]
For example, if I need call `date_created` from Revision in my admin.py as list_display field? Is there possible? 

```
@admin.register(Container)
class ContainerAdmin(CompareVersionAdmin, admin.ModelAdmin):
    list_display = ('date_created', 'id_auto_series', 'id_human', 'uuid', 'title', 'description', 'description_level',)
    filter_horizontal = ('items', 'container_child')
```

```
 ERRORS:
django_1    | <class 'collection.admin.ContainerAdmin'>: (admin.E108) The value of 'list_display[0]' refers to 'date_created', which is not a callable, an attribute of 'ContainerAdmin', or an attribute or method on 'collection.Container'.
```

![selecao_038](https://user-images.githubusercontent.com/641411/42707533-dce66e7a-86b0-11e8-8e9c-3aac9ec073d5.png)

**Comment by etianen** [comment]
Version and Revision are just database models.

for version in Version.objects.get_for_object(container):
    print(version.revision.date_created)

**Comment by photonauta35** [comment]
hi @etianen, thanks for answer here. I'm not sure about the clarity of topic, so I'm sorry, let me ask again. 

My question is: how can we call a property of Revision model after a extended model one (please, correct me if I has some misunderstanding). 

1. I have a model called Post in my `model.py` file. This model has reversion register to be extended from Revision model, right? 

```
@reversion.register()
class Post(models.Model):
    """Used to store posts"""
    title = models.CharField(
        max_length=256)
    content = models.TextField(
        null=True,
        blank=True)
  
    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'
```

2. So, in `admin,py` from the same model, I wanna call field in `list_display` to be listed, but field from Revision model seems dont be callables. 

```
@admin.register(Post)
class PostAdmin(CompareVersionAdmin, admin.ModelAdmin):
    list_display = ('id', 'date_created', 'title')
    search_fields = ['__all__']
```

Error message: 

```
 ERRORS:
django_1    | <class 'post.admin.PostAdmin'>: (admin.E108) The value of 'list_display[1]' refers to 'date_created', which is not a callable, an attribute of 'PostAdmin', or an attribute or method on 'post.Post'.
```

So, despite of 'date_created' be a field from Revision and Revision be "extended" in Post, I dont just call 'date_created' in presets like `list_display`.

What I misunderstand here?

I tryed to create a function in my model, but again 'date_created' is not a valid field. 

```
    def get_date_created(self):
        return self.date_created
```

```
AttributeError: 'Post' object has no attribute 'date_created'
```

This has no effect at all too: 

```
    def get_date_created(self):
        Version.objects.get_for_object(self)
        return Version.revision.date_created
```

**Comment by etianen** [comment]
When you register a model with django-reversion, it doesn't extend the
model. So the Revision fields will not be available on your model.

Your get_date_created method has a type. The second "version" should be
lowercase, as below:

def get_date_created(self):
        Version.objects.get_for_object(self)
        return version.revision.date_created

**Comment by etianen** [comment]
Oh, and another correction:

def get_date_created(self):
        return Version.objects.get_for_
object(self).order_by("id").first().revision.date_created

It would be a lot easier to just add a "date_created" field to your model
directly, however.

**Comment by photonauta35** [comment]
> When you register a model with django-reversion, it doesn't extend the model. So the Revision fields will not be available on your model.

ok! I got it now. Thank you. 

 
> def get_date_created(self):
>        return Version.objects.get_for_object(self).order_by("id").first().revision.date_created

This works pretty well! Thank you again.
