### ISSUE TITLE
Getting exception while resolving variable

### ISSUE THREAD

**Issue by diogosimao** [etianen/django-reversion#743]
- Running Django 2.0 on Apache 2.4 (modwsgi 3.4+)
- Latest django-reversion

Currently getting _Gateway Timeout_ while trying to recover.

Only clues are DEBUG logs entries:

> 
> Exception while resolving variable 'non_field_errors' in template 'reversion/change_list.html'
> Exception while resolving variable 'errors' in template 'reversion/change_list.html'
> Exception while resolving variable 'is_multipart' in template 'reversion/change_list.html'
>

**Comment by etianen** [comment]
Do you have a stack trace for those exceptions?

**Comment by diogosimao** [comment]
It looks like I have got some:

> Exception while resolving variable 'non_field_errors' in template 'reversion/change_list.html'.
> Traceback (most recent call last):
>   File "/home/user/public/user_env/lib/python3.5/site-packages/django/template/base.py", line 835, in _resolve_lookup
>     current = current[bit]
> TypeError: 'NoneType' object is not subscriptable
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/user/public/user_env/lib/python3.5/site-packages/django/template/base.py", line 843, in _resolve_lookup
>     current = getattr(current, bit)
> AttributeError: 'NoneType' object has no attribute 'non_field_errors'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/user/public/user_env/lib/python3.5/site-packages/django/template/base.py", line 849, in _resolve_lookup
>     current = current[int(bit)]
> ValueError: invalid literal for int() with base 10: 'non_field_errors'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/user/public/user_env/lib/python3.5/site-packages/django/template/base.py", line 856, in _resolve_lookup
>     (bit, current))  # missing attribute
> django.template.base.VariableDoesNotExist: Failed lookup for key [non_field_errors] in None

**Comment by diogosimao** [comment]
Apache also logs: 

> Timeout when reading response headers from daemon process

[Applying](https://serverfault.com/questions/514242/non-responsive-apache-mod-wsgi-after-installing-scipy/514251#514251) 

`WSGIApplicationGroup %{GLOBAL}`

won't solve!

**Comment by diogosimao** [comment]
Hi!

Maybe this stack trace?

> 
> DEBUG 2019-01-15 17:52:30,705 base 10734 140605078923008 Exception while resolving variable 'back' in template 'reversion/change_list.html'.
> Traceback (most recent call last):
>   File "/env/lib/python3.5/site-packages/django/template/base.py", line 835, in _resolve_lookup
>     current = current[bit]
>   File "/env/lib/python3.5/site-packages/django/template/context.py", line 83, in __getitem__
>     raise KeyError(key)
> KeyError: 'back'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/env/lib/python3.5/site-packages/django/template/base.py", line 841, in _resolve_lookup
>     if isinstance(current, BaseContext) and getattr(type(current), bit):
> AttributeError: type object 'RequestContext' has no attribute 'back'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/env/lib/python3.5/site-packages/django/template/base.py", line 849, in _resolve_lookup
>     current = current[int(bit)]
> ValueError: invalid literal for int() with base 10: 'back'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/env/lib/python3.5/site-packages/django/template/base.py", line 856, in _resolve_lookup
>     (bit, current))  # missing attribute
> django.template.base.VariableDoesNotExist: Failed lookup for key [back] in [{'None': None, 'False': False, 'True': True}, {'show': True, 'choices': [{'link': '?data__year=2018&nome=dia%25+mante&q=', 'title': '2018'}, {'link': '?data__year=2019&nome=dia%25+mante&q=', 'title': '2019'}], 'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7fe1095beae8>>}]

**Comment by etianen** [comment]
Something is not right with your setup. A missing template variable should
not raise an exception.

Is this actually causing the web page to crash, or just a debug-level log?
