### ISSUE TITLE
Import of django.contrib.admin.models.LogEntry in reversion.models causes startup error

### ISSUE THREAD

**Issue by wylee** [etianen/django-reversion#744]
The top level import of `django.contrib.admin.models.LogEntry` in the module `reversion.models` causes a startup error in Django projects that don't include `django.contrib.admin` in `INSTALLED_APPS`:

> RuntimeError: Model class django.contrib.admin.models.LogEntry doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

Perhaps this import could moved into the `Revision.get_comment()` method?

--

Affects version 3.0.0

https://github.com/etianen/django-reversion/blob/d4cb8aa5ca383b3d9bf57b07598d0e86dc390c2e/reversion/models.py#L10

**Comment by etianen** [comment]
I don't get that issue in my tests, or any of my production code.

Can I see your traceback?

**Comment by wylee** [comment]
I should have mentioned also that I'm using Django 2.0.8. Here's the traceback from running `manage.py test`:

> Traceback (most recent call last):
>   File "./manage.py", line 20, in <module>
>     execute_from_command_line([sys.argv[0]] + remaining_args)
>   File "/project/virtualenv/lib/python3.5/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
>     utility.execute()
>   File "/project/virtualenv/lib/python3.5/site-packages/django/core/management/__init__.py", line 347, in execute
>     django.setup()
>   File "/project/virtualenv/lib/python3.5/site-packages/django/__init__.py", line 24, in setup
>     apps.populate(settings.INSTALLED_APPS)
>   File "/project/virtualenv/lib/python3.5/site-packages/django/apps/registry.py", line 112, in populate
>     app_config.import_models()
>   File "/project/virtualenv/lib/python3.5/site-packages/django/apps/config.py", line 198, in import_models
>     self.models_module = import_module(models_module_name)
>   File "/project/virtualenv/lib/python3.5/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 985, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 968, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 697, in exec_module
>   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
>   File "/project/virtualenv/lib/python3.5/site-packages/reversion/models.py", line 10, in <module>
>     from django.contrib.admin.models import LogEntry
>   File "/project/virtualenv/lib/python3.5/site-packages/django/contrib/admin/models.py", line 33, in <module>
>     class LogEntry(models.Model):
>   File "/project/virtualenv/lib/python3.5/site-packages/django/db/models/base.py", line 108, in __new__
>     "INSTALLED_APPS." % (module, name)
> RuntimeError: Model class django.contrib.admin.models.LogEntry doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

**Comment by etianen** [comment]
Oh, I just realized.

You need to add django.contrib.admin to your INSTALLED_APPS setting.

**Comment by wylee** [comment]
That's a possible solution, as I noted above, but not all projects use the Django admin and IMO shouldn't be required to "install" it just to avoid this error.

**Comment by etianen** [comment]
Does moving the import into the get_comment() method actually fix this
error?

If it does, then yes, I guess that's the solution.

**Comment by wylee** [comment]
Good point--moving the import would only work for cases where `Revision.get_comment()` is never used. This is a bit more complex but also more robust:

```diff
diff --git a/reversion/models.py b/reversion/models.py
index bde6c5b..87f0a3e 100644
--- a/reversion/models.py
+++ b/reversion/models.py
@@ -1,13 +1,13 @@
 from __future__ import unicode_literals
 from collections import defaultdict
 from itertools import chain, groupby
+from django.apps import apps
 from django.contrib.contenttypes.models import ContentType
 try:
     from django.contrib.contenttypes.fields import GenericForeignKey
 except ImportError:  # Django < 1.9 pragma: no cover
     from django.contrib.contenttypes.generic import GenericForeignKey
 from django.conf import settings
-from django.contrib.admin.models import LogEntry
 from django.core import serializers
 from django.core.serializers.base import DeserializationError
 from django.core.exceptions import ObjectDoesNotExist
@@ -21,6 +21,23 @@ from reversion.errors import RevertError
 from reversion.revisions import _get_options, _get_content_type, _follow_relations_recursive
 
 
+# On Django >= 1.10, the Django admin change message is used as the
+# revision comment, but only if the Django admin app is installed.
+try:
+    admin_app = apps.get_app_config('admin')
+except LookupError:
+    LogEntry = None
+else:
+    # Additional check to ensure the installed admin app is actually
+    # Django's admin app and not a custom app that uses the "admin"
+    # label.
+    if admin_app.name == 'django.contrib.admin':
+        LogEntry = admin_app.get_model('LogEntry')
+        # Django < 1.10 LogEntry doesn't have a get_change_message method
+        if not hasattr(LogEntry, 'get_change_message'):
+            LogEntry = None
+
+
 def _safe_revert(versions):
     unreverted_versions = []
     for version in versions:
@@ -64,12 +81,10 @@ class Revision(models.Model):
     )
 
     def get_comment(self):
-        try:
+        if LogEntry:
             return LogEntry(change_message=self.comment).get_change_message()
-        except AttributeError:
-            # Django < 1.10
-            # LogEntry dont have `.get_change_message()`
-            return self.comment
+        # Django < 1.10 or Django admin not enabled
+        return self.comment
 
     def revert(self, delete=False):
         # Group the models by the database of the serialized model.
```

**Comment by icseibel** [comment]
I got the same issue in my current project as I'm not using default Django Admin. Is the implementation mentioned above going to be released soon?

**Comment by etianen** [comment]
I'll review a merge request for this. I don't have time to implement it
myself.

**Comment by codearm-docker** [comment]
No that the PR has been merged I think this issue can be closed :smiley:
