### ISSUE TITLE
Impossible to access an admin version change page

### ISSUE THREAD

**Issue by Kraymer** [etianen/django-reversion#746]
Version : 2.0.13
Django 1.10.8

Whenever I access the version admin page and click on an object id i have a http 504 error _"server take too long to respond"_

I think it is the related trace in Sentry :
 
![selection_377](https://user-images.githubusercontent.com/84227/44414421-0691bc80-a56e-11e8-8373-5c270bf14265.png)

I dropped all reversion_version objects but one in my postgres database and I can reproduce the bug, so it is not related to the table being too heavy.
I unregistered the 'django_admin_bootstrapped' app I used and rm all templates so that I have a vanilla admin setup, and the problem is still there.

Is there anything I can do to produce more debugging infos  ?

**Comment by etianen** [comment]
What is this a picture of? Is it your logging output?

**Comment by Kraymer** [comment]
sorry was a misclick, i'm currently writing a proper error report
