### ISSUE TITLE
Customisable `Version` and `Revision` save logic

### ISSUE THREAD

**Issue by oogles** [etianen/django-reversion#747]
We are using django-reversion in a complex system that goes far beyond simply allowing users to modify one or more objects presented in a form.

The system contains many manual transaction blocks, created with Django's `atomic()`, wrapping a variety of individual processes. Many of these processes manually raise exceptions under certain conditions, deliberately causing their wrapping transaction to rollback, while allowing the exception to be caught and handled and otherwise not interrupting the remainder of the outer process.

This obviously presents a problem when these processes affect models registered with django-reversion - it saves `Version` records for changes that are ultimately never committed to the database. Unfortunately, the solution offered in #231 - to use `create_revision()` to "mark up small, discrete blocks of code" - isn't feasible due to the complexity of the system. Not to mention, we'd like to retain the ability to group multiple changes under a single `Revision`.

So, instead, would it be possible for a future version of django-reversion to support making some of the core behaviour swappable? For example, if we could replace the default `add_to_revision()` behaviour to immediately save a `Version` to the database instead of keeping it in memory to be saved at the end of the revision context, it could be rolled back with the transaction in which it was written. This approach has some downsides, but they are more acceptable in our use case than the current problem with transaction rollbacks.

In order to get the desired functionality, we are currently looking at creating our own solution, but if we could make use of all the other features of django-reversion that already do what we need, and just customise it where we need to, that would be ideal.

At this point, we are thinking we would need to customise/replace the following behaviour:

* Entering a new revision context: We would need to write a `Revision` record to the database, so something is available for later `Version` records to link to.
* `add_to_revision`: As mentioned, to immediately write `Version` records.
* Exiting the revision context: We would need to remove the current behaviour of writing the `Revision`/`Version` records at this point.

Does this sound like something that is feasible for django-reversion to support?

**Comment by etianen** [comment]
The Version records are not written immediately to the DB, since over the
course of the revision, models may be saved multiple times. This should not
result in multiple Version instances being created. Therefore,
django-reversion only calculated the final Version models to save at the
and of the revision.

There are other edge-cases too, such as a model being created, then
deleted, in the same revision. This should not write any Version models
either.

If you are willing to accept these limitations, then you can write your own
create_revision() decorator, and manually create Version and Revision
objects as you describe. I don't really see this alternative behaviour
being worth including in reversion core, however.

**Comment by oogles** [comment]
> The Version records are not written immediately to the DB, since over the
course of the revision, models may be saved multiple times. This should not
result in multiple Version instances being created. Therefore,
django-reversion only calculated the final Version models to save at the
and of the revision.

> There are other edge-cases too, such as a model being created, then
deleted, in the same revision. This should not write any Version models
either.

Yes, as mentioned, there are downsides. In our use case, these are not nearly as problematic as the transaction rollback issue, though.

> If you are willing to accept these limitations, then you can write your own
create_revision() decorator, and manually create Version and Revision
objects as you describe. I don't really see this alternative behaviour
being worth including in reversion core, however.

I completely agree with regard to adding this behaviour directly to reversion. My question revolves more around whether reversion could include hooks in the necessary places we would need to customise - some means of easily replacing the built-in behaviour with our own, rather than writing a custom version of the ``create_revision()`` decorator. If we go this route, we'll also need to replace the ``register()`` decorator, and will end up copying a lot of reversion's code just to modify some bits in the middle.

**Comment by etianen** [comment]
I think that the django signal framework provides all the relevant hooks
already. All the rest of the reversion stuff is so tied to the current
implementation, I don't think any meaningful extra hooks could be supplied.

For example, all the logic around following relations assumes that version
information will be buffered in memory, and actually saved in the outermost
revision block.

Probably things could be reorganized to be more generic to support hooks
that would help your use-case, but this would still have the effect of
complicating the main codebase for zero gain to the project. And it would
almost certainly be useless to other people with different workflow
requirements.

I think your workflow merits it's own set of decorators. To be honest, in
your position I'd simply make my own version control system based on the
ideas used in reversion.

**Comment by oogles** [comment]
Yep, makes sense. Thanks for the input.
