### ISSUE TITLE
License clarity

### ISSUE THREAD

**Issue by iMerica** [etianen/django-reversion#753]
Hi thanks for building this. I'm trying to understand which license you've adapted and not having any luck. Would you please consider adapting the language from a mainstream license - one that even Github can parse and classify (e.g MIT or Apache).

Thank you,

Michael

https://choosealicense.com

**Comment by etianen** [comment]
I'm confused. What's wrong with this? https://github.com/etianen/django-reversion/blob/master/LICENSE

**Comment by iMerica** [comment]
Here is what a Github repo looks like when they adapt an existing widely used open source software license (on the right hand side).

<img width="970" alt="mit" src="https://user-images.githubusercontent.com/487897/45503285-a1338480-b743-11e8-88f2-c324236383bf.png">

And here is this Github repo

<img width="975" alt="who-knows" src="https://user-images.githubusercontent.com/487897/45503305-ae507380-b743-11e8-981d-8a40d58f3e4c.png">

Using a commonly used OSS license makes it easy for anyone to know at a glance if they can use this software in their own proprietary work.

**Comment by etianen** [comment]
I believe it's the 3-clause BSD license, word for word...
https://opensource.org/licenses/BSD-3-Clause

**Comment by iMerica** [comment]
Thanks @etianen 👍

**Comment by etianen** [comment]
Interesting how GitHub doens't understand it, however. If you can figure out why, I'd be happy to fix things up.
