### ISSUE TITLE
Question: There is a way to create reversions for a placeholder field of django-cms?

### ISSUE THREAD

**Issue by CristianCn** [etianen/django-reversion#758]
I have registered my models and it works great for the normal model fields, but it doesn't create reversions for the placeholder fields 

I saw that aldryn has created a way in aldryn-reversion but now it is deprecated, there is a way to register placeholder fields at the moment or tehre any plans in the future to add this feature?

Thanks!

**Comment by etianen** [comment]
What on earth is a placeholder field? I'm afraid I know nothing about
django-cms!
