### ISSUE TITLE
Disabling "Users" filter on "Revisions" admin page

### ISSUE THREAD

**Issue by Kraymer** [etianen/django-reversion#759]
When I access http://xxxx/admin/reversion/revision/ page, the page takes minutes to load because of _User_ filter list containing thousands of elements.

How can I disable that filter ?

I tried adding this code to my app :

~~~
admin.site.unregister(Version)

class VersionAdmin(VersionAdmin):
    list_filter = ()
admin.site.register(Version, VersionAdmin)
~~~

with no results

![selection_460](https://user-images.githubusercontent.com/84227/47444010-ce00a000-d7b5-11e8-9617-89c268359017.png)

**Comment by etianen** [comment]
The reversion app does not include an admin view for the Revision model.
Either you, or the 3rd party admin app your using, added that in.

**Comment by Kraymer** [comment]
Duh. Thank you!

**Comment by Kraymer** [comment]
(django-reversion-compare was the culprit)
