### ISSUE TITLE
Add custom fields to a revision

### ISSUE THREAD

**Issue by CristianCn** [etianen/django-reversion#760]
Hi!
There is a way to store manually data to a revision? I want to store data from a model with custom fields to a revision but i don't find the way to do it.

There is a way to manipulate or get the context as an object? I'm pursuing something like this:

```python
import reversion

def _add_to_context(obj, manager=None, context=None):
    if manager is None:
        manager = default_revision_manager

    if context is None:
        context = default_revision_manager._revision_context_manager

    adapter = manager.get_adapter(obj.__class__)
    version_data = adapter.get_version_data(obj)
    context.add_to_context(manager, obj, version_data)

def create_revision(obj, user=None, comment=None):
    with reversion.create_revision():
        if user:
            reversion.set_user(user)
        if comment:
            reversion.set_comment(comment)

        _add_to_context(obj)

        if hasattr(obj._meta, 'custom_field'):
            add_custom_field_to_revision(instance=obj)

def add_custom_field_to_revision(
        instance, revision_manager=None, rev_ctx=None):
 
    add_to_context = partial(
        _add_to_context,
        manager=revision_manager,
        context=rev_ctx,
    )

    # Add custom field to the revision
    for name in instance._meta.custom_field:
        add_to_context(getattr(instance, name))

```
Seems like an older version had `default_revision_manager, revision_context_manager, VersionAdapter`objects but i can't figure out how to do this on `3.0.1`.

Thanks!

**Comment by etianen** [comment]
Check out the add_meta method, here:

https://django-reversion.readthedocs.io/en/stable/api.html#revision-api

**Comment by kcunanan** [comment]
@etianen quick question: there used to be an example for adding `custom meta` in older docs
https://django-reversion.readthedocs.io/en/release-1.9.3/api.html#custom-meta-data

But there's no longer an example. Has the suggested way to use `add_meta` changed or is this still the suggested way to add custom metadata to revisions?

**Comment by etianen** [comment]
The method still exists, and is still in the docs under:

https://django-reversion.readthedocs.io/en/latest/api.html#revision-api

Not sure why the example was removed. I'm sure there was a sensible reason
behind it, possibly. :/

**Comment by kcunanan** [comment]
Thanks! I appreciate the follow up, that helps a lot
