### ISSUE TITLE
Accessing versioned field don't yield same result whether using `field_dict` or `object` 

### ISSUE THREAD

**Issue by Kraymer** [etianen/django-reversion#762]
I have this b object with a `date_from` field originally set at _26 Oct_ and set to _25 Oct_ later, in  the meantime the object has been versioned twice.

`$ manage.py shell_plus`
```
In [5]: b.versions().last().field_dict['date_from']
Out[5]: datetime.datetime(2018, 10, 26, 14, 0)

In [6]: b.versions().last().object.date_from
Out[6]: datetime.datetime(2018, 10, 25, 14, 0)
```
Isn't `b.versions().last().object.date_from` supposed to be equal to `datetime.datetime(2018, 10, 26, 14, 0)` ?
or I get a wrong comprehension of this `object` field

**Comment by etianen** [comment]
No, `object` is a generic foreign key to the latest version of the model.
