### ISSUE TITLE
Upgrade from 3.0.0 to 3.0.1 result in error when migrate

### ISSUE THREAD

**Issue by chowlinyi** [etianen/django-reversion#763]
After upgrading from 3.0.0 to 3.0.1 when I tried to run migrate, it returns the following error:

Applying reversion.0001_squashed_0004_auto_20160611_1202...Traceback (most recent call last):
  File "../.virtualenvs/aws/lib/python3.6/site-packages/django/db/backends/utils.py", line 83, in _execute
    return self.cursor.execute(sql)
psycopg2.ProgrammingError: relation "reversion_revision" already exists

**Comment by etianen** [comment]
v3.0.2 is out, with squashed migrations removed again.

**Comment by libcthorne** [comment]
What is the recommended upgrade path from 3.0.1 to 3.0.2? `python manage.py migrate --fake`?

**Comment by etianen** [comment]
Yes, that will probably work.

**Comment by andreasnuesslein** [comment]
**Heads up!** Just faking all the migrations could result in all kinds of things. The above should read

```
python manage.py migrate reversion --fake
```
