### ISSUE TITLE
Create initial revision from migration

### ISSUE THREAD

**Issue by Christophe31** [etianen/django-reversion#769]
Hi, should the project document a way to make migrations file to make initial revision instead of running them manually on each server instance?

```
from __future__ import unicode_literals
from django.db import migrations
from django.core import management


def update_all_contenttypes():
    from django.apps import apps
    from django.contrib.contenttypes.management import create_contenttypes

    for app_config in apps.get_app_configs():
        create_contenttypes(app_config)


def get_models():
    return (
        'my_app.MyModel',
        'my_app.MyModel2',
    )


def init_reversion():
    management.call_command(
        'createinitialrevisions',
        *get_models(),
        comment="Initial revision.",
        verbosity=1)


def clean_reversion():
    management.call_command(
        'deleterevisions',
        *get_models(),
        verbosity=1)


def forward(apps, schema_editor):
    update_all_contenttypes()
    init_reversion()


def backward(apps, schema_editor):
    clean_reversion()


class Migration(migrations.Migration):

    dependencies = [
        ('reversion', "0001_squashed_0004_auto_20160611_1202"),
        ('my_app', '0018_auto_20181230_0025'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
```

**Comment by etianen** [comment]
I'm hopeful that users can work this out for themselves, as all the parts
for it are documented separately.

It's a decent approach to creating initial revisions if you've got a large
number of copies of a codebase running in production.

**Comment by Christophe31** [comment]
* edit main exemple to add contenttypes in the migration so tests database still work

**Comment by Christophe31** [comment]
I use rolling release with CI automated process, so, if I can avoid running commands on instance, it's for the best.

**Comment by Christophe31** [comment]
* add backward relation

**Comment by Christophe31** [comment]
if it make sense, a small tool may allow simpler migration:

```
from __future__ import unicode_literals

from django.db import migrations
from django.core import management


def update_all_contenttypes():
    from django.apps import apps
    from django.contrib.contenttypes.management import create_contenttypes

    for app_config in apps.get_app_configs():
        create_contenttypes(app_config)


def init_reversion(models, comment):
    management.call_command(
        'createinitialrevisions',
        *models,
        comment=comment,
        verbosity=1)


def clean_reversion(models):
    management.call_command(
        'deleterevisions',
        *models,
        verbosity=1)


def reversion_migration(models, update_content_type=True, comment="Initial revision."):
    def forward(apps, schema_editor):
        if update_content_type:
            update_all_contenttypes()
        init_reversion(models, comment=comment)

    def backward(apps, schema_editor):
        clean_reversion()

    return migrations.RunPython(forward, backward)

```

which then would be used:

```
    operations = [
        reversion.migrations.reversion_migration(
             ("my_app.Model",)),
    ]
```

**Comment by Christophe31** [comment]
I don't know if it make sense, but it won't move this sample again, you can make what you want with the code and the issue. the tool sample I made works for me. Still I'm not glad about how contentypes are handled and the fact I have to manually refer to dependencies versions of both reversion and contenttypes.

**Comment by etianen** [comment]
It's a nice approach. I don't think it necessarily needs including in the
docs/codebase, but hopefully anyone googling will stumble across your
example as a starting point.

**Comment by mastacheata** [comment]
It's an invaluable tool for CI/CD and multi-stage deploys (i.e. when you have separate systems for review by certain user groups or deploy certain features only on certain machines)

Would it be possible to inlcude that as a separate management command or as an option to the creatinitialrevisions command so it would write the revision creation task into a migration instead of executing it directly?

I'd be happy to provide that as a PR if it's got any chance of being included.

**Comment by Christophe31** [comment]
It's nice but, to be honest, I think this implementation is not good as running it in the middle of the migrations chain break the initial if models have substantially changed.

**Comment by mastacheata** [comment]
Isn't that true as well if you create the initial revision manually and then change the model significantly?
I mean you can't go back unless you roll back your migrations as well obviously and old migrations should never be rerun unless you have a clean database or explicitly rolled back the database anyway.

**Comment by Christophe31** [comment]
Not the same, this thing will break in the middle of your migration in a new deployment while running migration after will "break" your old data ability to rollback while it's still have his informative value and does not crash.

**Comment by mastacheata** [comment]
I can't seem to follow you, Care to give an example?

Do you mean that the initial revision doesn't match the datastructure anymore right away after applying a migration following the one to create the initial revision since the data structure doesn't match right from the start? But if that's a problem, then I need to create a new initial revision after each migration? Is that problem really related to the initial revision being created in a migration and not more of a problem with changing data structures in general after creating the initial revision?

If that's not what you were trying to make your statement about, please provide an example. Maybe I'm lost in translation (French speaking English to a German ;))

**Comment by Christophe31** [comment]
in fact when you run createinitialrevisions, it expects models to be like the one in your database. if I put it in a migration file, it will run while some migrations may not be applied yet.

**Comment by mastacheata** [comment]
Ahh you mean that Django doesn't apply the migrations one-by-one?

**Comment by Christophe31** [comment]
this fix will work when you'll use it… if you continue developing, it won't work in ten month as your data structure will have evolved, if you deploy on a new server, it will try to `createinitialrevisions` while newer migrations are not applied yet.

**Comment by mastacheata** [comment]
Sorry, I simply didn't get the models part into my head. Had a discussion with a colleague and then it made click.   
Reversion must use the model definitions from the Model class files at the time of executing the command, even if the migrations and current database state don't reflect the state of that class yet.
