### ISSUE TITLE
Add comment with new-style RevisionMiddleware

### ISSUE THREAD

**Issue by spapas** [etianen/django-reversion#770]
I want to add a comment with the path that was used for each reversion with new-style middleware. See previous discussion (for old-style ones) in #562.

I've tried something like this:

```
import reversion
from reversion.middleware import RevisionMiddleware

class CommentedRevisionMiddleware(RevisionMiddleware):
    def __call__(self, request):
        resp = self.get_response(request)
    if reversion.is_active():
        reversion.set_comment(request.path)
    return resp
```

and various variations. No luck, the comment always stays empty :(

Any help?

**Comment by etianen** [comment]
The trick is not to subclass RevisionMiddleware. Compose it!

``` py
def revision_comment_middleware(get_response):
    def do_revision_comment_middleware(request):
        response = get_response(request)
        if reversion.is_active():
            reversion.set_comment(request.path)
        return response
    return do_revision_comment_middleware
```

Then, add `path.to.revision_comment_middleware` to your `MIDDLEWARE` setting after `RevisionMiddleware`.

**Comment by spapas** [comment]
Excellent, thank you very much @etianen !
