### ISSUE TITLE
Tests runnable without external database?

### ISSUE THREAD

**Issue by risicle** [etianen/django-reversion#773]
It would be particularly neat if the test suite's external database tests were optional. This would allow the django-reversion Nix package (https://github.com/NixOS/nixpkgs/blob/ca7ef865c45726dc80ba6e3d42e37ccfa6c0ae73/pkgs/development/python-modules/django_reversion/default.nix) to enable the tests, which would give package maintainers bumping the version a little more confidence they're not building broken packages. (They'd also get re-run whenever any of its dependencies get bumped to check *those* haven't broken it)

It does appear that a good few of the tests simply work against the default sqlite database and it would probably just be a matter of scattering some `@skipIf` decorators or `skipTest()` calls throughout the others. For bonus points, make `settings.py` simply omit the missing entries of `DATABASES` if the relevant db credentials e.g. `DJANGO_DATABASE_NAME_POSTGRES` aren't found in the env.

**Comment by risicle** [comment]
I'm confused... unless I'm reading the code wrong, ~70% of your tests don't touch the postgres or mysql databases and so "aren't replicating a production scenario" - surely us checking 70% of tests pass would be better than the current situation where the package could get *totally* broken and nobody would be any the wiser?

**Comment by etianen** [comment]
Looking closer at the Nix Django package... that doesn't seem to be running
tests either...

**Comment by risicle** [comment]
No, that's actually been a project of mine that I haven't got a lot of traction on - it has thousands of tests. In the mean time it's a lot better to try and get *something* for as many of the smaller projects as possible (in a way, ensuring tests pass for packages that *depend on* django gives an amount of assurance about django itself).

**Comment by risicle** [comment]
Anyway, I was only suggesting a ~20 line change that would have been kinda helpful to packagers, let's not get too caught up in it.
