### ISSUE TITLE
Does not work correctly with master-replica database schema

### ISSUE THREAD

**Issue by Anton-Shutik** [etianen/django-reversion#783]
Hey, thanks for such a nice app!
I have following issue:

__Any object revision always shows me current object state/version in admin.__ 

I have a database router as django [docs describes](https://docs.djangoproject.com/en/2.1/topics/db/multi-db/):
```python
class PrimaryReplicaRouter:
    def db_for_read(self, model, **hints):
        return 'replica'

    def db_for_write(self, model, **hints):
        return 'default'

# project/settings.py:
DATABASE_ROUTERS = ['PrimaryReplicaRouter']
```
Then, when rendering `changeform_view` it does:
```python
with transaction.atomic(using=version.db):
    # Revert the revision.
    version.revision.revert(delete=True)
    # Run the normal changeform view.
    with self.create_revision(request):
        response = self.changeform_view(request, quote(version.object_id), request.path, extra_context)
        # Decide on whether the keep the changes.
        if request.method == "POST" and response.status_code == 302:
            set_comment(_("Reverted to previous version, saved on %(datetime)s") % {
                "datetime": localize(template_localtime(version.revision.date_created)),
            })
        else:
            response.template_name = template_name  # Set the template name to the correct template.
            response.render()  # Eagerly render the response, so it's using the latest version.
            raise _RollBackRevisionView(response)  # Raise exception to undo the transaction and revision.
```
just to confirm, same, but in the words:
1. opens a transaction
2. reverts object to chosen revision (in `master` database)
3. renders django's standard `changeform_view`, which uses `replica` database(!), which is not aware about the transaction, ie we always get current object state
4. rolls back transaction

I've fixed it easily just by overriding queryset and it worked fine for me:
```python
class VersionAdmin(admin.ModelAdmin):

    def get_queryset(self, request):
        qs = super(RenderableAdmin, self).get_queryset(request)
        return qs.using(router.db_for_write(self.model))
```

**Comment by Anton-Shutik** [comment]
Could you pls confirm the issue and push the fix to master & release ? 
I can create PR as well if needed

**Comment by etianen** [comment]
I think that you can fix this in your own codebase, by overriding
get_queryset on your admin classes, or creating a subclasses VersionAdmin
just for your app.

I'm not convinced that this solution is suitable for general usage, as it
feels it could introduce it's own set of gotchas for other database routing
schemes.

**Comment by Anton-Shutik** [comment]
Ok, will do. But I don't think it will give any issues on others schemes. It works perfect on single database and master-replica as well.  All it does is just make django _fetch_ objects from database they were written to. That makes a sense since we have this code running in transaction context, which is also created on "writing" database.
