### ISSUE TITLE
Lots of sql requests on the history view page

### ISSUE THREAD

**Issue by OlivierGuilloux** [etianen/django-reversion#786]
Hello,

I have a lot of SQL on the history view, for this one I have 40 queries:

![image](https://user-images.githubusercontent.com/15343458/56590329-360a3480-65e7-11e9-834a-fcb0c5f1099a.png)

With revision that contains thousands of objects versions the page cannot display (timeout). Did I miss somthing ?

When I comment the following line in `admin.py` the number of requests get down :
```python
                # Revert the revision.
                # version.revision.revert(delete=True)
```
![image](https://user-images.githubusercontent.com/15343458/56590853-0c9dd880-65e8-11e9-904a-7c55deebb2d0.png)

Did i miss something on my side ?

Thanks

**Comment by etianen** [comment]
What SQL queries are running?

**Comment by OlivierGuilloux** [comment]
As you can see it returns all the others objects that are part or the revsion:

![image](https://user-images.githubusercontent.com/15343458/56592292-ad8d9300-65ea-11e9-9c31-fbb3b8d055d2.png)

On this page I am only interested in the id = 2

To create the revision, I do:

```python
  with reversion.create_revision():
    for obj in ...:
       obj.save()
    reversion.set_comment("Update from command line")
```

**Comment by etianen** [comment]
Oh I see.

So, when reversion reverts a revision, it saves all the models in the
revision back to the database. Calculating which models are required is
probably impossible, so it takes this heavy-handed approach.

The solution is to save one revision per Content model, rather than a
single revision containing all of them.

**Comment by OlivierGuilloux** [comment]
Ok I understand I will change my code in order to do so.
