### ISSUE TITLE
Add ip address to registered model revision when RevisionMiddleware is present.

### ISSUE THREAD

**Issue by robwise1** [etianen/django-reversion#787]
I apologize if this has been raised before. I see similar feature requests but these appear to have answers that refer to out of date documentation. I am looking for advice on how to add the IP address to the revision. 

I understand that I need to create a separate model, with a OneToOne of the corresponding Revision as well as additional fields for whatever extra data is needed. However, I do not understand where I can access both the revision as well as the request. 

I have a model, registered with reversion like this

```
@reversion.register()
class Account(BaseAccount):
    name = models.CharField()
    ...
```

I'm using RevisionMiddleware, but the middleware only informs if a revision is necessary, and sets the user, the revision is not yet created. Is there a simple way to fetch the IP and create my Metadata storage model when registering a model?

**Comment by etianen** [comment]
You'll need to make your own middleware that runs after RevisionMiddleware,
and calls reversion.add_meta to attach the metadata you want to the
revision.

https://django-reversion.readthedocs.io/en/stable/api.html#revision-api

**Comment by andreasnuesslein** [comment]
i think this issue could be closed. cheers
