### ISSUE TITLE
reversion works only in admin

### ISSUE THREAD

**Issue by AlekseiKhatkevich** [etianen/django-reversion#788]
Hello
Problem is that reversion only works when entry has been made or changed in admin panel, but when it was made or changed from web page - "recovery deleted" folder would not show these deleted entries.
Same issue for 5 different models.

All of them are registered in admin.py like this:

@admin.register(BoatModel)
class BoatsAdmin(VersionAdmin):

**Comment by etianen** [comment]
You need to decorate views you want to use django-reversion in.

https://django-reversion.readthedocs.io/en/stable/views.html

Or use a middleware:

https://django-reversion.readthedocs.io/en/stable/middleware.html
