### ISSUE TITLE
Is it possible to "stage" changes with this tool?

### ISSUE THREAD

**Issue by tlawren3** [etianen/django-reversion#789]
I'm looking for a way to prevent a new revision from being displayed prior to my approval. Can this be accomplished with django-reversion?

**Comment by cw-intellineers** [comment]
I would also be interested in something like this. In our app, I would like that each save triggers a new version and that once a user is satisified with the changes, a revision is created that "bundles" those versions together.

Is that something that is currently possible?

**Comment by etianen** [comment]
Nope, sorry. You'll want to build your own versioning system for that.

**Comment by cw-intellineers** [comment]
Thank you for your response @etianen
