### ISSUE TITLE
Django Reversion might be reverting changes on a legit PermissionDenied exception

### ISSUE THREAD

**Issue by aleksihakli** [etianen/django-reversion#792]
We are currently investigating a possible authentication attempt tracking bug in https://github.com/jazzband/django-axes/issues/440 and it seems like Django Reversion might be [rolling back database transactions](https://github.com/etianen/django-reversion/blob/master/reversion/middleware.py#L45) on objects if an authentication backend raises a `PermissionDenied` exception?

`PermissionDenied` is a legit exception that blocks user authentication flow in the [django.contrib.auth.authenticate](https://github.com/django/django/blob/master/django/contrib/auth/__init__.py#L61) function. 

Django Axes attempts to [update records of failures](https://github.com/jazzband/django-axes/blob/master/axes/handlers/database.py#L91) in the case of a denied login attempt, but it seems like the record is currently lost in a possible rollback?

**Comment by etianen** [comment]
Sounds quite plausible. Unfortunately, a rollback is all-or-nothing, and
I'm not aware of any other way of reverting the database changes in the
admin integration.
