### ISSUE TITLE
Add a revision when an instance is deleted

### ISSUE THREAD

**Issue by alexkiro** [etianen/django-reversion#796]
It appears that a entry is not added in `reversion_revision` when an instance of the registered model is deleted. Either from admin or from a view. 

It would be a nice addition to also store a revision in these cases for:

- complete auditing
- being able to more easily revert to a specific version in time in these cases (e.g. by recreating the deleted instance)

**Comment by etianen** [comment]
It sounds like a good idea, but infortunately it's been tried before, and turned out to be a *really bad idea* in practice :P

If you're interested in the history behind this, check out #164

**Comment by alexkiro** [comment]
> It sounds like a good idea, but infortunately it's been tried before, and turned out to be a _really bad idea_ in practice :P

Oops, sorry for opening a dupe :) 
 
> If you're interested in the history behind this, check out #164

Will take a look, thanks!

**Comment by etianen** [comment]
You're not the first, and you won't be the last. :P
