### ISSUE TITLE
Reverting deleted items and their related records

### ISSUE THREAD

**Issue by akulakov** [etianen/django-reversion#797]
When items are deleted and then reverted in order to un-delete, is there any way to configure, or a recipe to use so that linked records get restored as well?

Consider having models A and B, both registered, A has a FK to B, with on_delete=CASCADE argument. If B is deleted, both records will be deleted, but if B is reverted, A stays deleted.

Same for on_delete=SET_NULL -- would like to find a way to have it restored to the ID of deleted record when it's reverted.

**Comment by etianen** [comment]
That's what the "follow" argument to register() is for.

If you register A to "follow" the fk to B, the whenever A is saved, B will
also be added to the revision. If both models are deleted, and you revert
the revision, both models are restored.

Note, reverting the Version model only reverts a single model instance, but
reverting a Revision model reverts all model instances in that revision.

**Comment by akulakov** [comment]
Thanks for the response! I was reverting the Version, that's why I wasn't getting the related record restored. I will test later today and close the ticket if I don't have follow-ups.

**Comment by akulakov** [comment]
I've had some success reverting revisions with related items, but it doesn't always work: when I delete+recover a record through the admin, both records are restored. If immediately after that I delete the record again, and recover it, only the record I recover is restored, the linked record does NOT get restored.

I did more experimentation from the command line, it seems like some models, when deleted, create a Revision, but others do not (even though they're registered and deletion is done within the `create_revision` context manager:

```
# make 2 records with model_mommy.mommy.make (which uses normal `create` but fills in required
# fields automatically)
In [75]: with create_revision(): s=make(PossibleReschedule)

In [76]: with create_revision(): i=make(SchedulingInteraction, related_suggestion=s)

In [77]: SchedulingInteraction.objects.all()
Out[77]: <QuerySet [<SchedulingInteraction: id=5 [None] Action: None>]>

# existing revisions now
In [78]: reversion.models.Revision.objects.all().order_by('date_created')
Out[78]: <QuerySet [<Revision: id=4 [None] Action: None>, <Revision: Offer reschedule: (redacted)>, <Revision: id=5 [None] Action: None>]>

In [82]: lst=reversion.models.Revision.objects.all().order_by('date_created')

# ids of revisions
In [83]: [x.id for x in lst]
Out[83]: [342, 343, 344]

# delete PossibleReschedule
In [84]: with create_revision(): s.delete()

# linked SchedulingInteraction is also deleted
In [85]: SchedulingInteraction.objects.all()
Out[85]: <QuerySet []>

# no revision for the deletion??!!
In [87]: lst=reversion.models.Revision.objects.all().order_by('date_created');lst
Out[87]: <QuerySet [<Revision: id=4 [None] Action: None>, <Revision: Offer reschedule: (redacted)>, <Revision: id=5 [None] Action: None>]>

In [88]: [x.id for x in lst]
Out[88]: [342, 343, 344]

In [89]: with create_revision(): i=make(SchedulingInteraction)

In [90]: i
Out[90]: <SchedulingInteraction: id=6 [None] Action: None>

# delete SchedulingInteraction
In [91]: with create_revision(): i.delete()

# now revision is present
In [92]: lst=reversion.models.Revision.objects.all().order_by('date_created');lst
Out[92]: <QuerySet [<Revision: id=4 [None] Action: None>, <Revision: Offer reschedule: (redacted)>, <Revision: id=5 [None] Action: None>, <Revision: id=6 [None] Action: None>]>

In [93]: s=PossibleReschedule.objects.first()

# delete another PossibleReschedule
In [94]: with create_revision(): s.delete()


# again revision for deletion is not there!!!?
In [95]: lst=reversion.models.Revision.objects.all().order_by('date_created');lst
Out[95]: <QuerySet [<Revision: id=4 [None] Action: None>, <Revision: Offer reschedule: (redacted)>, <Revision: id=5 [None] Action: None>, <Revision: id=6 [None] Action: None>]>


# models are registered like this:
@reversion.register
class PossibleReschedule(BaseModel):

# link is to PossibleReschedule
@reversion.register(follow=['related_suggestion'])
class SchedulingInteraction(BaseModel):
```

**Comment by etianen** [comment]
Deleting models never creates a revision. Only saving creates revisions. A revision represents a snapshot of a group of models at a point in time. If you delete the models, you can always restore them to the previous snapshot taken the last time they were saved.

For example, given the following models:

``` py
@reversion.register(follow=["child_set"])
class Parent(models.Model):
    name = models.CharField(max_length=255)

@reversion.register(follow=["parent"])
class Child(models.Model):
    name = models.CharField(max_length=255)
    parent = models.ForeignKey(Parent, on_delete=models.CASCADE)

# Create a revision containing 1 parent and 2 children.
with reversion.create_revision():
    parent1 = Parent.objects.create(name="parent1")
    child1a = Child.objects.create(name="child1a", parent=parent)
    child1 b= Child.objects.create(name="child1b", parent=parent)

# The follow relations mean that saving a child or a parent will save related children and parents in
# the same revision. So this revision also contains 1 parent and 2 children.
with reversion.create_revision():
    child1a.name = "child1a_modified"
    child1.save()

# This will delete the parent and all children. No revision is created, but the previous revisions still exist and can be used to revert.
parent1.delete()

# Revert back to the previous revision. 1 parent and 2 children will be un-deleted, and the child1a name will be "child1a_modified".
Revision.objects.order_by("-id")[0].revert()

# Revert back to the first revision. child1a name will be reverted to "child1a".
Revision.objects.order)by("-id")[1].revert()
```

**Comment by akulakov** [comment]
Thanks, that makes sense; I tested everything and it works. I thought there would be a revision for deleted items by analogy with Version objects and `get_deleted()`, and also because in the recover page in the admin there's list of deleted items that would restore based on Revision data, so I assumed that is a list of 'deleted' Revisions. Also when testing in django shell I've ran into the issue with using `.last()` qs method which in this case refers to the earliest Revision instead of the latest, because of Revision default sorting by '-id'. Hope this helps if other people run into similar issues.

Thanks again for the great explanation!

**Comment by akulakov** [comment]
Reopening because on further testing, reverting a record that has a reverse relation specified with `SET_NULL`, causes this error which I'm not sure how to interpret:
`RevertError: Could not save SID: None | From: None | To: vNbmFHFkLdTjxqngOSlA | Message:  | Date: None version - missing dependency`

The case I'm setting up is very minimalistic, models A and B, model A has FK to B, with `SET_NULL` specified as `on_delete`. The error happens when i delete record under B.

model setup:
```
@reversion.register(follow=['scheduling_interactions', 'presched',])
class SMSMessage(BaseModel):
...
    presched                     = models.ForeignKey(PossibleReschedule, on_delete=models.SET_NULL, blank=True, null=True)

@reversion.register(follow=['scheduling_interactions', 'smsmessage_set'])
class PossibleReschedule(BaseModel):
...


```
In [34]: from model_mommy.mommy import make                                                                                                                                                               

In [35]: with create_revision(): s=make(PossibleReschedule)                                                                                                                                               

In [36]: with create_revision(): msg=make(SMSMessage, suggestion=s)                                                                                                                                       
In [40]: s.delete()                                                                                                                                                                                       
In [42]: Revision.objects.first().revert()                                                                                                                                                                
RevertError: Could not save SID: None | From: None | To: vNbmFHFkLdTjxqngOSlA | Message:  | Date: None version - missing dependency.
```

Looking at the code, it's still not very clear why this happens, perhaps Reversion expects that if related record with a `follow` relationship is deleted, the other one is also deleted, which is not the case with SET_NULL.

I also looked at the tests/ dir, it looks like no model is set up with SET_NULL relationship for testing, so is it just not supported?

**Comment by etianen** [comment]
Here's what you're doing at the moment:

35: Create a revision containing `s`.
36: Create a revision containing `msg`, but not `s`, since you don't follow
`suggestion`.
40: Delete `s`. This sets `msg.suggestion` to NULL, but no revision is
created.
42: Attempt to revert to the revision created in 36. Since `s` isn't
present in the revision, but the saved model version specifies that
`msg.suggestion` point to `s`, the revert fails.

You need to ensure that `s` is present in the revision created in 36.
Specificing `suggestion` in the `follow` array when registering
`SMSMessage` will probably do it.

**Comment by akulakov** [comment]
Thanks for the response and sorry for not replying sooner - I was on vacation.

I edited the code example when posting it, and it's a bit inconsistent, but I do have the `suggestion` specified in the `follow` array when registering `SMSMessage`, I renamed to to `presched` in the example to be less confusing so that it's the same as the model name.

**Comment by akulakov** [comment]
Thanks for help, really appreciate it!

**Comment by etianen** [comment]
Glad to help :)
