### ISSUE TITLE
Added does not include the data that was provided

### ISSUE THREAD

**Issue by khashashin** [etianen/django-reversion#799]
Creating (adding) new model instance does not include the data that was provided. Only when we change something there will be changed fields. Lets say my model has not required fields, but user can still provide this data during creation. Is that possible some how to include this data on "added" comment, like it works when we change something?
![image](https://user-images.githubusercontent.com/17837758/61920805-1cb4b380-af5b-11e9-9f85-fdd65eb5e0d8.png)

Use case to create statistics and get the data fields where the data were provided.

**Comment by etianen** [comment]
Sorry, I don't understand what you're trying to acheive here. Can you
elaborate?

**Comment by khashashin** [comment]
`added` does not include which fields was added.
```
class CoreWordCategoryModel(models.Model):
    co_abbreviation = models.CharField(max_length=10, blank=True)
    co_description = models.CharField(max_length=50, blank=True)
    ru_abbreviation = models.CharField(max_length=10, blank=True)
    ru_description = models.CharField(max_length=50, blank=True)
    en_abbreviation = models.CharField(max_length=10, blank=True)
    en_description = models.CharField(max_length=50, blank=True)
```
When you create new instance, django-reversion does not include the fields where data was provided
```
>>> cat = CoreWordCategoryModel(co_abbreviation='test', co_description='test')
>>> cat.save()
```

**Comment by etianen** [comment]
It uses the same logic as the built-in django admin framework. A comment
can be anything. You shouldn't be parsing it for machine-readable code,
really. It just happens that the admin framework uses a JSON representation
in some cases.

If you want to include added fields in the comment, you'll need to override
the log_addition() method in the model admin class.
