### ISSUE TITLE
What is the most performant way of getting dates when a particular field in model changed?

### ISSUE THREAD

**Issue by velis74** [etianen/django-reversion#800]
This is purely a performance question. 

I have a model which contains a field denoting current app_version. Now I'm attempting to reconstruct version update history such that I would end up with a list of (date, version) tuples showing the time points when the app_version field changed its value:

```
    for ver in Version.objects.get_for_object(device).select_related('revision', 'revision__user')\
            .prefetch_related('content_type').in_bulk().values():
        try:
            v = ver.field_dict['app_version']
            if v:
                versions.append((ver.revision.date_created, v))
        except:
            pass
```

This particular query takes anywhere between .7 and 5 seconds on my dev machine for the database I'm querying. It results in 6 queries being performed. All of this per each device, so this is unacceptably slow.

As seen by the code, I only need two fields from here: field_dict and revision.date_created.

I'm not sure, but can I take a shortcut like this here:

```
    for ver in Version.objects.get_for_object(device).values('serialized_data', 'revision__date_created'):
        try:
            data = json.loads(ver['serialized_data'])
            v = data[0]['fields']['app_version']
            versions.append((ver['revision__date_created'], v))
        except:
            pass
```

This reduces query time to somewhere between .3 and 1.2 seconds.

Ideally there would be an even faster method?

**Comment by etianen** [comment]
The serialized version information is, unfortunately, not indexable in a
cross-database way.

*If* we only supported postgres, and *if* we only supported JSON
serialization, then it would be possible to index this information and
perform your query in a performant way.

However, since neither of these apply, your second version is about as good
as it gets.

**Comment by velis74** [comment]
Thanks
