### ISSUE TITLE
LookupError: No installed app with label 'admin'

### ISSUE THREAD

**Issue by mehran-prs** [etianen/django-reversion#805]
Hi, I want to use djagno-reversion without `django.contrib.admin` app (using with DRF wihtout admin), but raise `LookupError: No installed app with label 'admin'.` error when try to run `python manage.py createinitialrevisions` command, how can i resolve it?

**Comment by etianen** [comment]
You need to add "django.contrib.admin" to your INSTALLED_APPS setting.

**Comment by quyetdakmil** [comment]
add "django.contrib.admin", not working with me ;((

**Comment by etianen** [comment]
I believe that the latest release of django-reversion doesn't need `django.contrib.admin` any more.

If you come across something that contradicts this, please check you've installed the latest django-reversion, and if you have, post the full traceback here.
