### ISSUE TITLE
Display changes in admin

### ISSUE THREAD

**Issue by sadman4eg** [etianen/django-reversion#807]
Is that right, or am I doing something wrong?
![Screen Shot 2019-10-30 at 16 24 22](https://user-images.githubusercontent.com/37148287/67866605-e2e2e280-fb31-11e9-890f-1e211c79a35c.png)
I mean the bottom variant. Top variant is from admin changes, middle variant - from view. And bottom variant from middleware versions creating

**Comment by etianen** [comment]
Are you referring to the weird diff comment?

You should use `get_comment` rather than just `comment` to get the text for
the django-reversion comment.
