### ISSUE TITLE
custom Version models per model?

### ISSUE THREAD

**Issue by andreasnuesslein** [etianen/django-reversion#808]
Ahoy @etianen ,

I googled for a while and couldn't find any information on that: 

I was wondering if it would be helpful/clever/possible to create per model Version models, i.e.:
```
@reversion.register()
class Person(models.Model):
    ...
```
would yield a `myapp_person_version` table, or a `reversion_myapp_person_version` or similar. Or alternatively add a function argument to `register()` to pass in a different Version-model for specific models?

My reasoning here being that that single `reversion_version` table is gonna grow quite rapidly in my scenario and at least based on my naive database knowledge I think it would be helpful to be able to spit it into semantically seperated tables. 

Cheers

**Comment by etianen** [comment]
It's an interesting idea, but I don't think there would be much performance
gains in splitting up the table. It would make database queries maybe a
little more efficient, but they should already be pretty well indexed.

In general, it's a good idea to periodically prune reversion tables using
the deleterevisions management command. Otherwise you're facing a great
deal of stored data no matter which way you cut it!

https://django-reversion.readthedocs.io/en/stable/commands.html#deleterevisions

**Comment by andreasnuesslein** [comment]
Ahoy @etianen ,

thanks for your reply! `deleterevisions` is not gonna be an option for us. I will need to have the data always to go back to the beginning of time. Or at least for the foreseable future. I might have to consider clutching it by maybe sharding by year or something similar... :thinking: 

If i created a non-invasive PR (i.e. a PR that won't change the default behavior) that gives me the ability to basically use a `class MyVersion(Version):` and `@reversion.register(custom_class=MyVersion)` would you merge it?

Cheers

**Comment by etianen** [comment]
To be honest, I'd rather keep the core codebase as simple as possible.

One idea if you're serious about this is to make your own versioning
implementation where there is a version table per model BUT you mirror the
database columns (minus unique constraints). This would make the stored
version information take up much less space compared the the serialised
JSON representation used by reversion. It would also allow querying of
columns and database migrations of old data.

I kinda wish I'd done reversion like this, tbh. But that bird has flown :P

**Comment by andreasnuesslein** [comment]
I'm not sure I follow with the approach you would take nowadays. How, for example, would you handle the deletion and addition of fields on that extra table? Also, why not use Postgres' JSON/JSONB ?

I realized your current implementation uses a `TextField`. But if you split the Version model into a abstract `VersionBase` and a `Version` on top, one could inherit from `VersionBase` and replace `serialized_data` field with a JSONField field for example to give you a huge performance boost as well as queryability on the field.

As an additional bonus due to djangos ORM you get my initial request for free ;)

**Comment by etianen** [comment]
You'd generate the reversion model dynamically by introspecting the fields
on the "real" model. The per-model reversion model would then participate
in the Django migrations framework as usual.

I'm not sure that JSONB would give a huge performance boost over TextField
at all. You'd gain queryability, but it's still serialized to text for
transmission over the wire via psycopg2, and JSONB often has a higher disk
footprint than JSON!

**Comment by andreasnuesslein** [comment]
But if it participated in the migrations, you'd lose historical field data if you also removed a field. Or would you never remove fields/columns, but only ever add? 
I do understand that you have the same problem now: if i remove a field and i want to roll back an old version, where would that extra data from the serialized json go, either way :thinking: . But at least in the JSON the data would still be there.

I guess you're right about the performance. But still: the queryability :tada: 

Hmmmmh you've given me a lot to think about :)

**Comment by etianen** [comment]
Yes, you would lose historical data when you remove a field. However, if
you're not going to be migrating historical data, it rapidly becomes
unparseable by the current version of the app. You'd have to make sure that
your migrations are all reversible with no data loss. That way you can
migrate your current and historical data back and forth.

A general-purpose solution for lossless, migrateable historical data does
not exist. django-reversion makes a best effort, but at some point if you
make a radical schema change your reversion history has to be deleted or
tediously manually migrated.

So if you truly need a lossless historical data record, you'll need a
careful, custom solution.
