### ISSUE TITLE
Minor release 3.0.6 broke Python 3.5 compatibility

### ISSUE THREAD

**Issue by nkuttler** [etianen/django-reversion#824]
In e9c608e885e06705eac9474a339efcba3d68f106 support for Python < 3.6 was removed, but the version was only increased from 3.0.5 to 3.0.6 and the change wasn't even mentioned in the changelog. This is a major change and would have deserved a major version bump.

Feel free to close this issue, it increases visibility for the problem.

**Comment by etianen** [comment]
I'm not sure... do we really want to perform a major version bump for dropping an older Python release? That would put us on v9 at this point, which would be doing a pretty effective job of swamping other changes.

After all, Django isn't performing major version bumps for dropping older Python releases, AFAIK

**Comment by nkuttler** [comment]
Going with semver terminology 3.0.6 was a patch version, Django only drops Python supporot in minor releases, e.g. 2.0 -> 2.1.

**Comment by etianen** [comment]
That seems like a good compromise to use in future. I'll follow that.
