### ISSUE TITLE
When saving with update_fields

### ISSUE THREAD

**Issue by rokondo** [etianen/django-reversion#825]
I save my objects with ` object.save(update_fields=[request.POST.get("field")])  `

I noticed that the other "unchanged" fields are not saved in revision. Is that expected behaviour or is there a good solution as a workaround?

**Comment by etianen** [comment]
Are you sure they're not being saved in reversion? Because I don't think
there's anything in the codebase that would do that.

**Comment by rokondo** [comment]
Or I am to silly? But when I go in the admin on the history I see:
![image](https://user-images.githubusercontent.com/640866/76331253-2a9f2500-62ef-11ea-9dc7-f92009d8a511.png)

**Comment by etianen** [comment]
Have a look at what's actually stored in the database in the
reversion_version table.

Also, maybe confirm the behavior by changing the update_fields and seeing
whether the admin view is affected.

**Comment by rokondo** [comment]
The data is not set in the database. I made a hack for the Form in Django now:
`    def clean(self):
        super().clean()
        for field_name in self.fields:
            field = self.fields.get(field_name)
            if not field_name in self.data and field_name in self.cleaned_data:
                self.cleaned_data[field_name]=getattr(self.instance,field_name)`

Luckily this code works now also when the update_field isset. I guess the problem is that the fields are left empty in `cleaned_data`.
