### ISSUE TITLE
Migration errors "(fields.E304) Reverse accessor"

### ISSUE THREAD

**Issue by nguyenbathanh** [etianen/django-reversion#828]
Hi!

I'm following installation guide of `django-reversion` at the documentation page, everything went well until I executed database migration by command `./manage.py migrate`, these are the errors:

```
reversion.Revision.user: (fields.E304) Reverse accessor for 'Revision.user' clashes with reverse accessor for 'Revision.triggered_by_user'.
	HINT: Add or change a related_name argument to the definition for 'Revision.user' or 'Revision.triggered_by_user'.
revisions.Revision.triggered_by_user: (fields.E304) Reverse accessor for 'Revision.triggered_by_user' clashes with reverse accessor for 'Revision.user'.
	HINT: Add or change a related_name argument to the definition for 'Revision.triggered_by_user' or 'Revision.user'.
```

Do you have any ideas on this matter?

**Comment by nguyenbathanh** [comment]
Never mind, I just figured out it is a problem from my project.

**Comment by RobbeVanH** [comment]
Did you find what the problem is? I'm having the same issue

**Comment by nguyenbathanh** [comment]
@RobbeVanH 

Check your project if there is any models which has foreign key with related name `triggered_by_user` or `user`, it conflicts with `django-reversion`, change that field name.

**Comment by ifranco14** [comment]
@nguyenbathanh do you know why this happen? have you got a reference to the source code?
