### ISSUE TITLE
Allow making revisions mandatory?

### ISSUE THREAD

**Issue by matthijskooijman** [etianen/django-reversion#829]
Currently, a revision is only created if `create_revision()` is used, or the `Revision` middleware is used. If you forget to add `create_revision()` in some code path that modifies a model, you won't get a revision AFAICS. This can be a source of bugs, especially when there is some underlying code that modifies the model, but the revision should be created by a view higher up in the call stack (that has more info about what happens exactly).

Would it make sense to, when registering a model (or maybe globally) *require* revisions?

Currently, nothing happens in the post-save handler when no revision is active:

https://github.com/etianen/django-reversion/blob/c8d65bb6128c24000294fa3b5a29351e3fa6ac08/reversion/revisions.py#L326-L328

I guess this could be changed to either ignore `is_active()` when revisions are mandatory (in which case `_current_frame()` will raise an exception later), or the signal handler could just raise an exception right away (might be cleaner).

Also, since this is post-save, it should probably *also* generate a revision in addition to an exception (unless we're in a transaction? Not sure when post-save runs exactly).

https://github.com/etianen/django-reversion/blob/c8d65bb6128c24000294fa3b5a29351e3fa6ac08/reversion/revisions.py#L49-L52

A related question might be if a revision should be tied to a particular model, specified to `create_revision`? If I'm creating a revision and expecting to save some model, but as a side effect some other model gets saved too, I think it now ends up in the same revision, even when the save of the other model was wrapped in its own `create_revision` (though I've not tested this, this is from reading the code).

**Comment by etianen** [comment]
You can actually do this yourself very easily. Just use a `pre_save` signal, and raise an exception if `not revision.is_active()`.

If you want to ensure a revision context is always active, you can use `RevisionMiddleware`, but be aware that this introduces a per-request overhead that might be prohibitive for some applications.
