### ISSUE TITLE
Should add hook function for `create_revision()` make also store other info from request?

### ISSUE THREAD

**Issue by thomaszdxsn** [etianen/django-reversion#831]
Thank you awesome library.

Currently I used middleware, but I want also store User-Agent of request to comment field as JSON format

Inspect source code, but don't known how to add this function

**Comment by etianen** [comment]
Add your own middleware that runs after `RevisionMiddleware`. In your middleware, call `revision.set_comment(...)` to set the comment of the revision to whatever you want.
