### ISSUE TITLE
Menu not showing in Django 2

### ISSUE THREAD

**Issue by farooqaaa** [etianen/django-reversion#834]
If you use Baton's `admin.site.urls` in _urls.py_, the menu doesn't show. This can be fixed by using Django's admin URLs. I think this should be mentioned in the docs.

**Comment by etianen** [comment]
I don't understand what you mean by "Baton's admin.site.urls".

**Comment by farooqaaa** [comment]
Extremely sorry. I opened this issue in the wrong repository.

**Comment by etianen** [comment]
No worries! :D
