### ISSUE TITLE
Use natural key for serialization

### ISSUE THREAD

**Issue by matwey** [etianen/django-reversion#841]
Hi,

Is it any possible to use [natural keys](https://docs.djangoproject.com/en/3.0/topics/serialization/#natural-keys) when serializing relations?

I see that default Django `serializers.serialize()` is used for serializing, but there is no way to pass `use_natural_foreign_keys=True` or `use_natural_primary_keys=True`.

**Comment by etianen** [comment]
That's not supported, but I'd take a MR that put support in. It sounds
useful.
