### ISSUE TITLE
Django Reversion - How to set_comment with Django Rest

### ISSUE THREAD

**Issue by N0SYS73M1SS4F3** [etianen/django-reversion#845]
I'm trying to ***save comment***  in ***table reversion_revision***. However i still got ***empty value comment***

***`What i tried`***

**`In ModelViewset`**
```
class ReversionViewMixin(object):
    def dispatch(self, *args, **kwargs):
        with transaction.atomic(), reversion.create_revision():
            response = super(ReversionViewMixin,
                             self).dispatch(*args, **kwargs)

            reversion.set_comment('Hello')    # <------ This Line
            return response

class HistoryViewset(ReversionViewMixin, viewsets.ModelViewSet):
    queryset = Version.objects.all()
    serializer_class = VersionSerializer
    filter_backends = (filters.DjangoFilterBackend,)
```

Any Help, Pls :( Thanks in advance...

**Comment by etianen** [comment]
What aspect of that is not working? It looks superficially fine to me.

**Comment by N0SYS73M1SS4F3** [comment]
@etianen ***comment doesn't save at all*** (Thanks for ur reply)

**Comment by etianen** [comment]
In order for the comment to save, you must save at least one model that is
registered with django-reversion. So you need to mix in ReversionViewMixin
with a rest framework view, and then save a model using that rest framework
view.

There is no point mixin in ReversionViewMixin with HistoryView, since
HistoryView does not save any models registered with django-reversion.

**Comment by N0SYS73M1SS4F3** [comment]
@etianen Sorry i still cant *catch* u :(

*Can u give me any **hint**??*

**Comment by N0SYS73M1SS4F3** [comment]
@etianen i already **save new model** that is *registered* with **django-reverse**. However, the *issue* still *remain*. :(

**Comment by etianen** [comment]
Take ReversionViewMixin out of HistoryView. It does nothing.

Add it to one of your other model viewsets.

Create a model using a POST request to the model viewset with
ReversionViewMixin mixed in.

Verify that the ReversionViewMixin.dispatch() method is actually being
called using a print() statement.

The comment should be saved in the revision.

**Comment by N0SYS73M1SS4F3** [comment]
@etianen can u give me any ***example***??

**Comment by etianen** [comment]
Short of writing out a whole Django project for you, I've explained it as
well as I can.

If you were to share your codebase, I could take a look, and make a patch
to show you where you've gone wrong. I'll also happily answer specific
questions you have.

**Comment by N0SYS73M1SS4F3** [comment]
https://stackoverflow.com/questions/63664572/django-reversion-how-to-use-with-django-rest

Above is my question, i asked in ***stackoverflow***.
kindly, pls take alook :)
