### ISSUE TITLE
Multi database project

### ISSUE THREAD

**Issue by MaurizioPilia** [etianen/django-reversion#853]
I want to place Revisions and Version in a separate DB so i need to replace the User and CopntentType ForeignKeys with naturalkeys.
A strategy like django user model will be perfect to allow customize the django-reversion models.

**Comment by etianen** [comment]
Are you suggesting that there should be a way to swap out different Version
and Revision models? That sounds like it would add a bunch of complexity
for quite an edge use-case.

Why do you want to put the revisions and versions in a separate DB? If
you're on postgres, you can use tablespaces to place the tables on a
different physical disk. MySQL has a similar partitioning feature too.
That's almost certainly going to be better than using two different
databases.

**Comment by MaurizioPilia** [comment]
> If you're on postgres, you can use tablespaces to place the tables on a different physical disk

The issue is our main db is Oracle, we are planning migrate to postgres but not jet.
So i need some way to break the User and ContentType foreign keys and i rather not monkey patch it.

I was thinking something around the lines of how django handles [AbstractUser](https://github.com/django/django/blob/3.1.2/django/contrib/auth/models.py#L315) with  [get_user_model()](https://github.com/django/django/blob/3.1.2/django/contrib/auth/__init__.py#L152).

Its not so much complexity as it is abstraction, i don't see this as a total edge-case, but i could be wrong.
I definitely don't want to tell you how to run your library, any suggestions or advice are welcome.

**Comment by etianen** [comment]
It's not really a natural key you want. If your Revision and Version are in
a different table to User and ContentType, you want db_constraint set to
False on the ForeignKey field to these models.

This could be done by making Revision and Version swappable, but that would
allow users to swap-in models that were unsuitable in a million different
hard-to-debug ways, and I worry about supporting that. I'm not sure that
dropping the DB constraint on the foreign keys, for example, won't lead to
some bugs in the admin integration, which is currently assuming that the
foreign keys point to a valid model instance. If they don't, Django would
raise a DoesNotExist exception, which would be unhandled.

Oracle does support tablespaces, allowing you to partition your database
across multiple disks. That would allow you to gain the IO advantages of
multiple databases without needed a separate database.
