### ISSUE TITLE
Logging of Deletion. Relation between django-reversion and LogEntry.

### ISSUE THREAD

**Issue by tuttle** [etianen/django-reversion#854]
Hi Dave,
when adopting `django-reversion` to project, does that mean the `LogEntry` table is not used anymore?

Well, I did my homework, so I noted decoupling from `django.contrib.admin` as well as https://github.com/etianen/django-reversion/pull/806 and some other commentary. I'm sorry, I still miss the bigger picture.

The history view on the object seems to use the reversion's tables only.

Do you see any remaining benefit from `LogEntry`?
  * For this I found the *deletion* is not recorded in reversion's history, so it stays in `LogEntry` and when the user is not using admin, the information is nowhere. This makes the reversion less usable for a lightweight auditing.
  * Any other benefits from the log doubling?

At least reverting the objects via admin still saves LogEntries, but its change_messages are rather misleading, missing info.

The LogEntry and Reversion items unfortunately cannot be paired in any way (for example using microseconds), which seems to block the developer from adding some custom change (e.g. machine readable) info via LogEntries.

What's your position on the logging data duplication now, from your long-running maintaining experience?

If I may, I think making the matter clear in the docs would be great.

Thank you very much (for this project and for the time devoted).

**Comment by etianen** [comment]
django-reversion does precisely nothing with LogEntry. Deliberately.

There's a lot of overlap between their functionalities, and a lot of
differences. LogEntry records add/change/delete events in a human -readable
form. Revision records snapshots of relatives models in a machine-readable
form with optional tagging of user and comments. If you want to attach
additional machine-readable metadata, use reversion.add_meta, not LogEntry.

I don't think there's much to document. They're both documented
individually and neither affects the other.

**Comment by tuttle** [comment]
Thank you. I'd say your response is something the documentation could use. I believe newcomers could wrap their heads around the concepts sooner. Especially when there were times the situation was different and django-reversion did at least mention LogEntry in the docs (Google finds it, it's not clear right away it's an old doc).

Personally, I like django-reversion, but I do miss the "Object deleted" info. I know you explained your reasons before for not including the feature to django-reversion. You probably got tired of it. It's just that I see it as a missing feature that would make django-reversion a complete solution for my purposes.

A configurable feature of django-reversion adding the deletion meta info would be great. Or the officially documented way anyone could do it without fear of django-reversion to terminate the support for a hacked solution.

Thank you.

**Comment by etianen** [comment]
A missing feature that breaks django-reversion is best left missing, IMO. :P

Writing docs is a balance of too much versus too little information. Adding
more information buries other information. I think they're best left as
"getting started" and "reference".
