### ISSUE TITLE
django-reversion 3.0.8 compatibility with Django 1.11

### ISSUE THREAD

**Issue by erikrw** [etianen/django-reversion#857]
Hi,

There's a mismatch between pypi/setup.py https://github.com/etianen/django-reversion/blob/4765d9759137e65ee25e50bf7977e65e3c998c32/setup.py#L38 which says that django-reversion 3.0.8+ require Django 1.11+

and Read the docs/CHANGELOG.rst https://github.com/etianen/django-reversion/blob/master/CHANGELOG.rst#308---2020-08-31 which says Django 1.11 LTS support has been dropped.

Which one is correct?

**Comment by etianen** [comment]
Oops. Trust the changelog.

I'll fix the setup.py now.

**Comment by erikrw** [comment]
Cool. In that case, should https://github.com/etianen/django-reversion/blob/master/README.rst#requirements also be updated?

**Comment by etianen** [comment]
Yes! :S

How about you PR me with any/all irregularities you find? I'll merge it
happily!

**Comment by erikrw** [comment]
Done. (I wasn't sure what the next supported version would be among 2.0/2.1/2.2, but I see 2.0 in setup.py)

**Comment by etianen** [comment]
Thanks, and merged! Any other issue you see, drop in a new MR :)
