### ISSUE TITLE
Postgres rollbacks on responses status_code >= 400

### ISSUE THREAD

**Issue by colegatron** [etianen/django-reversion#861]
Django-revisions provoke rollbacks on POST requests returning an status code>=400.

I have DRF Apiview (django 2.1, legacy app) used to add users to an application. 
It returns a status_code 200 when the user is created and a 400 if the user already exists on the application. 
In any case the apiview should write into a 'events' table the action performed:
`Events.objects.create(action='user-registration', result='ok/ko', otherinfo='whatever')`

Whenever I have enabled the revisions middleware the following code does not work as expected, getting a rollback in any POST returning a status code >=400. No idea why revision is affected by that or how overcome it.

This works:
```
    class register_user(APIview):
      def get(self,request):
        Events.object.create(action='register-user',result='fail',otherinfo='this is saved')
        return JsonResponse(status=400, data={'status': 'ko','data':'forced fail'})
```
This does not saves Events entity (or anything done in the :
```
    class register_user(APIview):
      def post(self,request):
        Events.object.create(action='register-user',result='fail',otherinfo='this is not saved')
        return JsonResponse(status=400, data={'status': 'ko','data':'forced fail'})
```

I had to disable revisions since I couldn't find how to avoid it. Any clue?
Thanks

**Comment by etianen** [comment]
The behaviour of revision middleware is to roll back any view where the
status is >= 400. This is suitable for basic applications, but doesn't work
with your setup.

I would look into the low level API, and use create_revision to mark up
blocks of code in revisions:

https://django-reversion.readthedocs.io/en/stable/api.html#revision-api

It will be more performant and controllable.You can even make your own view
mixin to add the behavior.

**Comment by colegatron** [comment]
As far as I understand the purpose of revision is to keep track to changes on records
So why it takes ANY decision about what to do depending on something completely unrelated to the purpose of keeping track of changes?

**Comment by etianen** [comment]
The revision middleware wraps all data-mutating views (e.g. POST, PUT,
PATCH, DELETE) in a transaction and a revision context. The transaction is
important as it ensures integrity between reversion and the data it's
tracking. In the event of an error response, the revision is not saved.

Right now, "not saving the revision" also involves rolling back the
database transaction. But, taking another look at the code, there's no
reason it needs to do that. I can take a look at this over the weekend, and
hopefully change this behavior for the better.

**Comment by colegatron** [comment]
In any case, thank you for the package, it is really useful to have an easy way to proof who deleted or modified a record whenever a "I didn't touch anything" answer jumps out during a business issue.

fyi; 
In my trials to keep the revision active but still ensure the 'events' table is committed I removed the @reversion.register() from the Events model, but that didn't worked.
I wondered that if the model is not under revision it wouldn't be affected by the transaction rollback but it was.

On the other side, from my point of view, the revision should not keep track of what the data-mutating views returns at all.
If I want to return a 500 but still doing anything with the database it is my own business, but still I expect revision keep track of the models instances changes due the @reversion.register() decorator.

**Comment by etianen** [comment]
Fixed in master. This is a breaking change, albiet one that's unlikely to affect anyone.

Please take a look :)
