### ISSUE TITLE
i can't connect to my db in another middleware when i using django-reversion

### ISSUE THREAD

**Issue by Sifb71** [etianen/django-reversion#864]
i create a custom middleware  to save my exceptions.

my code is :
```
class RequestLogMiddleware(MiddlewareMixin):

      def process_exception(self, request, exception):

                          // some code

                          ExceptionLog.objects.create(
                                  user_id_integer=user,
                                 file_name=file_name,
                        .....
                        // some code

```
but when i using django reversion ExceptionLog.objects.create() function dont working and save nothing to my db.

when i remove django reversion middleware  from my setting.py, every thing working!

Does anyone know the problem?

**Comment by etianen** [comment]
Try using the master branch of django-reversion. It includes a fix for this
issue.

**Comment by Sifb71** [comment]
i using the master branch of django-reversion but not working.
objects.create() returned "ExceptionLog object (id)" but nothing inserted in my table!
i have semillar problem in process_request() function in custom middleware and resolve it by change my middleware list sort! but this not working!

**Comment by etianen** [comment]
Are you sure you're using the master branch? I pushed up a fix for this
problem last Saturday.

The latest release on pypi does not have the fix.

**Comment by Sifb71** [comment]
yes. i clone from master branch, remove old revision packages and run setup.py to install this version.
can you test it?
@etianen

**Comment by etianen** [comment]
Hmm. Can I see your middleware order?

**Comment by Sifb71** [comment]
[
    'corsheaders.middleware.CorsMiddleware
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'reversion.middleware.RevisionMiddleware',
    'ymh.middleware.request_log_middleware.RequestLogMiddleware',
    ]

**Comment by etianen** [comment]
Try swapping the order of RequestLogMiddleware and RevisionMiddleware

**Comment by Sifb71** [comment]
i found a problem! 
code worked for GET method and if Exception occurs in GET method, logs saved in db but in other methods (such as POST , DELETE,...) not working.

**Comment by etianen** [comment]
Yes, because revisionmiddleware only kicks in for mutating methods (POST,
DELETE etc).

Have you tried swapping the order of RequestLogMiddleware and
RevisionMiddleware?

**Comment by Sifb71** [comment]
yes, i try it and not work.

**Comment by etianen** [comment]
In that case, I suggest you subclass RevisionMiddleware like this:

```py
from reversion.middleware import RevisionMiddleware

class NonAtomicRevisionMiddleware(RevisionMiddleware):
    atomic = False
```

And use this middlware instead.

This will disable wrapping requests in a database transaction.

I actually have a similar problem to this in an app I manage. Logging errors to a database is a bit awkward, as an error often results in a transaction rollback, which also rolls back the logged exception! A typical approach is to have a threadpool used to log expections to the database, which ensures the log messages are saved to the database irrespective of whether a database transaction is currently taking place. In other words, you have a dedicated database connection for logging, which separates the log records from the other records in the current atomic block.

**Comment by Sifb71** [comment]
worked!
I hope there will be no problem in the future.
Thank you.
