### ISSUE TITLE
create_revision block ignored; workaround: generally exclude one field type?

### ISSUE THREAD

**Issue by stefanvollmar** [etianen/django-reversion#865]
We use our own model field derived from Django’s filefield. Our class uses an extensive logging method containing its own `with reversion.create_revision()` block which is also called in the field’s `pre_save()` stage. Our logging works fine for all changes outside of Django admin - but when a new file is uploaded via Django admin, we get a generic Reversion entry and our `create_revision` block is just ignored - can we change that (having two Reversion entries for any new uploaded file is not a problem for us)? We use our own filefield replacements extensively and want to avoid having to manually exclude all those fields from automated Reversion processing. Or maybe there is a simple way to generally exclude our filefield class? Many thanks in advance!

**Comment by etianen** [comment]
In your case, I would not use the RevisionAdmin, but write your own
ModelAdmin subclass that uses your own revision logic. That way you get
complete control over the revision saving process, and it sounds like
you've done most of the work for that already.
