### ISSUE TITLE
automatic comments are empty

### ISSUE THREAD

**Issue by urzbs** [etianen/django-reversion#868]
I noticed when changing a model instance in the admin panel, a comment is added into the revision that tells us which field(s) (labels) have been changed.

If I instead use a UpdateView, then these comments are not added (empty). 

Is there a way to enable this or am I missing something?

Trying out this django package for the first time, so far i like it very much.

**Comment by etianen** [comment]
Hi,

Unfortunately, those comments are generated by the Django admin system, and
the logic, last time I checked, isn't easily extractable.

I'd suggest examining the source code of the Django admin and porting the
change message over for use in a view.

Dave.
