### ISSUE TITLE
django-yearlessdate objects being marked as changed when saved on django-admin with no changes to it

### ISSUE THREAD

**Issue by sayeghr** [etianen/django-reversion#869]
Hey team, I'm trying to fix an issue where a field using django-yearlessdate is always being marked as changed whenever a save is made on django-admin even though the django-yearlessdate isnt being changed. 

How does django-reversion determine that a field is dirty and should be included in a reversion history?

django-yearlesdate (https://github.com/seddonym/django-yearlessdate)

**Comment by etianen** [comment]
It doesn't. It lets django admin determine the change message. This implies
django-yearlessdate is triggering the django-admin change detection
somewhow. I'd raise an issue with them.

**Comment by sayeghr** [comment]
Thank you. Your response helped me identify the deficiency in the other library. I'll create a PR for the other library.

Thanks!
