### ISSUE TITLE
Django 3.2.4 Upgrade - DEFAULT_AUTO_FIELD

### ISSUE THREAD

**Issue by leonardodepaula** [etianen/django-reversion#873]
After upgrading to Django 3.2.4 I started to receive those warning messages:

WARNINGS:
reversion.Revision: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
reversion.Version: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.

How can I set default_auto_field for django-reversion?

Thanks.

**Comment by etianen** [comment]
This warning is harmless for Django 3.2. This will be fixed in the next
reversion release. Alternatively, I'll take a MR to fix it now.

**Comment by leonardodepaula** [comment]
Thanks, @etianen.

**Comment by Peter-van-Tol** [comment]
Done, hopefully it can be part of the next release!

**Comment by etianen** [comment]
Definitely :)
