### ISSUE TITLE
No migration when Reversion is added to the project.

### ISSUE THREAD

**Issue by skaidan** [etianen/django-reversion#875]
Hi!

Python 3.6.9
Django 2.2

pip install django-reversion==3.0.9

#Added 'reversion' in Installed apps

python manage.py migrate  -->  No migrations to apply.
python manage.py makemigrations  -->  I needed to try... but no changes...

python manage.py showmigrations  and no django-reversion app section.

Output:

![image](https://user-images.githubusercontent.com/12232701/121883429-03b17900-cd12-11eb-8f31-548e88df4a58.png)

It seems package is imported  but no migrates so data does not match.

Any tips are very welcomed

**Comment by skaidan** [comment]
Hum... okey... I have removed everything... container , virtual env... Reinstalled and now it goes awesome.

**Comment by etianen** [comment]
Cool cool. Pip can something go a bit wrong if it's interrupted.
