### ISSUE TITLE
Validation Error results in blank reversion comment

### ISSUE THREAD

**Issue by SiddChugh** [etianen/django-reversion#877]
Steps to reproduce:

-  Create an Admin model and inherit from `VersionAdmin`.
- Add an `inlineModelAdmin` object.
- Try editing the object to get a `ValidationError`.
- Click on the `history` button of the model admin and you would notice a version with empty `action` field.

If it's not a bug, is there a way to not store/display these versions in the `history` tab.

**Comment by etianen** [comment]
Where are you raising the validation error? In a custom form, or in the
model?

**Comment by SiddChugh** [comment]
Model.

**Comment by SiddChugh** [comment]
@etianen any updates to what might be going wrong here?

**Comment by etianen** [comment]
Are you using a 3rd party admin subclass?

The reason I ask, is that django-reversion will only create a revision if a
model is created/updated within the admin view. Under normal operation, if
an admin form raises a validation error, no models will be saved, so no
revision will be created.

In your case, it seems that somehow something is being saved, despite the
validation error being raised.

It would be useful to see what is inside these revisions with empty
comments. Get the ID of the revision by loading it up and looking in the
browser URL bar. Then using the ./manage.py shell, try:

from reversion.models import Revision
revision = Revision.objects.get(id=your_empty_revision_id)
print(v.object for v in revision.version_set.all())

That'll show you all the model snapshots saved in the revision, and we'll
get to the bottom of what's causing this issue.

**Comment by SiddChugh** [comment]
Hey, you were right. I was saving the object somewhere else before throwing a validation error in my view. 
Closing the ticket.
