### ISSUE TITLE
All versions of current model shows the latest version of inline models, even though it doesn't belong to that version

### ISSUE THREAD

**Issue by drishti-m** [etianen/django-reversion#878]
I have two models

```
models.py

class LegalEntity(models.Model):
  company_number = models.CharField(max_length=45, null=True, blank = True)
  country = models.CharField(max_length=45, null=True, blank = True)
  

class Editorial(models.Model):
   legal_entity = models.ForeignKey(LegalEntity,)
   title_en = models.CharField(max_length=1024, primary_key=True, blank=True)
   notes = models.CharField(max_length=1024, primary_key=True, blank=True)
 
.....
```
And, my admin looks like this

```
admin.py

class EditorialInline(admin.TabularInline):
    model = Editorial


@admin.register(LegalEntity)
class LegalEntityAdmin(VersionAdmin)
 inlines = [EditorialInline,]

@admin.register(Editorial)
class EditorialAdmin(VersionAdmin):
    pass

....
```

I run the commands
```
python manage.py makemigrations
python manage.py migrate
python manage.py createinitialrevisions
python manage.py runserver
```
Now, I log in to my admin page, and add legal entity.

- In first version, I only change the fields of model `LegalEntity`. I save it. The editorial inline fields are blank right now.
- Then, I make changes in the inline model `Editorial` in `LegalEntity` page. I add the fields `title_en` and `notes` of the inline `Editorial`.

Now, I click on *History* , and it shows two versions. Both of the versions show the latest change in inline model `Editorial` even though I made the change in `Editorial` inline only in the second version. Other fields of `LegalEntity` have as expected versioning. Only the inline models seem to have a versioning problem.

 Ideally, I would want that the first version show the `Editorial` inline fields blank because I had not added it in the first version. 
How can I achieve this?
Am I missing something here? Is there a way to fix it?

I am using django version 3.2.4 and django-reversion version 3.0.9

**Comment by etianen** [comment]
Depending on the order you declare your admin classes, you'll get different
results.

1. If EditorialAdmin is being loaded first, it will assume Editorial is a
top-level model and not register any relationship between Editorial and
LegalEntity.
2. If LegalEntityAdmin is being loaded first it will assume Editorial is a
child model of LegalEntity and set up a relationship between the two.

I think scenario (1) is happening.

In general I would avoid a model appearing as both an inline and a
top-level model in the admin. Having two places where a user can edit a
given object is confusing, IMO. When it comes to revisions, the situation
is worse, as the coupling is stronger. Would a user expect that reverting
an Editorial would also revert a LegalEntity?

**Comment by drishti-m** [comment]
The idea is that each legal entity can have multiple editorials. So, in the admin page of legal entity, we would ideally want all fields (including related models) of LegalEntity, so that it is easy for the user to edit records of legal entity. To achieve this, I want to use the inline feature in admin. And, I have hidden the Editorial Admin (which would otherwise be displayed as a separate admin page), because we already have Editorial admin as inline in LegalEntity.

So, I have 
```
@admin.register(Editorial)
class EditorialAdmin(SimpleHistoryAdmin):
 
     def get_model_perms(self, request):
         """
         Return empty perms dict thus hiding the model from admin index.
         """
        return {}

```

SInce each Editorial entity is linked to LegalEntity, and the admin page of LegalEntity shows LegalEntity form and inline form for Editorial, and after editing all fields, the user clicks "Save" finally on the LegalEntity admin. And, if the user wants to revert to this version, they would ideally expect to have that particular version of LegalEntity and Editorial and their relations. 

For example
- 1) In first time, I fill legal entity: company = 'A34', and country = 'DE', and Editorial: title = 'First change' (all on the same page of Legal Entity)
- 2) In the second save for the same legal entity (ie company = 'A34'), I add another editorial record  with title = 'Second change'(all on the same page of Legal Entity).
- 3) Then, I delete first editorial record with title = 'First Change' from legal entity admin and save legalentity (all on the same page of Legal Entity)

Now, when I click on history of this LegalEntity, I would want the first version to show i. with only first editorial,
second version to show  ii. with both editorials, and third version to show only the second editorial.

Is it possible to achieve this?

Thank you!

**Comment by etianen** [comment]
Yes. That's the expected behaviour when you only register Editorial as an
inline.

If you want that behaviour, you should comment out or delete
EditorialAdmin, and just use LegalEntityAdming with EditorialInline

**Comment by drishti-m** [comment]
The problem is:
the model `Editorial` is also as one to one field in another model `Policy`. And, we need to access the `editorial` form from `Policy` form (`Policy` is displayed as inline to `LegalEntity`). To achieve this, we need EditorialAdmin. But, we hide it from the UI such that Editorial is only displayed as inlines, and not a separate admin.
```
@admin.register(Editorial)
class EditorialAdmin(SimpleHistoryAdmin):
 
     def get_model_perms(self, request):
         """
         Return empty perms dict thus hiding the model from admin index.
         """
        return {}
```
Note: this complex relationship of Editorial with all the models is achieved with Generic foreign keys and generic relations.

**Comment by etianen** [comment]
I would register your models with reversion manually in your models.py
file. You can use reversion.register() and the `follow` argument to ensure
all relations are followed as desired (set up relations to follow in both
directions for the FKs and generic FKs). That way, you're not relying on
any auto-registration in the admin class, and can make sure everything is
grouped properly.
