### ISSUE TITLE
Use django-reversion without django.contrib.auth?

### ISSUE THREAD

**Issue by AgarwalPragy** [etianen/django-reversion#879]
Removing `'django.contrib.auth'` from `INSTALLED_APPS` in settings.py causes the following errors with django-reversion

```py
SystemCheckError: System check identified some issues:

ERRORS:
reversion.Revision.user: (fields.E300) Field defines a relation with model 'auth.User', which is either not installed, or is abstract.
reversion.Revision.user: (fields.E307) The field reversion.Revision.user was declared with a lazy reference to 'auth.user', but app 'auth' isn't installed.
```

My usecase is a desktop application, that uses a local sqlite database to store user's data. Since there is only 1 user who is always assumed to be authenticated, I don't need `django.contrib.auth` at all. I don't even need a user model.

How do I configure django-reversion to work without any user model and without any auth?

**Comment by etianen** [comment]
I think you're going to need to have the foreign key point to some model,
as I'm not aware of any way in Django to make a conditional foreign key.

You could define your own empty fake user model and specify it in the
AUTH_USER_MODEL setting. Or just use auth app and don't create any users. A
few empty DB tables are pretty harmless.
