### ISSUE TITLE
Revisions in the context of celery tasks triggered by post_save signals

### ISSUE THREAD

**Issue by leonardodepaula** [etianen/django-reversion#881]
This is related to #612.

Considering the explanation given on issue #612, my celery tasks are creating new revisions using the @reversion.create_revision() decorator on top of the function. However, the user responsible for the action was not filled when the celery task was triggered by a post_save signal.

I managed to fill that gap using a middleware that gets the request user. I retrieve the request user inside the receiver and pass it to the celery task as an argument.

Is there a way to do that built in on revision?

Thanks!

**Comment by etianen** [comment]
Pass the user to the celery task as an argument. Inside the celery task,
use reversion.set_user() to set the user from the argument.

https://django-reversion.readthedocs.io/en/stable/api.html

You could turn this into a decorator that combines
reversion.create_revision() and reversion.set_user() if you need to do it
in a lot of places.

**Comment by leonardodepaula** [comment]
Thank you, @etianen. I will check that.
