### ISSUE TITLE
Deletion user not saved in deleted versions.

### ISSUE THREAD

**Issue by dennybiasiolli** [etianen/django-reversion#882]
It seems strange, but I can't see the user who deleted the record.
In the `revision` the only thing I can see is the last user who changed/created the record.

```json
    "revision": {
        "date_created": "2021-08-02T11:55:50.448244+02:00",
        "user": null,
        "comment": "Initial version."
    },
```

Is this intended or it's something who needs a fix?
I can take a look at it and provide a PR if it needs a fix.

**Comment by etianen** [comment]
This is by design. More information can be found in #164
