### ISSUE TITLE
Feature to get next and previous versions of a versioned model instance.

### ISSUE THREAD

**Issue by anudeepsamaiya** [etianen/django-reversion#889]

**Comment by etianen** [comment]
```
versions = Version.objects.get_for_object(some_obj)
latest_version = versions[0]
next_version = versions[1]
```

**Comment by anudeepsamaiya** [comment]
This makes a db request for getting each item whether next or previous. It would be useful to have an iterator that when invoked fetches the bunch of version objects and iterates over them.

`type(version_obj.next) is a <class 'generator'>`

```
version = Version.objects.get_for_object(some_obj)[5]
for next_version in version.next:
      do something with next_version

for prev_version in version.prev:
     do something with prev_version
```

We will need to create a cached list of prefetched item in iterator and retrieve items from it in next or previous calls? I am open to discuss the implementation and raise a PR too.

**Comment by anudeepsamaiya** [comment]
> ```
> versions = Version.objects.get_for_object(some_obj)
> latest_version = versions[0]
> next_version = versions[1]
> ```
This makes a db request for getting each item whether next or previous. It would be useful to have an iterator that when invoked fetches the bunch of version objects and iterates over them.

type(version_obj.next) is a <class 'generator'>

version = Version.objects.get_for_object(some_obj)[5]
for next_version in version.next:
      do something with next_version

for prev_version in version.prev:
     do something with prev_version

We will need to create a cached list of prefetched item in iterator and retrieve items from it in next or previous calls? I am open to discuss the implementation and raise a PR too.

**Comment by etianen** [comment]
To avoid a db request per item, just buffer the queryset in a list.

```
versions = list(Version.objects.get_for_object(some_obj))
latest_version = versions[0]
next_version = versions[1]
```

Or, to iterate in a particular direction:

```
versions = Version.objects.get_for_object(some_obj).iterator()
latest_version = next(versions)
next_version = next(versions)
```

The Django ORM and Python stdlib already makes this sort of thing very easy.
