### ISSUE TITLE
Feature to fetch versions of models/queryset defined by `follow`

### ISSUE THREAD

**Issue by anudeepsamaiya** [etianen/django-reversion#890]
```
@reversion.register()
class Parent(models.Model):
    name = models.CharField(max_length=50)
    is_enabled = models.BooleanField(default=True)


@reversion.register(follow=["parent"])
class Child(models.Model):
    parent = models.ForeignKey(Parent, on_delete=models.PROTECT, null=True)

```

So every time we make any change to `Child` table, a version for `Parent` is also created which is linked using the `revison_id`.

Now when I get all the versions for a `Parent`, I dont get the changes of the `Child` table which created the version entry for the `parent` table.

**Comment by etianen** [comment]
Isn't that exactly what `Version.objects.get_for_model(..)` does?

**Comment by anudeepsamaiya** [comment]
> Isn't that exactly what `Version.objects.get_for_model(..)` does?

This only gets the version for the `Parent` or `Child` in isolated way. There is no way get them together.

`Parents` version history should provide the context of `Child`, when a version of `Parent` is created due to `Child` changes.

**Comment by etianen** [comment]
Get a `Revision` representing all related models in a a revision,

```
version = Version.objects.get_for_model(...)
revision = version.revision
```

Then you can do whatever...

```
parent_version = revision.version_set.filter(content_type=ContentType.objects.get_for_model(Parent)).first()
child_version = revision.version_set.filter(content_type=ContentType.objects.get_for_model(Child)).first()
```
