### ISSUE TITLE
[Feature] History diff

### ISSUE THREAD

**Issue by shawnngtq** [etianen/django-reversion#894]
This library is awesome! 

I think it will be better if we can compare the difference between versions. Like linux / git diff on the admin side.

How I am doing it now is compare the `revision_version.serialized_data`.

**Comment by rposborne** [comment]
This is a feature of the rails equivalent of Django reversion, [papertrail](https://github.com/paper-trail-gem/paper_trail).   They are stored in an "object_changset" json blob.   with a `{ property: [previous, current] }` format. 

I think it would be possible to achieve this via the signals pre-commit hook. Where the new reversion changes are diffed against the current state object.

**Comment by shawnngtq** [comment]
Closing this.

I prefer package with >= 1k GitHub stars, as they are less likely to be sunset.

For vanilla method, we can use a post-save signal to store the difference. However, I don't do it due to performance concern.
