### ISSUE TITLE
Update test matrix to test Django 3.2 against Python 3.10

### ISSUE THREAD

**Issue by amrishparmar** [etianen/django-reversion#900]
Django recently [released version 3.2.9](https://docs.djangoproject.com/en/3.2/releases/3.2.9/) which adds support for Python 3.10 in Django 3.2, so might make sense to update the matrix in `python-package.yml` workflow to test against this version.

**Comment by etianen** [comment]
Good point. I'll take an MR for this, or look into it myself at some point.

**Comment by etianen** [comment]
Fixed with f259930b12aa982f27c09ea9e3e676321c59fa58
