### ISSUE TITLE
django-reversion on PyPI is version 5.0.0, but this GitHub repo has version 4.0.0

### ISSUE THREAD

**Issue by Flimm** [etianen/django-reversion#905]
The version on PyPI is 5.0.0:

https://pypi.org/project/django-reversion/#history

But on GitHub, it's 4.0.0:

https://github.com/etianen/django-reversion/blob/master/reversion/__init__.py

**Comment by Flimm** [comment]
Never mind, it looks like it is fixed now. I'm not sure why I missed it.

**Comment by etianen** [comment]
Wat. Weird. :P
