### ISSUE TITLE
Update documentation regarding changelog on readthedocs.io

### ISSUE THREAD

**Issue by everspader** [etianen/django-reversion#908]
The latest available version according to the documentation found in https://django-reversion.readthedocs.io/en/stable/changelog.html points to version 4.0.0, which makes admin site incompatible with Django 4.0+.

According to [this](https://github.com/etianen/django-reversion/commit/c83c93d9fc5149b48d563d1bd281c5aa33bf6b97) commit, the fix was done in a later patch.

**Comment by Flimm** [comment]
The changelog only includes changes up to django-reversion 4.0.0, but since then, there have been other releases, namely django-reversion 4.0.1, 4.0.2, 5.0.0, 5.0.1.

**Comment by etianen** [comment]
Ah, looks like the readthedocs builds just started silently failing one day. Thanks for the spot!

I've fixed this in master, so the latest docs builds are as expected.

https://django-reversion.readthedocs.io/en/latest/changelog.html

The stable docs will update on next django-reversion release.
