### ISSUE TITLE
[Question] Reversion middleware HTML form action

### ISSUE THREAD

**Issue by shawnngtq** [etianen/django-reversion#911]
I use reversion middleware, and it automatically adds request, that is great!

I noticed that for admin UI changes, `Action` field will be populated. But for HTML form, it wouldn't.

Anyway to do it?

Thanks!

**Comment by etianen** [comment]
Unfortunately, no. The change message is part of the base Django admin
class and can't be used outside of it.

You can write your own message using reversion.revisions.set_comment(...)

**Comment by shawnngtq** [comment]
Gotcha, that's unfortunate, really love the change message, it's super helpful

**Comment by etianen** [comment]
Agreed. Maybe PR Django to extract that feature into another helper in `django.utils`. It sure would be useful.
