### ISSUE TITLE
Can `user` be removed from revision?

### ISSUE THREAD

**Issue by Guo-Zhang** [etianen/django-reversion#915]
I am using DRF with my own auth model. My auth model doesn't need to be managed by the database since it is in a microservice system, but revision requires me to give a AuthUser model. 

Besides, it seems not necessary to force to have a user model.

I have also noticed that the documentation seems outdated, and it is not clear enough for users. I am willing to help you on that if you need.

**Comment by etianen** [comment]
The user field is nullable, so you can just never set it. This requires having a User model in the database still, but the table can be empty. You can replace it with a stub model if you prefer.

Removing the field would remove a field that is useful for 99% of users. django-reversion aims to be a "good enough" solution for most people.

The documentation wasn't building properly for a while. It was fixed a month ago, but I hadn't pushed out an update to the "stable" tag. That's just been done, thanks for the spot!
