### ISSUE TITLE
Select Database for Revision

### ISSUE THREAD

**Issue by stefanschlipfi** [etianen/django-reversion#918]
Good Day,

first of all tanks for this amazing module !

I have the following use case:

2 Apps registered in Django:
app1 and app2

app1 uses another database as app2
The default django database is on another database too.

Is it possible to change the database for the revisions, because now the revisions from app1 and app2 where stored in the django default databse.

**Comment by etianen** [comment]
Can you configure a database router to route the django-reversion models to a different database?

https://docs.djangoproject.com/en/4.1/topics/db/multi-db/

**Comment by etianen** [comment]
You can choose the default database for revisions using a Django database
router:

https://docs.djangoproject.com/en/4.1/topics/db/multi-db/#automatic-database-routing
