### ISSUE TITLE
Using fixtures to initialise versioned inline data

### ISSUE THREAD

**Issue by nybl** [etianen/django-reversion#931]
Hey, apologies if this is a known thing, but I've been unable to find an answer in the docco.

I'm trying to use fixtures to initialize some standing data for a Django Admin based application.  Having loaded the fixtures, I call createinitialrevisions to initialize Reversion. The problem I'm having is that inline objects are being initialized with separate revision_ids to their parents in the reversion_version table (these are simple value objects, rather than being first class entities, and have no lifecycle outside their containing parent).  I guess this makes sense as Reversion does not know which objects need to be versioned together.  This means that if I amend or delete these parent objects, their dependent inline objects are not tied to the parents correctly, and cannot be reverted or recovered with them.

If I use the Admin GUI the relationship between the parents and inline objects is known, and Reversion can group the changes together correctly.  However, for the initial bulk loading of data this isn't a practical approach.

Is there some way to tie data loaded through fixtures together so that Reversion knows what is going on when createinitialrevisions is called?  If not, is there a recommended way to programmatically initialize related standing data in a Reversion friendly way?

Thanks for any pointers.

**Comment by etianen** [comment]
Are you registering models manually using `reversion.register`, or relying on the admin auto-registration?

**Comment by nybl** [comment]
Apologies for the delay in getting back to you.  Initially I used auto-registration, however, some of my inlines were not being picked up, so I decorated these with reversion.register calls with no parameters.  This seemed to get things started, however, the inlines found within fixtures seemed to be loaded individually.  At this point I stopped and went down the route of some simple custom admin commands to load data from JSON fixture files with inlines nested wthin the main entities.  This works well as it allows reversion transactions to be set up explicitly.  I'm sure this isn't the accepted route, but it has sorted out 99% of the issue for me at the cost of a little more boilerplate code.

**Comment by way-dave** [comment]
Odd. Your approach of manually saving reversion transactions will all relevant inlines will work, but it's a bit of a pain.

The admin integration should correctly configure the main model, and all inlines, using appropriate `follow` arguments to `reversion.register`. If it's not working, I'd be interested to see your specific admin integration, and hear what's not being set up correctly.
