### ISSUE TITLE
[enhancement] Storing serialized_data in a JSONField instead of a TextField?

### ISSUE THREAD

**Issue by scur-iolus** [etianen/django-reversion#938]
Since [version 3.1.](https://docs.djangoproject.com/en/4.1/releases/3.1/#jsonfield-for-all-supported-database-backends) (released in August 2020, almost 3 years ago), Django includes `models.JSONField` (and `forms.JSONField`) that can be used on all supported database backends. The [model field](https://docs.djangoproject.com/en/stable/ref/models/fields/#django.db.models.JSONField) supports the introspection, lookups, and transforms. Previously, this feature was only available to PostgreSQL users. This `JSONField` could allow us to store semi-structured data in the database.

For now, `django-reversion` uses a `models.TextField` to store serialized data. Wouldn't it be nice to replace that field by a `JSONField` when the data is stored as JSON, that is to say when `version.format=="json"`? Storing JSON encoded data instead of raw strings would enable us to benefit from [JSON querying in Django ORM](https://docs.djangoproject.com/en/stable/topics/db/queries/#querying-jsonfield), which could pave the way for plenty of new use cases. For instance: filtering very efficiently a QuerySet of `Version` instances by the content of the underlying serialized data. That would be all more consistent that the vast majority of `django-reversion` users probably already stores serialized data as JSON (since this is the default serialization format).

Assuming the pull request #928 will be merged soon, this could come under a new setting in the `DEFAULT` dictionary, which could be named `USE_JSONFIELD` (or anything else more explicit). Of course, it would be `False` by default, for backward compatibility with previous versions (😅) of the extension.

I'm aware that such a feature would imply significant changes in `django-reversion` / could even lead to breaking changes / memory overhead, depending on the implementation. That would obviously not be an easy step. But in the long run, don't you think that the idea might be relevant?

**Comment by etianen** [comment]
I'm not sure how this could be implemented. A database field that is one type or another based on a setting is tricky, since the migrations would have to vary depending on that setting too! And if a user changed the setting after running the migrations, a new migration would have to be made, and where would Django store it?

I'm not sure Django really supports the idea of a database field that is dependent on a setting. I fear this would cause a lot of weird behavior for people.

> filtering very efficiently a QuerySet of Version instances

Unfortunately, this would still likely involve a sequential table scan in postgres. It's likely that for large tables this would still be prohibitive.

**Comment by etianen** [comment]
Rewriting this project to only support PostgreSQL and JSON serialization would allow indexing on the versioned data, yes.

The loss of general usefulness to support a single use-case seems like a bad tradeoff to me.

If efficient introspection of the versioned data is required, I'd suggest going one step further and having a dedicated version table for each model. That would avoid any JSON overhead whatsoever.
