### ISSUE TITLE
Admin: 'GET' on a change_view creates a transaction block

### ISSUE THREAD

**Issue by gersmann** [etianen/django-reversion#940]
I noticed that loading change_view pages is slower when using reversion, due to a transaction block being opened. If I replace the implementation of `create_revision` with:

```
    @contextmanager
    def create_revision(self, request: HttpRequest):
        if request.method == "GET":
            yield
        else:
            with create_revision():
                set_user(request.user)
                yield
```

This goes away. Is there a reason for wrapping change_view `GET` requests in a `create_revision` block?

**Comment by etianen** [comment]
Good idea.

I'd take a PR to use `_request_creates_revision` to conditionally create the revision in the admin.
