### ISSUE TITLE
following OnetoOneField

### ISSUE THREAD

**Issue by gitanupam** [etianen/django-reversion#942]
I see that ForeignKeys and ManytoManyFields are _followed_ beautifully and automatically without me having to specify `follow`. `OnetoOneField` does not seem to be followed. Are OnetoOneFields handled differently? 

(I am using django-reversion-compare and my goal is to show what changed in all fields of my model as well as all fields in OnetoOneField model related to it, across any two versions)

**Comment by etianen** [comment]
I think `OneToOneField` is handled identically to `ForeignKey`. It's a subclass of `ForeignKey`, so should be handled identically.

However, it will only be included in the version data of the owning model (i.e. the model the `OneToOneField` is defined on), and not the model at the other end of the relationship.
