### ISSUE TITLE
Allow displaying "non-recoverable" objects as read-only

### ISSUE THREAD

**Issue by PavelPancocha** [etianen/django-reversion#945]
Idea: It could happen, that you have some `Version` available, but you are not able to recover it.

But it still can have the value for you to just display the data of the object "how did it look" before.

I can prepare PR for this and #944 - @etianen let me know :)

Relates to: #944

**Comment by etianen** [comment]
Unfortunately, the way the recover preview works is that it performs a revert in a database transaction, displays the data, then rolls back the transaction.

Any other way of previewing a rollback falls apart pretty quickly. All related fields (foreign keys, admin inlines) need special-case handling that requires delving into protected Django internals. `django-reversion` used to work like this once and it broke all the time whenever Django changed it's internals.
