### ISSUE TITLE
5.0.11 misses migration files

### ISSUE THREAD

**Issue by pinguin999** [etianen/django-reversion#959]
Hi 

the new release misses migration files. 
Can you run makemigrations and make a new release?

Thanks
Kolja

**Comment by etianen** [comment]
Oops. I'll fix that today.

Feel free to raise a PR if you'd like to get your name on the repo as a
contributor!

**Comment by pinguin999** [comment]
Sure you can find the pull request here: #960

**Comment by etianen** [comment]
Released as v5.0.12 🙇

**Comment by pinguin999** [comment]
Thanks a lot for your fast response and the new release.

**Comment by pinguin999** [comment]
Maybe you can make the old version as yanked https://pypi.org/help/#yanked

**Comment by etianen** [comment]
Good idea! Done.
