### ISSUE TITLE
Migration file missing for changes introduced in v5.0.11

### ISSUE THREAD

**Issue by GitRon** [etianen/django-reversion#962]
Hi there!

I have a checker for missing migrations in my pipeline and this found out that apparently, since v5.0.11 there's a migration file missing.

Would be great to get this added 🙂 

```shell
Migrations for 'reversion':
  /usr/local/lib/python3.12/site-packages/reversion/migrations/0003_alter_revision_options_alter_version_options.py
    - Change Meta options on revision
    - Change Meta options on version
```

Best regards  
Ronny

**Comment by GitRon** [comment]
Sorry! Didnt check properly for issues. My bad 😔

**Comment by etianen** [comment]
It's quite frustrating that changing the Python display name of a model results in a migration... I've never understood why that's the case.

**Comment by GitRon** [comment]
Yes, that's true. It will never have any impact on the table strucutre. Nevertheless, having the check in your CI is a huge improvement. Couldn't live without it anymore 🙃
