### ISSUE TITLE
how to show preview of previous versions in django views. exactly as it is done in admin panel

### ISSUE THREAD

**Issue by amirj700** [etianen/django-reversion#965]
I'm new to django reversion and there might be a simple solution to what I need, however I was not able to find appropriate solution through web search. 
In admin panel I can easily get a list of object versions and preview each history before doing any revert. 

I want to repeat same procedure for my objects using django Views and forms (like UpdateView). for example I place a history button on my form html and by clicking on it receives a list of versions. by clicking on any of them, it shows preview of the selected version in a form of updateView with no reverting. (as same as admin panel).
 
Its good to mention that my forms are rendered using crispy and they contain some many to many fields and 2 inline formsets.

**Comment by etianen** [comment]
There's no exposed functionality for doing this outside of the admin. However, you can adapt the code for rendering the form with a revision here:

https://github.com/etianen/django-reversion/blob/master/reversion/admin.py#L164

The general approach taken is to:

1. Load the revision
2. Start a transaction
3. Revert the revision
4. Render the reverted model
5. Roll back the transaction

This approach means that foreign keys and M2M relationships "just work", as step (3) saves everything back in the database as it was.

If there was demand, this could be made into a context manager for easy use in non-admin views.

**Comment by josidridolfo** [comment]
Boosting this to echo desire for this:

> If there was demand, this could be made into a context manager for easy use in non-admin views.

**Comment by amirj700** [comment]
Thanks to @etianen, This is my implementation but it would be great if this made easy by lib for non admin views:
`def previous_view(request, pk):
    if request.method == 'POST':
        return HttpResponseNotAllowed(['GET'], _('POST method is not allowed for this view.'))
    
    # Retrieve the object to be updated
    instance = get_object_or_404(BaseContract, pk=pk)
    versions = Version.objects.get_for_object(instance).order_by('-id')[:2]
    # Check the length of the versions queryset
    if len(versions) == 1:
        version = versions[0]
        previous_version = None  # Set previous_version to None if there's only one version
    elif len(versions) == 2:
        version, previous_version = versions
    else:
        raise ValueError("Invalid number of versions returned")

    if previous_version:
        # If the form is not submitted, display the form with existing data
        try:
            with transaction.atomic(using=previous_version.db):
                previous_version.revision.revert(delete=True)
                object: BaseContract = previous_version.object
                form = ProductForm(instance=object, user=request.user, menu_disabled=True)
                for key, field in form.fields.items():
                    field.disabled = True
                rend = render(request, 'path_to_form/item_form.html', {
                    'form': form,
                })
                raise _RollBackRevisionView(rend)
        except _RollBackRevisionView as ex:
            return ex.response # Render the update form template with the form
        return None
    else:
        return HttpResponseNotAllowed(['GET'], _('no previous version'))`

**Comment by josidridolfo** [comment]
Made some quick changes to try to trace what's happening. It looks like the object with all of its m2m fields is not being passed as expected to the exception handler:


```
...
                    with transaction.atomic(using=version.db):
                        version.revert()
                        # with reversion.create_revision():
                        object: type(self) = version.object
                        print(f'The found object is of type: {type(object)}')
                        print(f'The found object has the following state {object.state}')
                        print(f'The found object has the following suppliers_invited: {object.suppliers_invited.all()}')
                        print(f'Passing the above object to the Exception handler')
                        raise MostRecentApprovedObject(object)
                except MostRecentApprovedObject as ex:
                    print('Handling the exception! Returning the object')
                    print(f'The returned object\'s state is: {ex.object.state}')
                    print(f'The returned object\'s invited suppliers are: {ex.object.suppliers_invited.all()}')
                    return ex.object
...
```



```
web-1  | The found object is of type: <class 'bids.models.Bid'>
web-1  | The found object has the following state APPROVED
web-1  | The found object has the following suppliers_invited: <QuerySet [<Supplier: Adkins, Rice and Ramirez>, <Supplier: Alexander-Ward>, <Supplier: Bailey, Cobb and Holt>]> # GREAT! This is what we want to see!
web-1  | Passing the above object to the Exception handler
web-1  | Handling the exception! Returning the object
web-1  | The returned object's state is: APPROVED
web-1  | The returned object's invited suppliers are: <QuerySet []> # Boooooo - why didn't the Queryset from earlier get passed?
```


Any ideas on how to resolve this?

**Comment by amirj700** [comment]
in cbv, m2m fields and inline forms are rendered after main form procedure by their managers, and when you revert as exception raise and get back to current state of db,  their render will be with latest version thanks to their manager. thats why I changed from cbv to view function to get a complete version as final render.

**Comment by josidridolfo** [comment]
Thanks for your quick and helpful responses @amirj700!

So all of my CBVs should now be function-based views? Looks like I have a lot of refactoring ahead of me...

Assume the CBVs are just for DetailViews: given your experience, do you think that overriding the dispatch() or get() methods will enable me to keep CBVs and monkey-patch a solution? Or do you think refactoring and making CBVs are the way to go?

**Comment by amirj700** [comment]
I did not changed all of my cbvs, I only changed the old version view request (one view), but it was good for my senario, for you it might differ. I tried overriding get and dispatch but because I had inlines forms it was way harder than I thought.

**Comment by josidridolfo** [comment]
> I only changed the old version view request (one view)

This is a great idea!

So, instead of refactoring and changing my CBVs, create separate FBVs only for PENDING objects. CBVs should redirect users to the pending page iff the object is PENDING, and then handle the view separately. 

I'm very new to all this and greatly appreciate your help and guidance!

**Comment by josidridolfo** [comment]
@etianen and @amirj700:

@etianen - thank you again for creating such an extremely useful tool!

@amirj700 - thank you *so much* for your guidance and advice! I've been struggling with this for a week and thanks in large part to your help I've made it work!

**Comment by amirj700** [comment]
Great! you are welcome.
