### ISSUE TITLE
Question: usage of django-reversion in larger scale open source projects

### ISSUE THREAD

**Issue by ollejernstrom** [etianen/django-reversion#973]
Love the things about django-reversion, and I think it might be able to solve the issues we are facing. 

I was wondering if there are any known large scale open source applications an aspiring adopter can view for some early stage inspiration as to were to start instead of diving head first?

Again, nice work!

**Comment by etianen** [comment]
I'm glad to hear you're considering `django-reversion`.

You can actually see a big old list of projects using `django-reversion` here:

https://github.com/etianen/django-reversion/network/dependents

Unfortunately, there's no ability to sort by stars or forks, but I'm sure a patient person could browse that list and take a look at some interesting looking repos! 💪
