### ISSUE TITLE
Django 5.1 compatibility

### ISSUE THREAD

**Issue by g10f** [etianen/django-reversion#974]
Currently django-reversion does not work with django 5.1.
E.g  is_hidden() Method on ManyToOneRel class doesn't exist anymore.

**Comment by woojing** [comment]
It is solved in https://github.com/etianen/django-reversion/pull/969

**Comment by spapas** [comment]
Any idea when we'll get a new release of django-reversion ? Django 5.1 has landed but the patched version of django-reversion isn't on pypi yet.

TIA

**Comment by spapas** [comment]
If it helps, I tested Django 5.1 it with the master version ([7c23ff4](https://github.com/etianen/django-reversion/commit/7c23ff4bae5c495a94cf1bfd3e5ad395f223caf2)) and works fine, at least with my project.

**Comment by woojing** [comment]
Hey @etianen,

First off, thanks a ton for all your work on django-reversion! It’s been super helpful for our project. 🙌

I wanted to check in and see if there’s a chance for a new release soon.

With Django 5.1 coming out, the current version of django-reversion is no longer compatible, and we’re really eager to keep things running smoothly.

Of course, no pressure--just wanted to bring it to your attention. Thanks again for everything you do!

**Comment by etianen** [comment]
This will shortly be released as v5.1.0 ❤️
